// GENERATED by contentc — DO NOT EDIT

//! Compiler output.
//!
//! Every module here is emitted by `cargo run -p contentc` from the records
//! under `content/`. **Do not edit these files by hand** — the next compile
//! overwrites them, and `cargo run -p contentc -- --check` is the gate that
//! fails if they are stale.
//!
//! The arrow points one way: `content/` describes what things ARE, this crate
//! is the compiled form of that, and `godgame-core` reads it and never writes
//! it. That is what makes adding a block a content change rather than a code
//! change.

pub mod blocks;
pub mod items;
pub mod mobs;
pub mod sprites;
pub mod structs;
pub mod worldgen;

/// One flat table, type-erased so the gates can walk them by name.
///
/// The game never touches this — it indexes the concrete `[u8; N]` statics
/// directly. It exists because Rust cannot look a static up by name and two
/// consumers need to: the parity test that diffs these tables against the
/// TypeScript build, and the tuning index.
#[derive(Clone, Copy, Debug)]
pub enum Table {
    U8(&'static [u8]),
    U16(&'static [u16]),
    U32(&'static [u32]),
    F32(&'static [f32]),
}

impl Table {
    pub fn len(&self) -> usize {
        match self {
            Table::U8(v) => v.len(),
            Table::U16(v) => v.len(),
            Table::U32(v) => v.len(),
            Table::F32(v) => v.len(),
        }
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// The slot as an `f64`, which is lossless for every width used here.
    pub fn get(&self, i: usize) -> f64 {
        match self {
            Table::U8(v) => v[i] as f64,
            Table::U16(v) => v[i] as f64,
            Table::U32(v) => v[i] as f64,
            Table::F32(v) => v[i] as f64,
        }
    }

    pub fn kind(&self) -> &'static str {
        match self {
            Table::U8(_) => "u8",
            Table::U16(_) => "u16",
            Table::U32(_) => "u32",
            Table::F32(_) => "f32",
        }
    }
}

/// Every module's tables, for the gates. `(module, name, table)`.
pub fn all_tables() -> Vec<(&'static str, &'static str, Table)> {
    let mut out = Vec::new();
    for (n, t) in blocks::BLOCK_TABLES {
        out.push(("blocks", *n, *t));
    }
    for (n, t) in items::ITEM_TABLES {
        out.push(("items", *n, *t));
    }
    for (n, t) in mobs::MOB_TABLES {
        out.push(("mobs", *n, *t));
    }
    for (n, t) in sprites::SPRITE_TABLES {
        out.push(("sprites", *n, *t));
    }
    for (n, t) in structs::STRUCT_TABLES {
        out.push(("structs", *n, *t));
    }
    for (n, t) in worldgen::FEATURE_TABLES {
        out.push(("worldgen", *n, *t));
    }
    out
}

/// Every module's authoring id -> code, for the gates. `(module, id, code)`.
pub fn all_codes() -> Vec<(&'static str, &'static str, u16)> {
    let mut out = Vec::new();
    for (id, c) in blocks::BLOCK_CODES {
        out.push(("blocks", *id, *c));
    }
    for (id, c) in items::ITEM_CODES {
        out.push(("items", *id, *c));
    }
    for (id, c) in mobs::MOB_CODES {
        out.push(("mobs", *id, *c));
    }
    for (id, c) in sprites::SPRITE_CODES {
        out.push(("sprites", *id, *c));
    }
    for (id, c) in structs::STRUCT_CODES {
        out.push(("structs", *id, *c));
    }
    for (id, c) in worldgen::FEATURE_CODES {
        out.push(("worldgen", *id, *c));
    }
    out
}

/// Every module's pair matrices, for the gates. `(module, name, side, bits)`.
pub fn all_matrices() -> Vec<(&'static str, &'static str, usize, &'static [u8])> {
    #[allow(unused_mut)]
    let mut out = Vec::new();
    for (n, side, bits) in blocks::BLOCK_MATRICES {
        out.push(("blocks", *n, *side, *bits));
    }
    out
}
