// GENERATED by contentc — DO NOT EDIT
// 20 mobs from 3 source file(s):
//   content/mobs/cavern.toml
//   content/mobs/deep.toml
//   content/mobs/surface.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which movement/decision routine drives this creature.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobBrain {
    Walker,
    Hopper,
    Flyer,
    Skitter,
    Burrower,
}

/// Damage tags this creature ignores entirely — a fire elemental should not
/// burn.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobSpecImmune {
    Fire,
    Acid,
    Ice,
    Impact,
    Poison,
}

/// Depth bands this may spawn in. The coarse habitat knob.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobSpecBands {
    Surface,
    Shallow,
    Cavern,
    Deep,
}

/// What it throws. Speed, size and on-hit rider come from the table in
/// MobSystem.ts.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobProjectile {
    IceShard,
    Ember,
    Spore,
    Stone,
}

/// Which pose this sequence supplies. Closed vocabulary — a typo is a build
/// error. The facade names this union `MobPose`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobSpecSeqState {
    Idle,
    Move,
    Air,
}

/// How the frames are stepped. Names are the contract with the runtime's
/// picker.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MobSpecSeqMode {
    Hold,
    Loop,
    Once,
    Phase,
    Ambient,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MobDrop {
    /// Item id, or a `a|b|c` preference chain. Unvalidated until the item
    /// registry exists.
    pub item: &'static str,
    /// Inclusive stack size range.
    pub count: [f32; 2],
    /// Probability this entry drops at all.
    pub chance: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MobSpecSeq {
    /// Which pose this sequence supplies. Closed vocabulary — a typo is a build
    /// error. The facade names this union `MobPose`.
    pub state: MobSpecSeqState,
    /// How the frames are stepped. Names are the contract with the runtime's
    /// picker.
    pub mode: MobSpecSeqMode,
    /// Playback rate for THIS sequence. 0 inherits the sprite's `fps`, which is
    /// why the default is 0 and not 8 — 0 is 'unset', and an explicit 8 here
    /// would pin the sequence if the sprite were ever retuned.
    pub fps: f32,
    /// `ambient` only: seconds between interrupts. 0 = never interrupt. The
    /// interrupt frame is the sequence's LAST frame, so the ambient cycle itself
    /// is frames[0..n-2].
    pub blink_every: f32,
    /// `ambient` only: seconds the interrupt frame is held.
    pub blink_for: f32,
    /// The frames, as a `'''` body: `cellsH` rows per frame, frames separated by
    /// a blank line. Read it as a filmstrip.
    pub frames: &'static [&'static str],
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MobSpecRanged {
    /// What it throws. Speed, size and on-hit rider come from the table in
    /// MobSystem.ts.
    pub projectile: MobProjectile,
    /// Seconds between shots. A DURATION — never body-scaled.
    pub cooldown: f32,
    /// Horizontal firing radius, world px. Perception, so not body-scaled.
    pub range: f32,
    /// Health taken on a projectile hit.
    pub damage: f32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MobSpecArt {
    /// Art grid width in world cells. One art pixel is one world cell.
    pub cells_w: i32,
    /// Art grid height in world cells. Every frame must have exactly this many
    /// rows.
    pub cells_h: i32,
    /// Palette, "#rrggbb" per index. Index 0 is the transparent slot and is
    /// written "." — it is never painted, so its value is a placeholder, not a
    /// colour. Frame characters are digits indexing this list.
    pub pal: &'static [&'static str],
    /// Sprite-wide playback rate. A sequence with its own non-zero `fps`
    /// overrides it, so this is the value for everything that has no reason to be
    /// special.
    pub fps: Option<f32>,
    /// How many tinted copies of the whole sprite to bake. 1 = just the palette
    /// as authored. More than one lets a crowd of the same creature read as
    /// individuals without authoring a second palette, at the cost of one extra
    /// baked canvas set each.
    pub variants: Option<i32>,
    /// One animation sequence per entry, in file order. Attributes as keys,
    /// frames in the `frames` body.
    pub seq: Option<&'static [MobSpecSeq]>,
}

/// The compiled shape of one mob. Derived from crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MobSpec {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Which movement/decision routine drives this creature.
    pub brain: MobBrain,
    /// Display name (bestiary UI, debug HUD).
    pub name: &'static str,
    /// Hit points.
    pub max_health: f32,
    /// Health taken from the player per contact hit. 0 = harmless.
    pub contact_damage: f32,
    /// Seconds this creature must wait between contact hits. A DURATION — never
    /// body-scaled.
    pub attack_cooldown: f32,
    /// Flat damage subtracted from every hit this creature takes. Flat rather
    /// than a percentage so a heavily armoured creature is still killable with a
    /// weak weapon, just slowly; the combat code floors the result at 1.
    pub armor: f32,
    /// Damage tags this creature ignores entirely — a fire elemental should not
    /// burn.
    pub immune: &'static [MobSpecImmune],
    /// Collision box width in world cells. Independent of `art.cellsW`: a sprite
    /// may overhang its own hitbox (wings, antennae) without widening what the
    /// world collides with.
    pub body_cells_w: i32,
    /// Collision box height in world cells, AND the body-scale anchor every
    /// distance-bearing stat below is multiplied against. Change this and the
    /// creature's whole motion budget moves with it — which is what you want
    /// when a creature genuinely gets bigger, and is exactly what you do not want
    /// when only its drawing changes.
    pub body_cells_h: i32,
    /// Patrol speed. Body-scaled by the facade.
    pub speed: f32,
    /// Speed while alerted. Defaults to `speed` — a creature that does not
    /// change gear.
    pub chase_speed: Option<f32>,
    /// Initial upward velocity for a hop, ledge-leap or eruption. 0 = cannot
    /// leave the ground.
    pub jump_speed: f32,
    /// Multiplier on the player's raw gravity. 0 = flight (the flyer brain
    /// assumes it).
    pub gravity_scale: f32,
    /// Horizontal notice radius for a hostile. 0 = never aggresses.
    pub aggro_px: f32,
    /// Vertical half-height of the notice box.
    pub aggro_y_px: f32,
    /// Horizontal panic radius. Non-zero makes the creature run AWAY and
    /// overrides aggroPx.
    pub flee_px: f32,
    pub ranged: Option<MobSpecRanged>,
    /// Seconds between hops / dives / surfacings, depending on brain. A DURATION.
    pub beat: f32,
    /// Additive self-illumination drawn in the post-light overlay pass, 0..1.
    pub glow: f32,
    /// Skip the material-hazard probe outright. Blunter than `immune fire` and
    /// kept separate from it: this one says 'nothing the world is made of can
    /// hurt me', which is what a creature that LIVES in lava needs.
    pub lava_immune: bool,
    /// Particle colour for hits and death bursts — the creature's body tone.
    pub blood: [u8; 3],
    /// Experience awarded for a kill.
    pub xp: i32,
    /// Currency awarded for a kill, separate from xp.
    pub value: i32,
    /// What killing this yields. Rolled independently, so several entries can all
    /// drop.
    pub drops: Option<&'static [MobDrop]>,
    /// Depth bands this may spawn in. The coarse habitat knob.
    pub bands: &'static [MobSpecBands],
    /// Cells below the local surface before this may spawn. Overlays `bands` for
    /// the few species that want a narrower slice than a whole band.
    pub min_depth: i32,
    /// Last depth this may spawn at. Default 65535 = no upper bound beyond
    /// `bands`.
    pub max_depth: i32,
    /// Dominant SURFACE biome ids this may spawn in (src/sim/biomes.ts). Absent =
    /// any biome. Not a `ref(biome)` yet: biomes are still hand-written, and a
    /// forward reference that fails the build is worse than one that does not.
    pub biomes: Option<&'static [&'static str]>,
    /// Weight is multiplied by darkness at the surface, so these thin out in
    /// daylight.
    pub nocturnal: bool,
    /// Requires lava within a short radius of the spawn point.
    pub needs_lava: bool,
    /// How many spawn together. The extras are placed around the first one and
    /// each must pass the same footing test, so a pack in bad terrain simply
    /// arrives smaller rather than clipping into rock.
    pub pack_size: [f32; 2],
    /// Relative spawn weight among eligible defs. 0 = never spawns naturally.
    pub weight: f32,
    pub art: Option<MobSpecArt>,
}

/// Authoring ids, index == code.
pub static MOB_IDS: [&str; 20] = [
    "grubling",
    "critter",
    "sandworm",
    "frostmite",
    "thornhopper",
    "slime",
    "bat",
    "stoneback",
    "cinder_moth",
    "bloat",
    "driftling",
    "emberling",
    "sentinel",
    "sporeling",
    "skeleton",
    "glimmerback",
    "gulper",
    "bladeframe",
    "slagworm",
    "mycelith",
];

/// Every def, index == code, tombstones included.
pub static MOBS: [MobSpec; 20] = [
    MobSpec {
        id: "grubling",
        code: 0,
        brain: MobBrain::Walker,
        name: "Grubling",
        max_health: 14.0,
        contact_damage: 8.0,
        attack_cooldown: 0.85,
        armor: 1.0,
        immune: &[],
        body_cells_w: 2,
        body_cells_h: 2,
        speed: 110.0,
        chase_speed: Some(215.0),
        jump_speed: 0.0,
        gravity_scale: 1.0,
        aggro_px: 130.0,
        aggro_y_px: 40.0,
        flee_px: 0.0,
        ranged: None,
        beat: 2.4,
        glow: 0.0,
        lava_immune: false,
        blood: [169, 117, 61],
        xp: 4,
        value: 2,
        drops: Some(&[
            MobDrop {
                item: "chitin",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "grub_meat",
                count: [1.0, 1.0],
                chance: 0.35,
            },
        ]),
        bands: &[MobSpecBands::Surface, MobSpecBands::Shallow],
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["plains", "savanna", "jungle", "swamp", "tundra", "desert"]),
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 26.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 2,
            pal: &[".", "#3a2617", "#6f4a2a", "#a9753d", "#ffd27a"],
            fps: Some(7.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.4,
                    blink_for: 0.14,
                    frames: &["23", "11", "", "22", "11", "", "34", "11"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["23", "1.", "", "23", "11", "", "23", ".1", "", "23", "11"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["23", ".."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "critter",
        code: 1,
        brain: MobBrain::Skitter,
        name: "Critter",
        max_health: 6.0,
        contact_damage: 0.0,
        attack_cooldown: 0.85,
        armor: 0.0,
        immune: &[],
        body_cells_w: 2,
        body_cells_h: 2,
        speed: 120.0,
        chase_speed: Some(330.0),
        jump_speed: 560.0,
        gravity_scale: 1.0,
        aggro_px: 0.0,
        aggro_y_px: 60.0,
        flee_px: 105.0,
        ranged: None,
        beat: 1.6,
        glow: 0.0,
        lava_immune: false,
        blood: [242, 227, 200],
        xp: 1,
        value: 0,
        drops: Some(&[MobDrop {
            item: "hide",
            count: [1.0, 1.0],
            chance: 0.6,
        }]),
        bands: &[MobSpecBands::Surface],
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["plains", "savanna", "jungle", "swamp", "tundra", "glacier"]),
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 22.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 2,
            pal: &[".", "#3a2c22", "#c8b7a0", "#f2e3c8", "#ff9a9a"],
            fps: Some(12.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.6,
                    blink_for: 0.12,
                    frames: &[".3", "22", "", "23", "22", "", ".4", "22"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".3", "12", "", ".3", "22", "", ".3", "21", "", ".3", "22"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 14.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".3", "22", "", "23", ".2"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "sandworm",
        code: 2,
        brain: MobBrain::Burrower,
        name: "Sandworm",
        max_health: 30.0,
        contact_damage: 16.0,
        attack_cooldown: 1.0,
        armor: 2.0,
        immune: &[],
        body_cells_w: 4,
        body_cells_h: 2,
        speed: 150.0,
        chase_speed: Some(210.0),
        jump_speed: 700.0,
        gravity_scale: 1.0,
        aggro_px: 190.0,
        aggro_y_px: 110.0,
        flee_px: 0.0,
        ranged: None,
        beat: 2.8,
        glow: 0.0,
        lava_immune: false,
        blood: [195, 154, 90],
        xp: 12,
        value: 6,
        drops: Some(&[
            MobDrop {
                item: "worm_hide",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "chitin",
                count: [1.0, 3.0],
                chance: 0.5,
            },
        ]),
        bands: &[MobSpecBands::Surface, MobSpecBands::Shallow],
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["desert", "savanna", "tundra", "glacier"]),
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 10.0,
        art: Some(MobSpecArt {
            cells_w: 4,
            cells_h: 2,
            pal: &[".", "#6b4a24", "#8a6a3c", "#c39a5a", "#e8cf9a", "#ff6b57"],
            fps: Some(8.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 4.2,
                    blink_for: 0.18,
                    frames: &["1231", "1..1", "", "1221", "1..1", "", "1235", "1..1"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "1234", "11..", "", "1234", ".11.", "", "1234", "..11", "", "1234", ".11.",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 10.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["1235", "....", "", "1234", "...."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "frostmite",
        code: 3,
        brain: MobBrain::Walker,
        name: "Frostmite",
        max_health: 7.0,
        contact_damage: 5.0,
        attack_cooldown: 0.6,
        armor: 0.0,
        immune: &[MobSpecImmune::Ice],
        body_cells_w: 2,
        body_cells_h: 2,
        speed: 140.0,
        chase_speed: Some(260.0),
        jump_speed: 480.0,
        gravity_scale: 1.0,
        aggro_px: 120.0,
        aggro_y_px: 45.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.2,
        glow: 0.0,
        lava_immune: false,
        blood: [127, 212, 232],
        xp: 2,
        value: 0,
        drops: Some(&[MobDrop {
            item: "ice_shard",
            count: [1.0, 2.0],
            chance: 0.45,
        }]),
        bands: &[MobSpecBands::Surface, MobSpecBands::Shallow],
        min_depth: 0,
        max_depth: 40,
        biomes: Some(&["glacier", "tundra"]),
        nocturnal: false,
        needs_lava: false,
        pack_size: [2.0, 4.0],
        weight: 18.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 2,
            pal: &[".", "#2a5570", "#3c6f8a", "#7fd4e8", "#eaffff"],
            fps: Some(11.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.2,
                    blink_for: 0.1,
                    frames: &[".4", "32", "", ".3", "32", "", "44", "32"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "31", "", ".4", "32", "", ".4", "13", "", ".4", "32"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 12.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "33", "", "44", ".3"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "thornhopper",
        code: 4,
        brain: MobBrain::Hopper,
        name: "Thornhopper",
        max_health: 18.0,
        contact_damage: 7.0,
        attack_cooldown: 0.85,
        armor: 0.0,
        immune: &[MobSpecImmune::Poison],
        body_cells_w: 3,
        body_cells_h: 2,
        speed: 170.0,
        chase_speed: None,
        jump_speed: 600.0,
        gravity_scale: 1.0,
        aggro_px: 150.0,
        aggro_y_px: 80.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::Spore,
            cooldown: 1.9,
            range: 165.0,
            damage: 6.0,
        }),
        beat: 1.3,
        glow: 0.0,
        lava_immune: false,
        blood: [122, 79, 154],
        xp: 7,
        value: 3,
        drops: Some(&[MobDrop {
            item: "spore_sac",
            count: [1.0, 2.0],
            chance: 0.7,
        }]),
        bands: &[MobSpecBands::Surface, MobSpecBands::Shallow],
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["jungle", "swamp"]),
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 2.0],
        weight: 14.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 2,
            pal: &[".", "#2a1b38", "#3a2a4a", "#7a4f9a", "#c8ff7a", "#e8ffb4"],
            fps: Some(7.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.8,
                    blink_for: 0.22,
                    frames: &[".4.", "131", "", ".4.", "133", "", ".5.", "131"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4.", "131", "", "...", "331", "", ".4.", "133"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 10.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4.", ".3.", "", "4.4", "333"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "slime",
        code: 5,
        brain: MobBrain::Hopper,
        name: "Slime",
        max_health: 20.0,
        contact_damage: 10.0,
        attack_cooldown: 0.85,
        armor: 0.0,
        immune: &[],
        body_cells_w: 3,
        body_cells_h: 2,
        speed: 190.0,
        chase_speed: None,
        jump_speed: 640.0,
        gravity_scale: 1.0,
        aggro_px: 145.0,
        aggro_y_px: 70.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.05,
        glow: 0.0,
        lava_immune: false,
        blood: [73, 176, 119],
        xp: 5,
        value: 2,
        drops: Some(&[MobDrop {
            item: "slime_gel",
            count: [1.0, 2.0],
            chance: 1.0,
        }]),
        bands: &[MobSpecBands::Shallow, MobSpecBands::Cavern],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 20.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 2,
            pal: &[".", "#1e4a34", "#2c6f4a", "#49b077", "#a8f0c4"],
            fps: Some(6.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.1,
                    blink_for: 0.16,
                    frames: &[".4.", "232", "", "...", "333", "", "434", "333"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["...", "333", "", ".4.", "232", "", ".3.", "333"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 9.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4.", ".3.", "", "434", "333"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "bat",
        code: 6,
        brain: MobBrain::Flyer,
        name: "Cave Bat",
        max_health: 10.0,
        contact_damage: 6.0,
        attack_cooldown: 0.7,
        armor: 0.0,
        immune: &[],
        body_cells_w: 3,
        body_cells_h: 2,
        speed: 200.0,
        chase_speed: Some(360.0),
        jump_speed: 0.0,
        gravity_scale: 0.0,
        aggro_px: 170.0,
        aggro_y_px: 130.0,
        flee_px: 0.0,
        ranged: None,
        beat: 0.9,
        glow: 0.0,
        lava_immune: false,
        blood: [74, 61, 92],
        xp: 3,
        value: 0,
        drops: Some(&[MobDrop {
            item: "bat_wing",
            count: [1.0, 1.0],
            chance: 0.4,
        }]),
        bands: &[
            MobSpecBands::Surface,
            MobSpecBands::Shallow,
            MobSpecBands::Cavern,
            MobSpecBands::Deep,
        ],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: true,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 12.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 2,
            pal: &[".", "#1a1424", "#2a2233", "#4a3d5c", "#ff9a6b"],
            fps: Some(14.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.6,
                    blink_for: 0.12,
                    frames: &["3.3", ".4.", "", "...", "343", "", "3.3", ".2."],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "3.3", ".4.", "", "2.2", "343", "", "...", "343", "", "2.2", "343",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["...", "343"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "stoneback",
        code: 7,
        brain: MobBrain::Walker,
        name: "Stoneback",
        max_health: 55.0,
        contact_damage: 14.0,
        attack_cooldown: 1.2,
        armor: 8.0,
        immune: &[MobSpecImmune::Impact],
        body_cells_w: 4,
        body_cells_h: 3,
        speed: 80.0,
        chase_speed: Some(130.0),
        jump_speed: 0.0,
        gravity_scale: 1.0,
        aggro_px: 110.0,
        aggro_y_px: 55.0,
        flee_px: 0.0,
        ranged: None,
        beat: 3.2,
        glow: 0.0,
        lava_immune: false,
        blood: [110, 110, 110],
        xp: 18,
        value: 10,
        drops: Some(&[
            MobDrop {
                item: "stone_chunk",
                count: [2.0, 4.0],
                chance: 1.0,
            },
            MobDrop {
                item: "iron_ore",
                count: [1.0, 2.0],
                chance: 0.45,
            },
            MobDrop {
                item: "gem",
                count: [1.0, 1.0],
                chance: 0.08,
            },
        ]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 9.0,
        art: Some(MobSpecArt {
            cells_w: 4,
            cells_h: 3,
            pal: &[".", "#262626", "#3a3a3a", "#6e6e6e", "#8f8f8f", "#b8b8b8"],
            fps: Some(4.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 5.5,
                    blink_for: 0.2,
                    frames: &[
                        ".44.", "3333", "1..1", "", ".44.", "3223", ".11.", "", ".54.", "3333",
                        "1..1",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        ".44.", "3333", "1..1", "", ".44.", "3333", ".1.1", "", ".44.", "3333",
                        ".11.", "", ".44.", "3333", "1.1.",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".44.", "3333", "...."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "cinder_moth",
        code: 8,
        brain: MobBrain::Flyer,
        name: "Cinder Moth",
        max_health: 12.0,
        contact_damage: 5.0,
        attack_cooldown: 0.8,
        armor: 0.0,
        immune: &[MobSpecImmune::Fire],
        body_cells_w: 3,
        body_cells_h: 2,
        speed: 180.0,
        chase_speed: Some(300.0),
        jump_speed: 0.0,
        gravity_scale: 0.0,
        aggro_px: 185.0,
        aggro_y_px: 120.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::Ember,
            cooldown: 2.2,
            range: 190.0,
            damage: 7.0,
        }),
        beat: 1.1,
        glow: 0.35,
        lava_immune: false,
        blood: [255, 122, 44],
        xp: 8,
        value: 4,
        drops: Some(&[
            MobDrop {
                item: "ash_pile",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "moth_dust",
                count: [1.0, 1.0],
                chance: 0.3,
            },
        ]),
        bands: &[
            MobSpecBands::Surface,
            MobSpecBands::Shallow,
            MobSpecBands::Cavern,
        ],
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["volcanic", "desert", "savanna"]),
        nocturnal: true,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 11.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 2,
            pal: &[".", "#3a1408", "#4a1e10", "#ff7a2c", "#ffd68a", "#fff2c8"],
            fps: Some(13.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.4,
                    blink_for: 0.1,
                    frames: &["4.4", ".3.", "", "2.2", "232", "", "5.5", ".3."],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "4.4", ".3.", "", "2.2", "232", "", "...", "434", "", "2.2", "232",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["...", "434"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "bloat",
        code: 9,
        brain: MobBrain::Hopper,
        name: "Bloat",
        max_health: 46.0,
        contact_damage: 18.0,
        attack_cooldown: 1.1,
        armor: 0.0,
        immune: &[],
        body_cells_w: 4,
        body_cells_h: 3,
        speed: 150.0,
        chase_speed: None,
        jump_speed: 560.0,
        gravity_scale: 1.0,
        aggro_px: 165.0,
        aggro_y_px: 90.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.7,
        glow: 0.0,
        lava_immune: false,
        blood: [107, 79, 160],
        xp: 14,
        value: 6,
        drops: Some(&[
            MobDrop {
                item: "slime_gel",
                count: [2.0, 4.0],
                chance: 1.0,
            },
            MobDrop {
                item: "crystal_shard",
                count: [1.0, 1.0],
                chance: 0.2,
            },
        ]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 8.0,
        art: Some(MobSpecArt {
            cells_w: 4,
            cells_h: 3,
            pal: &[".", "#241a3c", "#3b2a5c", "#6b4fa0", "#a688e0", "#c9a6ff"],
            fps: Some(5.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.4,
                    blink_for: 0.18,
                    frames: &[
                        ".44.", "3333", "2332", "", "....", "3443", "2332", "", ".55.", "3443",
                        "2332",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "....", "3443", "2332", "", ".44.", "3333", "3333", "", ".4..", "3433",
                        "2332",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 8.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".44.", ".33.", ".22.", "", "4444", "3333", ".33."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "driftling",
        code: 10,
        brain: MobBrain::Flyer,
        name: "Driftling",
        max_health: 5.0,
        contact_damage: 0.0,
        attack_cooldown: 0.85,
        armor: 0.0,
        immune: &[],
        body_cells_w: 2,
        body_cells_h: 2,
        speed: 70.0,
        chase_speed: None,
        jump_speed: 0.0,
        gravity_scale: 0.0,
        aggro_px: 0.0,
        aggro_y_px: 60.0,
        flee_px: 70.0,
        ranged: None,
        beat: 2.2,
        glow: 0.55,
        lava_immune: false,
        blood: [158, 242, 255],
        xp: 2,
        value: 0,
        drops: Some(&[MobDrop {
            item: "crystal_shard",
            count: [1.0, 1.0],
            chance: 0.5,
        }]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 12.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 2,
            pal: &[".", "#2c6070", "#3f7f8c", "#9ef2ff", "#e6ffff"],
            fps: Some(4.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.7,
                    blink_for: 0.22,
                    frames: &[".4", "3.", "", ".3", "2.", "", "44", "33"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "3.", "", "4.", ".3", "", ".3", "4.", "", "3.", ".4"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", ".3"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "emberling",
        code: 11,
        brain: MobBrain::Walker,
        name: "Emberling",
        max_health: 26.0,
        contact_damage: 22.0,
        attack_cooldown: 0.9,
        armor: 2.0,
        immune: &[MobSpecImmune::Fire],
        body_cells_w: 2,
        body_cells_h: 3,
        speed: 130.0,
        chase_speed: Some(250.0),
        jump_speed: 640.0,
        gravity_scale: 1.0,
        aggro_px: 175.0,
        aggro_y_px: 80.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.4,
        glow: 0.45,
        lava_immune: true,
        blood: [255, 138, 60],
        xp: 16,
        value: 8,
        drops: Some(&[
            MobDrop {
                item: "ember_core",
                count: [1.0, 1.0],
                chance: 1.0,
            },
            MobDrop {
                item: "ash_pile",
                count: [1.0, 3.0],
                chance: 1.0,
            },
        ]),
        bands: &[
            MobSpecBands::Shallow,
            MobSpecBands::Cavern,
            MobSpecBands::Deep,
        ],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: true,
        pack_size: [1.0, 1.0],
        weight: 14.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 3,
            pal: &[".", "#2b1a18", "#7a3320", "#ff8a3c", "#ffe08a", "#fff6d0"],
            fps: Some(9.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.5,
                    blink_for: 0.12,
                    frames: &[".4", "32", "11", "", ".3", "32", "11", "", ".5", "43", "11"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        ".4", "32", "1.", "", ".4", "32", "11", "", ".4", "32", ".1", "", ".4",
                        "32", "11",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 11.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "33", ".1", "", ".5", "43", ".."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "sentinel",
        code: 12,
        brain: MobBrain::Walker,
        name: "Sentinel",
        max_health: 40.0,
        contact_damage: 9.0,
        attack_cooldown: 1.0,
        armor: 5.0,
        immune: &[MobSpecImmune::Ice, MobSpecImmune::Impact],
        body_cells_w: 3,
        body_cells_h: 3,
        speed: 95.0,
        chase_speed: Some(150.0),
        jump_speed: 0.0,
        gravity_scale: 1.0,
        aggro_px: 210.0,
        aggro_y_px: 100.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::IceShard,
            cooldown: 1.6,
            range: 230.0,
            damage: 11.0,
        }),
        beat: 2.6,
        glow: 0.2,
        lava_immune: false,
        blood: [159, 232, 255],
        xp: 26,
        value: 18,
        drops: Some(&[
            MobDrop {
                item: "iron_bar",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "copper_bar",
                count: [1.0, 1.0],
                chance: 0.6,
            },
            MobDrop {
                item: "machine_scrap",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "frozen_core",
                count: [1.0, 1.0],
                chance: 0.25,
            },
        ]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 150,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 7.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 3,
            pal: &[".", "#2a2f38", "#3a3f4a", "#6b7488", "#9fe8ff", "#ff5a4a"],
            fps: Some(6.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.1,
                    blink_for: 0.16,
                    frames: &[
                        ".4.", "232", "2.2", "", ".3.", "232", "2.2", "", ".5.", "232", "2.2",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        ".4.", "232", "2..", "", ".4.", "232", "2.2", "", ".4.", "232", "..2", "",
                        ".4.", "232", "2.2",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4.", "232", "..."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "sporeling",
        code: 13,
        brain: MobBrain::Hopper,
        name: "Sporeling",
        max_health: 11.0,
        contact_damage: 4.0,
        attack_cooldown: 0.85,
        armor: 0.0,
        immune: &[MobSpecImmune::Poison, MobSpecImmune::Acid],
        body_cells_w: 2,
        body_cells_h: 3,
        speed: 150.0,
        chase_speed: None,
        jump_speed: 520.0,
        gravity_scale: 1.0,
        aggro_px: 160.0,
        aggro_y_px: 85.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::Spore,
            cooldown: 2.4,
            range: 175.0,
            damage: 5.0,
        }),
        beat: 1.5,
        glow: 0.15,
        lava_immune: false,
        blood: [127, 176, 74],
        xp: 6,
        value: 3,
        drops: Some(&[
            MobDrop {
                item: "spore_sac",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "mushroom_cap",
                count: [1.0, 1.0],
                chance: 0.55,
            },
        ]),
        bands: &[MobSpecBands::Deep],
        min_depth: 240,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [2.0, 3.0],
        weight: 13.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 3,
            pal: &[".", "#1e3418", "#2f4a2a", "#7fb04a", "#d8ff9a", "#f2ffd8"],
            fps: Some(7.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.3,
                    blink_for: 0.14,
                    frames: &[".4", "33", "22", "", ".3", "33", "22", "", "44", "33", "22"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "33", "22", "", ".4", "33", "2.", "", ".4", "33", ".2"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 10.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4", "33", "..", "", "44", "33", ".."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "skeleton",
        code: 14,
        brain: MobBrain::Walker,
        name: "Skeleton",
        max_health: 24.0,
        contact_damage: 11.0,
        attack_cooldown: 0.9,
        armor: 1.0,
        immune: &[MobSpecImmune::Poison],
        body_cells_w: 2,
        body_cells_h: 3,
        speed: 120.0,
        chase_speed: Some(210.0),
        jump_speed: 500.0,
        gravity_scale: 1.0,
        aggro_px: 200.0,
        aggro_y_px: 90.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::Stone,
            cooldown: 2.1,
            range: 200.0,
            damage: 8.0,
        }),
        beat: 2.0,
        glow: 0.0,
        lava_immune: false,
        blood: [228, 220, 196],
        xp: 10,
        value: 5,
        drops: Some(&[
            MobDrop {
                item: "bone",
                count: [1.0, 3.0],
                chance: 1.0,
            },
            MobDrop {
                item: "arrow",
                count: [1.0, 3.0],
                chance: 0.3,
            },
        ]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [2.0, 4.0],
        weight: 15.0,
        art: Some(MobSpecArt {
            cells_w: 2,
            cells_h: 3,
            pal: &[".", "#6e6a5c", "#b8b098", "#e4dcc4", "#ff5a4a"],
            fps: Some(8.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.9,
                    blink_for: 0.14,
                    frames: &[".3", "22", "11", "", ".3", "21", "11", "", ".4", "22", "11"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        ".3", "22", "1.", "", ".3", "22", "11", "", ".3", "22", ".1", "", ".3",
                        "22", "11",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 10.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".3", "22", ".1", "", ".3", "23", ".."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "glimmerback",
        code: 15,
        brain: MobBrain::Walker,
        name: "Glimmerback",
        max_health: 34.0,
        contact_damage: 12.0,
        attack_cooldown: 1.1,
        armor: 6.0,
        immune: &[MobSpecImmune::Ice, MobSpecImmune::Impact],
        body_cells_w: 3,
        body_cells_h: 2,
        speed: 90.0,
        chase_speed: Some(140.0),
        jump_speed: 0.0,
        gravity_scale: 1.0,
        aggro_px: 120.0,
        aggro_y_px: 50.0,
        flee_px: 0.0,
        ranged: None,
        beat: 2.8,
        glow: 0.4,
        lava_immune: false,
        blood: [180, 138, 255],
        xp: 20,
        value: 14,
        drops: Some(&[
            MobDrop {
                item: "crystal_shard",
                count: [2.0, 4.0],
                chance: 1.0,
            },
            MobDrop {
                item: "gem",
                count: [1.0, 1.0],
                chance: 0.3,
            },
        ]),
        bands: &[MobSpecBands::Cavern, MobSpecBands::Deep],
        min_depth: 120,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 8.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 2,
            pal: &[".", "#2e2450", "#5a4a92", "#a888e8", "#e8d8ff", "#ffffff"],
            fps: Some(5.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.8,
                    blink_for: 0.16,
                    frames: &[".4.", "323", "", ".3.", "323", "", "454", "323"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        ".4.", "123", "", ".4.", "323", "", ".4.", "321", "", ".4.", "323",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".4.", ".3."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "gulper",
        code: 16,
        brain: MobBrain::Flyer,
        name: "Gulper",
        max_health: 22.0,
        contact_damage: 13.0,
        attack_cooldown: 0.8,
        armor: 0.0,
        immune: &[],
        body_cells_w: 4,
        body_cells_h: 2,
        speed: 130.0,
        chase_speed: Some(250.0),
        jump_speed: 0.0,
        gravity_scale: 0.0,
        aggro_px: 175.0,
        aggro_y_px: 110.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.4,
        glow: 0.0,
        lava_immune: false,
        blood: [111, 176, 192],
        xp: 9,
        value: 5,
        drops: Some(&[
            MobDrop {
                item: "worm_hide",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "slime_gel",
                count: [1.0, 1.0],
                chance: 0.35,
            },
        ]),
        bands: &[MobSpecBands::Shallow, MobSpecBands::Cavern],
        min_depth: 20,
        max_depth: 220,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 10.0,
        art: Some(MobSpecArt {
            cells_w: 4,
            cells_h: 2,
            pal: &[".", "#1e4450", "#3f7f8c", "#6fb0c0", "#bfeaf2", "#ff8a6b"],
            fps: Some(9.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.2,
                    blink_for: 0.14,
                    frames: &[".44.", "2332", "", ".34.", "2332", "", ".44.", "2335"],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Loop,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "4...", "2332", "", ".4..", "3223", "", "..4.", "2332", "", "...4", "3223",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[".44.", "2335"],
                },
            ]),
        }),
    },
    MobSpec {
        id: "bladeframe",
        code: 17,
        brain: MobBrain::Walker,
        name: "Bladeframe",
        max_health: 52.0,
        contact_damage: 24.0,
        attack_cooldown: 0.75,
        armor: 7.0,
        immune: &[MobSpecImmune::Ice, MobSpecImmune::Impact],
        body_cells_w: 3,
        body_cells_h: 3,
        speed: 105.0,
        chase_speed: Some(230.0),
        jump_speed: 520.0,
        gravity_scale: 1.0,
        aggro_px: 190.0,
        aggro_y_px: 95.0,
        flee_px: 0.0,
        ranged: None,
        beat: 1.8,
        glow: 0.15,
        lava_immune: false,
        blood: [180, 192, 208],
        xp: 30,
        value: 22,
        drops: Some(&[
            MobDrop {
                item: "machine_scrap",
                count: [1.0, 3.0],
                chance: 1.0,
            },
            MobDrop {
                item: "iron_bar",
                count: [1.0, 1.0],
                chance: 0.4,
            },
            MobDrop {
                item: "gem",
                count: [1.0, 1.0],
                chance: 0.1,
            },
        ]),
        bands: &[MobSpecBands::Deep],
        min_depth: 200,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 1.0],
        weight: 6.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 3,
            pal: &[".", "#24282f", "#4a5260", "#8a94a6", "#d8e0ec", "#ff5a4a"],
            fps: Some(6.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 2.6,
                    blink_for: 0.18,
                    frames: &[
                        "254", "334", "1.1", "", "234", "334", "1.1", "", "254", "344", "1.1",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "254", "334", "1..", "", "254", "334", "1.1", "", "254", "334", "..1", "",
                        "254", "334", "1.1",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 10.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["254", "334", ".1.", "", "244", "444", "..."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "slagworm",
        code: 18,
        brain: MobBrain::Burrower,
        name: "Slagworm",
        max_health: 78.0,
        contact_damage: 30.0,
        attack_cooldown: 1.3,
        armor: 5.0,
        immune: &[MobSpecImmune::Fire],
        body_cells_w: 4,
        body_cells_h: 3,
        speed: 120.0,
        chase_speed: Some(190.0),
        jump_speed: 760.0,
        gravity_scale: 1.0,
        aggro_px: 210.0,
        aggro_y_px: 140.0,
        flee_px: 0.0,
        ranged: None,
        beat: 3.4,
        glow: 0.5,
        lava_immune: true,
        blood: [255, 106, 32],
        xp: 44,
        value: 30,
        drops: Some(&[
            MobDrop {
                item: "ember_core",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "ash_pile",
                count: [2.0, 4.0],
                chance: 1.0,
            },
            MobDrop {
                item: "obsidian_block",
                count: [1.0, 3.0],
                chance: 0.6,
            },
            MobDrop {
                item: "gem",
                count: [1.0, 1.0],
                chance: 0.15,
            },
        ]),
        bands: &[MobSpecBands::Deep],
        min_depth: 200,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: true,
        pack_size: [1.0, 1.0],
        weight: 4.0,
        art: Some(MobSpecArt {
            cells_w: 4,
            cells_h: 3,
            pal: &[".", "#2a120a", "#6b2410", "#d84a14", "#ff9a34", "#ffe27a"],
            fps: Some(6.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 4.6,
                    blink_for: 0.24,
                    frames: &[
                        "2112", "3443", ".22.", "", "2112", "3343", ".22.", "", "2552", "4554",
                        ".22.",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "1221", "3443", "22..", "", "1221", "3443", ".22.", "", "1221", "3443",
                        "..22", "", "1221", "3443", ".22.",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Once,
                    fps: 9.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["1221", "3443", "....", "", "5445", "4554", "...."],
                },
            ]),
        }),
    },
    MobSpec {
        id: "mycelith",
        code: 19,
        brain: MobBrain::Walker,
        name: "Mycelith",
        max_health: 44.0,
        contact_damage: 10.0,
        attack_cooldown: 1.0,
        armor: 3.0,
        immune: &[MobSpecImmune::Poison, MobSpecImmune::Acid],
        body_cells_w: 3,
        body_cells_h: 3,
        speed: 85.0,
        chase_speed: Some(130.0),
        jump_speed: 0.0,
        gravity_scale: 1.0,
        aggro_px: 175.0,
        aggro_y_px: 100.0,
        flee_px: 0.0,
        ranged: Some(MobSpecRanged {
            projectile: MobProjectile::Spore,
            cooldown: 2.8,
            range: 200.0,
            damage: 9.0,
        }),
        beat: 2.6,
        glow: 0.3,
        lava_immune: false,
        blood: [168, 216, 106],
        xp: 24,
        value: 12,
        drops: Some(&[
            MobDrop {
                item: "spore_sac",
                count: [2.0, 4.0],
                chance: 1.0,
            },
            MobDrop {
                item: "mushroom_cap",
                count: [1.0, 2.0],
                chance: 1.0,
            },
            MobDrop {
                item: "mushroom_stem",
                count: [1.0, 1.0],
                chance: 0.5,
            },
        ]),
        bands: &[MobSpecBands::Deep],
        min_depth: 220,
        max_depth: 65535,
        biomes: None,
        nocturnal: false,
        needs_lava: false,
        pack_size: [1.0, 2.0],
        weight: 7.0,
        art: Some(MobSpecArt {
            cells_w: 3,
            cells_h: 3,
            pal: &[".", "#223018", "#46603a", "#8fbe58", "#d8ff9a", "#f4ffd8"],
            fps: Some(5.0),
            variants: Some(1),
            seq: Some(&[
                MobSpecSeq {
                    state: MobSpecSeqState::Idle,
                    mode: MobSpecSeqMode::Ambient,
                    fps: 0.0,
                    blink_every: 3.0,
                    blink_for: 0.2,
                    frames: &[
                        "343", ".2.", "1.1", "", "233", ".2.", "1.1", "", "454", ".3.", "1.1",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Move,
                    mode: MobSpecSeqMode::Phase,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &[
                        "343", ".2.", "1..", "", "343", ".2.", "1.1", "", "343", ".2.", "..1", "",
                        "343", ".2.", "1.1",
                    ],
                },
                MobSpecSeq {
                    state: MobSpecSeqState::Air,
                    mode: MobSpecSeqMode::Hold,
                    fps: 0.0,
                    blink_every: 0.0,
                    blink_for: 0.1,
                    frames: &["343", ".2.", "..."],
                },
            ]),
        }),
    },
];

pub const MOB_COUNT: usize = 20;

/// id -> code. Consts, so `mob::STONE` is a compile-time constant.
pub mod mob {
    pub const GRUBLING: u16 = 0;
    pub const CRITTER: u16 = 1;
    pub const SANDWORM: u16 = 2;
    pub const FROSTMITE: u16 = 3;
    pub const THORNHOPPER: u16 = 4;
    pub const SLIME: u16 = 5;
    pub const BAT: u16 = 6;
    pub const STONEBACK: u16 = 7;
    pub const CINDER_MOTH: u16 = 8;
    pub const BLOAT: u16 = 9;
    pub const DRIFTLING: u16 = 10;
    pub const EMBERLING: u16 = 11;
    pub const SENTINEL: u16 = 12;
    pub const SPORELING: u16 = 13;
    pub const SKELETON: u16 = 14;
    pub const GLIMMERBACK: u16 = 15;
    pub const GULPER: u16 = 16;
    pub const BLADEFRAME: u16 = 17;
    pub const SLAGWORM: u16 = 18;
    pub const MYCELITH: u16 = 19;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

bitflags::bitflags! {
    /// Depth-band bits for MOB_BANDS. Bit order is fixed by
    /// tools/contentc/schema/mob.ts.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct Band: u32 {
        const SURFACE = 1 << 0;
        const SHALLOW = 1 << 1;
        const CAVERN = 1 << 2;
        const DEEP = 1 << 3;
    }
}

bitflags::bitflags! {
    /// Damage-tag bits for MOB_IMMUNE.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct Dmg: u32 {
        const FIRE = 1 << 0;
        const ACID = 1 << 1;
        const ICE = 1 << 2;
        const IMPACT = 1 << 3;
        const POISON = 1 << 4;
    }
}

bitflags::bitflags! {
    /// Flag bits for MOB_FLAGS.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub struct Mobf: u32 {
        const NOCTURNAL = 1 << 0;
        const NEEDS_LAVA = 1 << 1;
        const LAVA_IMMUNE = 1 << 2;
        const RANGED = 1 << 3;
    }
}

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Packed immunity bitmask: `MOB_IMMUNE[c] & DMG.fire`.
pub static MOB_IMMUNE: [u32; 20] = [
    0, 0, 0, 4, 16, 0, 0, 8, 1, 0, 0, 1, 12, 18, 16, 12, 0, 12, 1, 18,
];

/// Packed band bitmask: `MOB_BANDS[c] & BAND.cavern`. The spawn picker tests
/// every def against one band per candidate cell, so this replaces an indexOf
/// over a string array in the inner loop.
pub static MOB_BANDS: [u8; 20] = [
    3, 1, 3, 3, 3, 6, 15, 12, 7, 12, 12, 14, 12, 8, 12, 12, 6, 8, 8, 8,
];

pub static MOB_MINDEPTH: [u16; 20] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 240, 0, 120, 20, 200, 200, 220,
];

pub static MOB_MAXDEPTH: [u16; 20] = [
    65535, 65535, 65535, 40, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535, 65535,
    65535, 65535, 220, 65535, 65535, 65535,
];

/// Relative spawn weight.
pub static MOB_WEIGHT: [f32; 20] = [
    26.0, 22.0, 10.0, 18.0, 14.0, 20.0, 12.0, 9.0, 11.0, 8.0, 12.0, 14.0, 7.0, 13.0, 15.0, 8.0,
    10.0, 6.0, 4.0, 7.0,
];

/// Packed habitat/behaviour flags: `MOB_FLAGS[c] & MOBF.nocturnal`. Reading
/// presence of the `ranged` group off a bit keeps the spawn and combat
/// early-outs to one array read.
pub static MOB_FLAGS: [u8; 20] = [0, 0, 0, 0, 8, 0, 1, 0, 9, 0, 0, 6, 8, 8, 8, 0, 0, 0, 6, 8];

/// Every flat table in this module, by name. For the gates, not the game.
pub static MOB_TABLES: &[(&str, crate::Table)] = &[
    ("MOB_IMMUNE", crate::Table::U32(&MOB_IMMUNE)),
    ("MOB_BANDS", crate::Table::U8(&MOB_BANDS)),
    ("MOB_MINDEPTH", crate::Table::U16(&MOB_MINDEPTH)),
    ("MOB_MAXDEPTH", crate::Table::U16(&MOB_MAXDEPTH)),
    ("MOB_WEIGHT", crate::Table::F32(&MOB_WEIGHT)),
    ("MOB_FLAGS", crate::Table::U8(&MOB_FLAGS)),
];

/// Authoring id -> code, by name. For the gates, not the game.
pub static MOB_CODES: &[(&str, u16)] = &[
    ("grubling", 0),
    ("critter", 1),
    ("sandworm", 2),
    ("frostmite", 3),
    ("thornhopper", 4),
    ("slime", 5),
    ("bat", 6),
    ("stoneback", 7),
    ("cinder_moth", 8),
    ("bloat", 9),
    ("driftling", 10),
    ("emberling", 11),
    ("sentinel", 12),
    ("sporeling", 13),
    ("skeleton", 14),
    ("glimmerback", 15),
    ("gulper", 16),
    ("bladeframe", 17),
    ("slagworm", 18),
    ("mycelith", 19),
];
