// GENERATED by contentc — DO NOT EDIT
// 51 sprites from 2 source file(s):
//   content/sprites/icons.toml
//   content/sprites/player.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which pose this sequence supplies. Closed vocabulary — a typo is a build
/// error. The facade names this union `AnimState`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqState {
    Idle,
    Run,
    Skid,
    Jump,
    DoubleJump,
    Fall,
    Land,
    Dash,
    WallSlide,
    Swim,
    Punch,
    Hurt,
}

/// How the frames are stepped. Names are the contract with the runtime's
/// picker.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqMode {
    Hold,
    Loop,
    Once,
    Phase,
    Ambient,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteSeq {
    /// Which pose this sequence supplies. Closed vocabulary — a typo is a build
    /// error. The facade names this union `AnimState`.
    pub state: SpriteSeqState,
    /// How the frames are stepped. Names are the contract with the runtime's
    /// picker.
    pub mode: SpriteSeqMode,
    /// Playback rate for THIS sequence. 0 inherits the sprite's `fps`, which is
    /// why the default is 0 and not 8 — 0 is 'unset', and an explicit 8 here
    /// would pin the sequence if the sprite were ever retuned.
    pub fps: f32,
    /// `ambient` only: seconds between interrupts. 0 = never interrupt. The
    /// interrupt frame is the sequence's LAST frame, so the ambient cycle itself
    /// is frames[0..n-2].
    pub blink_every: f32,
    /// `ambient` only: seconds the interrupt frame is held.
    pub blink_for: f32,
    /// The frames, as a `'''` body: `cellsH` rows per frame, frames separated by
    /// a blank line. Read it as a filmstrip.
    pub frames: &'static [&'static str],
}

/// The compiled shape of one sprite. Derived from
/// crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteDef {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Display name, for the art debug overlay. Defaults to the id.
    pub name: &'static str,
    /// Art grid width in world cells. One art pixel is one world cell.
    pub cells_w: i32,
    /// Art grid height in world cells. Every frame must have exactly this many
    /// rows.
    pub cells_h: i32,
    /// Palette, "#rrggbb" per index. Index 0 is the transparent slot and is
    /// written "." — it is never painted, so its value is a placeholder, not a
    /// colour. Frame characters are digits indexing this list.
    pub pal: &'static [&'static str],
    /// Sprite-wide playback rate. A sequence with its own non-zero `fps`
    /// overrides it, so this is the value for everything that has no reason to be
    /// special.
    pub fps: f32,
    /// How many tinted copies of the whole sprite to bake. 1 = just the palette
    /// as authored. More than one lets a crowd of the same creature read as
    /// individuals without authoring a second palette, at the cost of one extra
    /// baked canvas set each.
    pub variants: i32,
    /// One animation sequence per entry, in file order. Attributes as keys,
    /// frames in the `frames` body.
    pub seq: Option<&'static [SpriteSeq]>,
}

/// Authoring ids, index == code.
pub static SPRITE_IDS: [&str; 51] = [
    "player",
    "icon_block_cube",
    "icon_pick_traveler",
    "icon_pick_copper",
    "icon_pick_iron",
    "icon_pick_gold",
    "icon_pick_gem",
    "icon_sword_traveler",
    "icon_sword_king",
    "icon_bow",
    "icon_sling",
    "icon_arrow",
    "icon_arrow_iron",
    "icon_ore_copper",
    "icon_ore_iron",
    "icon_ore_gold",
    "icon_coal",
    "icon_bar_copper",
    "icon_bar_iron",
    "icon_bar_gold",
    "icon_gem",
    "icon_crystal_shard",
    "icon_flint",
    "icon_flask_fire",
    "icon_flask_light",
    "icon_flask_haste",
    "icon_bandage",
    "icon_stew",
    "icon_roast",
    "icon_cake",
    "icon_torch",
    "icon_lantern",
    "icon_campfire",
    "icon_ladder",
    "icon_rope",
    "icon_platform",
    "icon_chest",
    "icon_pearl",
    "icon_pearl_shard",
    "icon_bone",
    "icon_scrap",
    "icon_core_ember",
    "icon_core_frozen",
    "icon_gel",
    "icon_chitin",
    "icon_hide",
    "icon_wing",
    "icon_dust",
    "icon_sac",
    "icon_meat",
    "icon_sapling",
];

/// Every def, index == code, tombstones included.
pub static SPRITES: [SpriteDef; 51] = [
    SpriteDef {
        id: "player",
        code: 0,
        name: "Player",
        cells_w: 2,
        cells_h: 3,
        pal: &[
            ".", "#1b1220", "#3ec8b4", "#21877e", "#ffcf5c", "#ff6b57", "#fff3c4",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[
            SpriteSeq {
                state: SpriteSeqState::Idle,
                mode: SpriteSeqMode::Ambient,
                fps: 1.6129032,
                blink_every: 4.6,
                blink_for: 0.1,
                frames: &[".4", "22", "11", "", ".4", "32", "11", "", ".3", "32", "11"],
            },
            SpriteSeq {
                state: SpriteSeqState::Run,
                mode: SpriteSeqMode::Phase,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    ".4", "32", "1.", "", ".4", "22", "11", "", ".4", "32", ".1", "", ".4", "32",
                    "11",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Skid,
                mode: SpriteSeqMode::Loop,
                fps: 10.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[".4", "23", "11", "", ".4", "23", "16"],
            },
            SpriteSeq {
                state: SpriteSeqState::Jump,
                mode: SpriteSeqMode::Once,
                fps: 9.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[".4", "22", ".1", "", ".4", "32", ".."],
            },
            SpriteSeq {
                state: SpriteSeqState::DoubleJump,
                mode: SpriteSeqMode::Once,
                fps: 12.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    ".4", "32", "..", "", "34", "3.", "..", "", "33", ".4", "..", "", ".4", "32",
                    ".1",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Fall,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[".4", "33", "1.", "", ".4", "33", "..", "", ".4", "33", ".1"],
            },
            SpriteSeq {
                state: SpriteSeqState::Land,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &["..", ".4", "32", "", ".4", "33", "11", "", ".4", "32", "11"],
            },
            SpriteSeq {
                state: SpriteSeqState::Dash,
                mode: SpriteSeqMode::Loop,
                fps: 18.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &["64", "32", "..", "", ".4", "62", "6.", "", "64", "62", ".."],
            },
            SpriteSeq {
                state: SpriteSeqState::WallSlide,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[".4", ".2", ".1", "", ".4", ".2", ".."],
            },
            SpriteSeq {
                state: SpriteSeqState::Swim,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "6.", "34", "3.", "", "..", "34", ".3", "", ".6", "34", "33", "", "..", "34",
                    ".3",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Punch,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[".4", "33", "11", "", ".4", "36", "11", "", ".4", "32", "11"],
            },
            SpriteSeq {
                state: SpriteSeqState::Hurt,
                mode: SpriteSeqMode::Hold,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &["5.", "23", "1."],
            },
        ]),
    },
    SpriteDef {
        id: "icon_block_cube",
        code: 1,
        name: "icon_block_cube",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#55555c", "#9a9aa4", "#c8c8d2"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["33", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_pick_traveler",
        code: 2,
        name: "icon_pick_traveler",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#6b4a2c", "#6e6458", "#a89a86"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["232", ".1.", "..1"],
        }]),
    },
    SpriteDef {
        id: "icon_pick_copper",
        code: 3,
        name: "icon_pick_copper",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#6b4a2c", "#a35f36", "#e08a52"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["232", ".1.", "..1"],
        }]),
    },
    SpriteDef {
        id: "icon_pick_iron",
        code: 4,
        name: "icon_pick_iron",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#6b4a2c", "#7e7a78", "#c8c4c0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["232", ".1.", "..1"],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gold",
        code: 5,
        name: "icon_pick_gold",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#6b4a2c", "#b08a2e", "#f0d878"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["232", ".1.", "..1"],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gem",
        code: 6,
        name: "icon_pick_gem",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#4a2c3a", "#8e2f5e", "#e878b4"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["232", ".1.", "..1"],
        }]),
    },
    SpriteDef {
        id: "icon_sword_traveler",
        code: 7,
        name: "icon_sword_traveler",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#5a4630", "#c2c6ce", "#8a8e96"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["..2", ".2.", "31."],
        }]),
    },
    SpriteDef {
        id: "icon_sword_king",
        code: 8,
        name: "icon_sword_king",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#4a3a1e", "#f2dc94", "#fff6cc", "#e0508c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["..3", ".2.", "41."],
        }]),
    },
    SpriteDef {
        id: "icon_bow",
        code: 9,
        name: "icon_bow",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#d8c898", "#8a5c2e"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".21", "2.1", ".21"],
        }]),
    },
    SpriteDef {
        id: "icon_sling",
        code: 10,
        name: "icon_sling",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#b8a884", "#7c7a78"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["1.1", ".1.", ".2."],
        }]),
    },
    SpriteDef {
        id: "icon_arrow",
        code: 11,
        name: "icon_arrow",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#d8cfae", "#a0783f", "#6e6c74"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["..3", ".2.", "1.."],
        }]),
    },
    SpriteDef {
        id: "icon_arrow_iron",
        code: 12,
        name: "icon_arrow_iron",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#d8cfae", "#a0783f", "#c8ccd4"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["..3", ".2.", "1.."],
        }]),
    },
    SpriteDef {
        id: "icon_ore_copper",
        code: 13,
        name: "icon_ore_copper",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e6a64", "#a35f36", "#e08a52"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["13", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_ore_iron",
        code: 14,
        name: "icon_ore_iron",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e6a64", "#8e8a86", "#cfcbc6"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["13", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_ore_gold",
        code: 15,
        name: "icon_ore_gold",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e6a64", "#b08a2e", "#f0d878"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["13", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_coal",
        code: 16,
        name: "icon_coal",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#1e1c20", "#3a3640", "#5a5464"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["23", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_bar_copper",
        code: 17,
        name: "icon_bar_copper",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#a35f36", "#e08a52"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_bar_iron",
        code: 18,
        name: "icon_bar_iron",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#8e8a86", "#cfcbc6"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_bar_gold",
        code: 19,
        name: "icon_bar_gold",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#b08a2e", "#f0d878"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_gem",
        code: 20,
        name: "icon_gem",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e1e46", "#b8407e", "#f0a0d0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".3", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_crystal_shard",
        code: 21,
        name: "icon_crystal_shard",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#4a3a7a", "#8e6ce0", "#cfb4ff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".3", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_flint",
        code: 22,
        name: "icon_flint",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#3e3c42", "#6e6c74", "#a8a6b0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "31"],
        }]),
    },
    SpriteDef {
        id: "icon_flask_fire",
        code: 23,
        name: "icon_flask_fire",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#e8763a", "#ffc06a"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_flask_light",
        code: 24,
        name: "icon_flask_light",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#b48ad8", "#f0d8ff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_flask_haste",
        code: 25,
        name: "icon_flask_haste",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#8a72b8", "#cfc0f0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_bandage",
        code: 26,
        name: "icon_bandage",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#d8d2c0", "#a89878"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["21", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_stew",
        code: 27,
        name: "icon_stew",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6a5240", "#b06a3c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_roast",
        code: 28,
        name: "icon_roast",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#7a4a2a", "#c88a52"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", ".1"],
        }]),
    },
    SpriteDef {
        id: "icon_cake",
        code: 29,
        name: "icon_cake",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#8a6aa8", "#d8b8f0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_torch",
        code: 30,
        name: "icon_torch",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#7a5230", "#ffc25a"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", ".1"],
        }]),
    },
    SpriteDef {
        id: "icon_lantern",
        code: 31,
        name: "icon_lantern",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#c8a03c", "#ffe8a0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["11", "22"],
        }]),
    },
    SpriteDef {
        id: "icon_campfire",
        code: 32,
        name: "icon_campfire",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#7a4a2a", "#ff9a3c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_ladder",
        code: 33,
        name: "icon_ladder",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#8a6234", "#c8a068"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["1.1", "222", "1.1"],
        }]),
    },
    SpriteDef {
        id: "icon_rope",
        code: 34,
        name: "icon_rope",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#a08858", "#d8c098"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2.", "1.1", ".2."],
        }]),
    },
    SpriteDef {
        id: "icon_platform",
        code: 35,
        name: "icon_platform",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#8a6234", "#c09050"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["222", "1.1", "..."],
        }]),
    },
    SpriteDef {
        id: "icon_chest",
        code: 36,
        name: "icon_chest",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#7a5228", "#a06e38", "#e8c85a"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["222", "313", "111"],
        }]),
    },
    SpriteDef {
        id: "icon_pearl",
        code: 37,
        name: "icon_pearl",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#c8c2d8", "#eae6f4", "#ffffff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["32", "21"],
        }]),
    },
    SpriteDef {
        id: "icon_pearl_shard",
        code: 38,
        name: "icon_pearl_shard",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#c8c2d8", "#eae6f4", "#ffffff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".3", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_bone",
        code: 39,
        name: "icon_bone",
        cells_w: 3,
        cells_h: 3,
        pal: &[".", "#e4dcc4"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["11.", ".1.", ".11"],
        }]),
    },
    SpriteDef {
        id: "icon_scrap",
        code: 40,
        name: "icon_scrap",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e7686", "#b0b8c8"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["21", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_core_ember",
        code: 41,
        name: "icon_core_ember",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#8a3010", "#e86a20", "#ffc060"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["23", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_core_frozen",
        code: 42,
        name: "icon_core_frozen",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#3a6a90", "#6ab0e0", "#d8f4ff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["23", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_gel",
        code: 43,
        name: "icon_gel",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#4e9a62", "#8ee0a0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_chitin",
        code: 44,
        name: "icon_chitin",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e5a3c", "#a8895c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_hide",
        code: 45,
        name: "icon_hide",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6e523a", "#a07a52"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", "1."],
        }]),
    },
    SpriteDef {
        id: "icon_wing",
        code: 46,
        name: "icon_wing",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#5a4a5e", "#9a86a2"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["2.", "12"],
        }]),
    },
    SpriteDef {
        id: "icon_dust",
        code: 47,
        name: "icon_dust",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#b8a878", "#f0e2b0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["2.", ".1"],
        }]),
    },
    SpriteDef {
        id: "icon_sac",
        code: 48,
        name: "icon_sac",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6a4a86", "#b088d0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_meat",
        code: 49,
        name: "icon_meat",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#a86868", "#d89a94"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &["22", "11"],
        }]),
    },
    SpriteDef {
        id: "icon_sapling",
        code: 50,
        name: "icon_sapling",
        cells_w: 2,
        cells_h: 2,
        pal: &[".", "#6a4a2c", "#7ac04e"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[".2", "1."],
        }]),
    },
];

pub const SPRITE_COUNT: usize = 51;

/// id -> code. Consts, so `sprite::STONE` is a compile-time constant.
pub mod sprite {
    pub const PLAYER: u16 = 0;
    pub const ICON_BLOCK_CUBE: u16 = 1;
    pub const ICON_PICK_TRAVELER: u16 = 2;
    pub const ICON_PICK_COPPER: u16 = 3;
    pub const ICON_PICK_IRON: u16 = 4;
    pub const ICON_PICK_GOLD: u16 = 5;
    pub const ICON_PICK_GEM: u16 = 6;
    pub const ICON_SWORD_TRAVELER: u16 = 7;
    pub const ICON_SWORD_KING: u16 = 8;
    pub const ICON_BOW: u16 = 9;
    pub const ICON_SLING: u16 = 10;
    pub const ICON_ARROW: u16 = 11;
    pub const ICON_ARROW_IRON: u16 = 12;
    pub const ICON_ORE_COPPER: u16 = 13;
    pub const ICON_ORE_IRON: u16 = 14;
    pub const ICON_ORE_GOLD: u16 = 15;
    pub const ICON_COAL: u16 = 16;
    pub const ICON_BAR_COPPER: u16 = 17;
    pub const ICON_BAR_IRON: u16 = 18;
    pub const ICON_BAR_GOLD: u16 = 19;
    pub const ICON_GEM: u16 = 20;
    pub const ICON_CRYSTAL_SHARD: u16 = 21;
    pub const ICON_FLINT: u16 = 22;
    pub const ICON_FLASK_FIRE: u16 = 23;
    pub const ICON_FLASK_LIGHT: u16 = 24;
    pub const ICON_FLASK_HASTE: u16 = 25;
    pub const ICON_BANDAGE: u16 = 26;
    pub const ICON_STEW: u16 = 27;
    pub const ICON_ROAST: u16 = 28;
    pub const ICON_CAKE: u16 = 29;
    pub const ICON_TORCH: u16 = 30;
    pub const ICON_LANTERN: u16 = 31;
    pub const ICON_CAMPFIRE: u16 = 32;
    pub const ICON_LADDER: u16 = 33;
    pub const ICON_ROPE: u16 = 34;
    pub const ICON_PLATFORM: u16 = 35;
    pub const ICON_CHEST: u16 = 36;
    pub const ICON_PEARL: u16 = 37;
    pub const ICON_PEARL_SHARD: u16 = 38;
    pub const ICON_BONE: u16 = 39;
    pub const ICON_SCRAP: u16 = 40;
    pub const ICON_CORE_EMBER: u16 = 41;
    pub const ICON_CORE_FROZEN: u16 = 42;
    pub const ICON_GEL: u16 = 43;
    pub const ICON_CHITIN: u16 = 44;
    pub const ICON_HIDE: u16 = 45;
    pub const ICON_WING: u16 = 46;
    pub const ICON_DUST: u16 = 47;
    pub const ICON_SAC: u16 = 48;
    pub const ICON_MEAT: u16 = 49;
    pub const ICON_SAPLING: u16 = 50;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Every flat table in this module, by name. For the gates, not the game.
pub static SPRITE_TABLES: &[(&str, crate::Table)] = &[];

/// Authoring id -> code, by name. For the gates, not the game.
pub static SPRITE_CODES: &[(&str, u16)] = &[
    ("player", 0),
    ("icon_block_cube", 1),
    ("icon_pick_traveler", 2),
    ("icon_pick_copper", 3),
    ("icon_pick_iron", 4),
    ("icon_pick_gold", 5),
    ("icon_pick_gem", 6),
    ("icon_sword_traveler", 7),
    ("icon_sword_king", 8),
    ("icon_bow", 9),
    ("icon_sling", 10),
    ("icon_arrow", 11),
    ("icon_arrow_iron", 12),
    ("icon_ore_copper", 13),
    ("icon_ore_iron", 14),
    ("icon_ore_gold", 15),
    ("icon_coal", 16),
    ("icon_bar_copper", 17),
    ("icon_bar_iron", 18),
    ("icon_bar_gold", 19),
    ("icon_gem", 20),
    ("icon_crystal_shard", 21),
    ("icon_flint", 22),
    ("icon_flask_fire", 23),
    ("icon_flask_light", 24),
    ("icon_flask_haste", 25),
    ("icon_bandage", 26),
    ("icon_stew", 27),
    ("icon_roast", 28),
    ("icon_cake", 29),
    ("icon_torch", 30),
    ("icon_lantern", 31),
    ("icon_campfire", 32),
    ("icon_ladder", 33),
    ("icon_rope", 34),
    ("icon_platform", 35),
    ("icon_chest", 36),
    ("icon_pearl", 37),
    ("icon_pearl_shard", 38),
    ("icon_bone", 39),
    ("icon_scrap", 40),
    ("icon_core_ember", 41),
    ("icon_core_frozen", 42),
    ("icon_gel", 43),
    ("icon_chitin", 44),
    ("icon_hide", 45),
    ("icon_wing", 46),
    ("icon_dust", 47),
    ("icon_sac", 48),
    ("icon_meat", 49),
    ("icon_sapling", 50),
];
