// GENERATED by contentc — DO NOT EDIT
// 56 sprites from 2 source file(s):
//   content/sprites/icons.toml
//   content/sprites/player.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which pose this sequence supplies. Closed vocabulary — a typo is a build
/// error. The facade names this union `AnimState`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqState {
    Idle,
    Run,
    Skid,
    Jump,
    DoubleJump,
    Fall,
    Land,
    Dash,
    WallSlide,
    Swim,
    Punch,
    Hurt,
}

/// How the frames are stepped. Names are the contract with the runtime's
/// picker.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqMode {
    Hold,
    Loop,
    Once,
    Phase,
    Ambient,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteSeq {
    /// Which pose this sequence supplies. Closed vocabulary — a typo is a build
    /// error. The facade names this union `AnimState`.
    pub state: SpriteSeqState,
    /// How the frames are stepped. Names are the contract with the runtime's
    /// picker.
    pub mode: SpriteSeqMode,
    /// Playback rate for THIS sequence. 0 inherits the sprite's `fps`, which is
    /// why the default is 0 and not 8 — 0 is 'unset', and an explicit 8 here
    /// would pin the sequence if the sprite were ever retuned.
    pub fps: f32,
    /// `ambient` only: seconds between interrupts. 0 = never interrupt. The
    /// interrupt frame is the sequence's LAST frame, so the ambient cycle itself
    /// is frames[0..n-2].
    pub blink_every: f32,
    /// `ambient` only: seconds the interrupt frame is held.
    pub blink_for: f32,
    /// The frames, as a `'''` body: `cellsH` rows per frame, frames separated by
    /// a blank line. Read it as a filmstrip.
    pub frames: &'static [&'static str],
}

/// The compiled shape of one sprite. Derived from
/// crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteDef {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Display name, for the art debug overlay. Defaults to the id.
    pub name: &'static str,
    /// Art grid width in world cells. One art pixel is one world cell.
    pub cells_w: i32,
    /// Art grid height in world cells. Every frame must have exactly this many
    /// rows.
    pub cells_h: i32,
    /// Palette, "#rrggbb" per index. Index 0 is the transparent slot and is
    /// written "." — it is never painted, so its value is a placeholder, not a
    /// colour. Frame characters are digits indexing this list.
    pub pal: &'static [&'static str],
    /// Sprite-wide playback rate. A sequence with its own non-zero `fps`
    /// overrides it, so this is the value for everything that has no reason to be
    /// special.
    pub fps: f32,
    /// How many tinted copies of the whole sprite to bake. 1 = just the palette
    /// as authored. More than one lets a crowd of the same creature read as
    /// individuals without authoring a second palette, at the cost of one extra
    /// baked canvas set each.
    pub variants: i32,
    /// One animation sequence per entry, in file order. Attributes as keys,
    /// frames in the `frames` body.
    pub seq: Option<&'static [SpriteSeq]>,
}

/// Authoring ids, index == code.
pub static SPRITE_IDS: [&str; 56] = [
    "player",
    "icon_block_cube",
    "icon_pick_traveler",
    "icon_pick_copper",
    "icon_pick_iron",
    "icon_pick_gold",
    "icon_pick_gem",
    "icon_sword_traveler",
    "icon_sword_king",
    "icon_bow",
    "icon_sling",
    "icon_arrow",
    "icon_arrow_iron",
    "icon_ore_copper",
    "icon_ore_iron",
    "icon_ore_gold",
    "icon_coal",
    "icon_bar_copper",
    "icon_bar_iron",
    "icon_bar_gold",
    "icon_gem",
    "icon_crystal_shard",
    "icon_flint",
    "icon_flask_fire",
    "icon_flask_light",
    "icon_flask_haste",
    "icon_bandage",
    "icon_stew",
    "icon_roast",
    "icon_cake",
    "icon_torch",
    "icon_lantern",
    "icon_campfire",
    "icon_ladder",
    "icon_rope",
    "icon_platform",
    "icon_chest",
    "icon_pearl",
    "icon_pearl_shard",
    "icon_bone",
    "icon_scrap",
    "icon_core_ember",
    "icon_core_frozen",
    "icon_gel",
    "icon_chitin",
    "icon_hide",
    "icon_wing",
    "icon_dust",
    "icon_sac",
    "icon_meat",
    "icon_sapling",
    "icon_anvil",
    "icon_furnace",
    "icon_workbench",
    "icon_chitin_plate",
    "icon_hide_jerkin",
];

/// Every def, index == code, tombstones included.
pub static SPRITES: [SpriteDef; 56] = [
    SpriteDef {
        id: "player",
        code: 0,
        name: "Player",
        cells_w: 4,
        cells_h: 5,
        pal: &[
            ".", "#1b1220", "#3ec8b4", "#21877e", "#ffcf5c", "#ff6b57", "#fff3c4", "#14564f",
            "#e8913a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[
            SpriteSeq {
                state: SpriteSeqState::Idle,
                mode: SpriteSeqMode::Ambient,
                fps: 1.6129032,
                blink_every: 4.6,
                blink_for: 0.1,
                frames: &[
                    "....", ".8..", ".44.", "732.", ".11.", "", "....", "88..", ".44.", "722.",
                    ".11.", "", "....", ".3..", ".33.", "732.", ".11.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Run,
                mode: SpriteSeqMode::Phase,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", ".8..", ".44.", "732.", ".1.1", "", "....", "88..", ".44.", ".22.",
                    "..1.", "", "....", ".8..", ".44.", ".322", "1.7.", "", "....", ".8..", ".44.",
                    "732.", ".11.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Skid,
                mode: SpriteSeqMode::Loop,
                fps: 10.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", "..88", ".44.", "723.", ".11.", "", "....", "..88", ".44.", "723.",
                    ".116",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Jump,
                mode: SpriteSeqMode::Once,
                fps: 9.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "...2", ".8.2", ".442", ".22.", "..1.", "", "....", ".88.", ".44.", ".32.",
                    "..1.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::DoubleJump,
                mode: SpriteSeqMode::Once,
                fps: 12.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", ".84.", ".22.", ".33.", "..6.", "", "....", "....", ".228", ".334",
                    "....", "", "....", "....", ".22.", ".338", "..4.", "", "....", ".8..", ".44.",
                    ".322", "1.7.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Fall,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", ".88.", ".44.", "733.", "..1.", "", "....", ".88.", "7442", ".33.",
                    "....", "", "....", ".88.", ".44.", ".332", "1...",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Land,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", "....", ".88.", "7442", "6116", "", "....", ".8..", ".44.", "733.",
                    ".11.", "", "....", ".8..", ".44.", "732.", ".11.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Dash,
                mode: SpriteSeqMode::Loop,
                fps: 18.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", "6...", "844.", ".22.", "..1.", "", "....", "....", "844.", "622.",
                    "..1.", "", "....", "6...", "844.", "622.", "..1.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::WallSlide,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", ".8..", "..4.", ".72.", "..1.", "", "....", "88..", "..4.", ".72.",
                    "....",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Swim,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", "..6.", "8344", "77..", "....", "", "....", "....", "8344", ".72.",
                    "....", "", "....", "...6", "8344", "772.", "....", "", "....", "....", "8344",
                    ".72.", "....",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Punch,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "....", ".8..", ".44.", "233.", ".11.", "", "....", "8...", ".446", ".326",
                    ".11.", "", "....", ".8..", ".44.", "732.", ".11.",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Hurt,
                mode: SpriteSeqMode::Hold,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &["5...", "55..", ".55.", "723.", ".1.."],
            },
        ]),
    },
    SpriteDef {
        id: "icon_block_cube",
        code: 1,
        name: "icon_block_cube",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#5c5c66", "#8a8a95", "#b4b4c0", "#dcdce6"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "13332221", "13332221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_traveler",
        code: 2,
        name: "icon_pick_traveler",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#4e463c", "#6e6458", "#a89a86", "#3e2c1a",
            "#c4b8a4",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_copper",
        code: 3,
        name: "icon_pick_copper",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#7a4324", "#a35f36", "#e08a52", "#3e2c1a",
            "#ffc48a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_iron",
        code: 4,
        name: "icon_pick_iron",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#5c5856", "#7e7a78", "#c8c4c0", "#3e2c1a",
            "#eceaea",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gold",
        code: 5,
        name: "icon_pick_gold",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#7e5f18", "#b08a2e", "#f0d878", "#3e2c1a",
            "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gem",
        code: 6,
        name: "icon_pick_gem",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#38202c", "#5c3a4a", "#6e2048", "#8e2f5e", "#e878b4", "#2a1620",
            "#ffd8f0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sword_traveler",
        code: 7,
        name: "icon_sword_traveler",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a2a1a", "#5a4630", "#8a8e96", "#c2c6ce", "#7d6a48", "#f2f6ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....1741", "...1541.", "..1541..", ".1541...", "166661..", ".1321...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sword_king",
        code: 8,
        name: "icon_sword_king",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a2c12", "#5c4820", "#c8a63e", "#f2dc94", "#9a7420", "#fff6cc",
            "#e0508c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....1741", "...1541.", "..1541..", ".1541...", "1686617.", ".1321777",
                ".1661.7.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bow",
        code: 9,
        name: "icon_bow",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#6b4420", "#a5713a", "#d8c898"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...1321.", "..13241.", ".132.41.", "132..41.", "132..41.", ".132.41.", "..13241.",
                "...1321.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sling",
        code: 10,
        name: "icon_sling",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#cdbb95", "#7a6c50", "#b8a884", "#9a9894"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "121..121", ".121121.", "..1221..", ".144331.", ".145531.", ".143331.", "..1331..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_arrow",
        code: 11,
        name: "icon_arrow",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#7a5a2e", "#a0783f", "#9a98a2", "#6e6c74", "#b8b096", "#d8cfae",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "......41", ".....451", "....1451", "...1321.", "..1321..", ".1321...", "17661...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_arrow_iron",
        code: 12,
        name: "icon_arrow_iron",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#7a5a2e", "#a0783f", "#dfe3eb", "#9aa0a8", "#b8b096", "#d8cfae",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "......41", ".....451", "....1451", "...1321.", "..1321..", ".1321...", "17661...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_copper",
        code: 13,
        name: "icon_ore_copper",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#7a4526", "#c2703f", "#f09a5e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14433651", "14763221", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_iron",
        code: 14,
        name: "icon_ore_iron",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#6e7682", "#aab2be", "#eaf0f6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14433651", "14763221", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_gold",
        code: 15,
        name: "icon_ore_gold",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#8a6a20", "#c8a038", "#f0d878",
            "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14437871", "14763721", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_coal",
        code: 16,
        name: "icon_coal",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#26232c", "#3d3848", "#565064", "#7a7290"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11111.", ".1454321", "14543321", "14433221", "13332221", "13222221", ".1222221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_copper",
        code: 17,
        name: "icon_bar_copper",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6b3c1f", "#a35f36", "#c2703f", "#e08a52", "#f7b478",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".165551.", "14444441", "14322331", "13322331", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_iron",
        code: 18,
        name: "icon_bar_iron",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#4e535c", "#7c828c", "#a6acb6", "#ced4de", "#f0f4fa",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".165551.", "14444441", "14322331", "13322331", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_gold",
        code: 19,
        name: "icon_bar_gold",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6e5218", "#b08a2e", "#d0a838", "#f0d878", "#ffeaa0", "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".155551.", "14644441", "16764331", "13633221", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_gem",
        code: 20,
        name: "icon_gem",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#52123a", "#6e1e46", "#b8407e", "#e878b4", "#f0a0d0", "#ffe6f6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".165441.", "16764331", ".164331.", "..1431..", "..1321..", "...121..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_crystal_shard",
        code: 21,
        name: "icon_crystal_shard",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#322558", "#4a3a7a", "#6e52b0", "#8e6ce0", "#cfb4ff", "#f4ecff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....151.", "...1651.", "..16761.", "..13641.", ".134431.", ".133221.",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flint",
        code: 22,
        name: "icon_flint",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#2e2c34", "#4e4c56", "#7a7884", "#b0aeba"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154431.", "15444331", "14443321", "14433221", "1433221.", ".13221..",
                "..111...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_fire",
        code: 23,
        name: "icon_flask_fire",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#43384a", "#877a90", "#a83a14", "#e8763a", "#ffc06a", "#ffe8b0",
            "#7a5230",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", ".132221.", "13227221", "16665551", "15444441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_light",
        code: 24,
        name: "icon_flask_light",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#4a3f5c", "#8f82a8", "#7a52a8", "#b48ad8", "#f0d8ff", "#fcf2ff",
            "#7a5230", "#3a2a52",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", "91322219", "13227221", "16665551", "15444441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_haste",
        code: 25,
        name: "icon_flask_haste",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3f3a52", "#7e7898", "#5e4a92", "#8a72b8", "#cfc0f0", "#efe6ff",
            "#7a5230",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", ".132221.", "13276661", "16655551", "15544441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bandage",
        code: 26,
        name: "icon_bandage",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#8a7a5c", "#a89878", "#d8d2c0", "#efe9dc"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154421.", "15442331", "14423331", ".142331.", "..11431.", "...14331",
                "...11111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_stew",
        code: 27,
        name: "icon_stew",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#4a3a2c", "#6a5240", "#8a6a50", "#8a4e2a", "#b06a3c", "#d8935c",
            "#e8b878",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1771..", ".176651.", "17686551", "14444431", "14333321", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_roast",
        code: 28,
        name: "icon_roast",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#5c3620", "#9a5e34", "#c88a52", "#e6a86c", "#e4dcc4", "#b0a68c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...1111.", "..154441", ".1544331", ".1443321", ".1433221", ".1672221", "1671111.",
                "1661....",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_cake",
        code: 29,
        name: "icon_cake",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#5e4478", "#8a6aa8", "#a888c0", "#d8b8f0", "#f2e2ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", ".111111.", "16555551", "15544441", "14433331", "13332221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_torch",
        code: 30,
        name: "icon_torch",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#5a3a20", "#7a5230", "#c85a1c", "#ff9a3a", "#ffd67e", "#a3521a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", "7156517.", ".14541..", ".13321..", "..1321..", "..1321..",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_lantern",
        code: 31,
        name: "icon_lantern",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6e5418", "#c8a03c", "#e8a82e", "#ffdc88", "#fff8d8", "#8a6418",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".712217.", ".133221.", "12655521", "12654421", "12554421", "12544421", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_campfire",
        code: 32,
        name: "icon_campfire",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#4e3018", "#7a4a2a", "#c04a12", "#ff9a3c", "#ffd070", "#8f3f0e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", ".156651.", ".145541.", "71455417", ".144441.", "13211321",
                "12211221",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ladder",
        code: 33,
        name: "icon_ladder",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#8a6234", "#c8a068"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "11....11", "132..321", "13233321", "132..321", "13233321", "132..321", "13233321",
                "11....11",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_rope",
        code: 34,
        name: "icon_rope",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#7d6640", "#a08858", "#d8c098"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".144331.", "143..321", "143..321", "133..221", ".133221.", "..1111..",
                "...1321.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_platform",
        code: 35,
        name: "icon_platform",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#6a4a24", "#8a6234", "#c09050"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14444441", "13333331", "12222221", ".13..31.", ".13..31.", ".13..31.",
                ".11..11.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chest",
        code: 36,
        name: "icon_chest",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#4e3316", "#7a5228", "#a06e38", "#b8901f", "#e8c85a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14455441", "13355331", "11156111", "13355331", "12255221", "12255221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pearl",
        code: 37,
        name: "icon_pearl",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6e6a84", "#9a94b0", "#c8c2d8", "#eae6f4", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".165431.", "16664331", "15644321", "14443521", "14333221", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pearl_shard",
        code: 38,
        name: "icon_pearl_shard",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6e6a84", "#9a94b0", "#c8c2d8", "#eae6f4", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", "...111..", "..15441.", ".156541.", ".145431.", "..1431..", "...121..",
                "...111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bone",
        code: 39,
        name: "icon_bone",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#b0a68c", "#e4dcc4", "#f6f0dc"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111....", "14431...", "143331..", ".11331..", "...1331.", "...13321", "...13221",
                "....111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_scrap",
        code: 40,
        name: "icon_scrap",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#454c5a", "#6e7686", "#b0b8c8", "#e2e8f2"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".11.11..", "1541441.", "14444331", "14333321", ".1332221", "..132221", "...12221",
                "....1111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_core_ember",
        code: 41,
        name: "icon_core_ember",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#5c1c08", "#8a3010", "#e86a20", "#ffc060", "#fff0c0", "#4a1c0c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", "71443317", "14554331", "14565431", "13455431", "13344321", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_core_frozen",
        code: 42,
        name: "icon_core_frozen",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#1e4058", "#3a6a90", "#6ab0e0", "#a8dcf6", "#eafaff", "#142c44",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1441..", "71455417", "14566541", "13455431", ".134431.", "..1321..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_gel",
        code: 43,
        name: "icon_gel",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#2e6640", "#4e9a62", "#8ee0a0", "#c8f6d4"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1441..", ".155441.", "14544331", "14433321", "14333221", "13322221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chitin",
        code: 44,
        name: "icon_chitin",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#4a3c26", "#6e5a3c", "#a8895c", "#d0ae78"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".155441.", "15554331", "14454321", "14353221", "13353221", ".135321.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_hide",
        code: 45,
        name: "icon_hide",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#4a3626", "#6e523a", "#a07a52", "#c49a6c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".1....1.", "151..151", "15444451", "15444331", "14433321", "14332221", "131..121",
                ".1....1.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_wing",
        code: 46,
        name: "icon_wing",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#3a2e3e", "#5a4a5e", "#9a86a2", "#c2b0c8"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "1111....", "154411..", "1542431.", "14423331", "14323231", ".1323231", "..123231",
                "..11.11.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_dust",
        code: 47,
        name: "icon_dust",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#8a7a4e", "#b8a878", "#f0e2b0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...41...", ".41.....", ".....41.", "...11...", "..1431..", ".144331.", "14333221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sac",
        code: 48,
        name: "icon_sac",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#45285e", "#6a4a86", "#b088d0", "#e8d4ff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1431..", ".144331.", "14453331", "14353521", "13332521", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_meat",
        code: 49,
        name: "icon_meat",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#6e3a3e", "#a86868", "#d89a94", "#eec4bc", "#f2ddc8",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11111.", ".1554431", "15464331", "14463321", "14336321", "13332221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sapling",
        code: 50,
        name: "icon_sapling",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3a2a18", "#6a4a2c", "#4e8a34", "#7ac04e", "#a8e070", "#8a6a44",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".11..11.", "16511541", ".1513141", "..11311.", "...131..", "..17731.", ".1733221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_anvil",
        code: 51,
        name: "icon_anvil",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#33353a", "#4c4e54", "#72767e", "#b4b8c0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "14444441", "13333331", "..1331..", "..1221..", ".133331.",
                "12222221",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_furnace",
        code: 52,
        name: "icon_furnace",
        cells_w: 8,
        cells_h: 8,
        pal: &[
            ".", "#16121e", "#3e3c3a", "#5a5856", "#7a7674", "#c8601c", "#ffb04a", "#7e3a10",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1441..", "..1331..", "14444441", "13111131", "13566531", "13566531", "13555531",
                "72222227",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_workbench",
        code: 53,
        name: "icon_workbench",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#6a4a26", "#9a703e", "#c49a5c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14444441", "13333331", ".122221.", ".131131.", ".131131.", ".133331.",
                ".121121.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chitin_plate",
        code: 54,
        name: "icon_chitin_plate",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#4a3c24", "#6a5838", "#8a7450", "#c0a870"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "11111111", "14411441", "14355321", "13355321", "11355311", "13355221", ".135521.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_hide_jerkin",
        code: 55,
        name: "icon_hide_jerkin",
        cells_w: 8,
        cells_h: 8,
        pal: &[".", "#16121e", "#4e3620", "#6a4c30", "#8c6a44", "#c2a074"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".14..41.", "14411441", "13455321", "13355321", "13255221", ".132221.", ".122221.",
                "..1111..",
            ],
        }]),
    },
];

pub const SPRITE_COUNT: usize = 56;

/// id -> code. Consts, so `sprite::STONE` is a compile-time constant.
pub mod sprite {
    pub const PLAYER: u16 = 0;
    pub const ICON_BLOCK_CUBE: u16 = 1;
    pub const ICON_PICK_TRAVELER: u16 = 2;
    pub const ICON_PICK_COPPER: u16 = 3;
    pub const ICON_PICK_IRON: u16 = 4;
    pub const ICON_PICK_GOLD: u16 = 5;
    pub const ICON_PICK_GEM: u16 = 6;
    pub const ICON_SWORD_TRAVELER: u16 = 7;
    pub const ICON_SWORD_KING: u16 = 8;
    pub const ICON_BOW: u16 = 9;
    pub const ICON_SLING: u16 = 10;
    pub const ICON_ARROW: u16 = 11;
    pub const ICON_ARROW_IRON: u16 = 12;
    pub const ICON_ORE_COPPER: u16 = 13;
    pub const ICON_ORE_IRON: u16 = 14;
    pub const ICON_ORE_GOLD: u16 = 15;
    pub const ICON_COAL: u16 = 16;
    pub const ICON_BAR_COPPER: u16 = 17;
    pub const ICON_BAR_IRON: u16 = 18;
    pub const ICON_BAR_GOLD: u16 = 19;
    pub const ICON_GEM: u16 = 20;
    pub const ICON_CRYSTAL_SHARD: u16 = 21;
    pub const ICON_FLINT: u16 = 22;
    pub const ICON_FLASK_FIRE: u16 = 23;
    pub const ICON_FLASK_LIGHT: u16 = 24;
    pub const ICON_FLASK_HASTE: u16 = 25;
    pub const ICON_BANDAGE: u16 = 26;
    pub const ICON_STEW: u16 = 27;
    pub const ICON_ROAST: u16 = 28;
    pub const ICON_CAKE: u16 = 29;
    pub const ICON_TORCH: u16 = 30;
    pub const ICON_LANTERN: u16 = 31;
    pub const ICON_CAMPFIRE: u16 = 32;
    pub const ICON_LADDER: u16 = 33;
    pub const ICON_ROPE: u16 = 34;
    pub const ICON_PLATFORM: u16 = 35;
    pub const ICON_CHEST: u16 = 36;
    pub const ICON_PEARL: u16 = 37;
    pub const ICON_PEARL_SHARD: u16 = 38;
    pub const ICON_BONE: u16 = 39;
    pub const ICON_SCRAP: u16 = 40;
    pub const ICON_CORE_EMBER: u16 = 41;
    pub const ICON_CORE_FROZEN: u16 = 42;
    pub const ICON_GEL: u16 = 43;
    pub const ICON_CHITIN: u16 = 44;
    pub const ICON_HIDE: u16 = 45;
    pub const ICON_WING: u16 = 46;
    pub const ICON_DUST: u16 = 47;
    pub const ICON_SAC: u16 = 48;
    pub const ICON_MEAT: u16 = 49;
    pub const ICON_SAPLING: u16 = 50;
    pub const ICON_ANVIL: u16 = 51;
    pub const ICON_FURNACE: u16 = 52;
    pub const ICON_WORKBENCH: u16 = 53;
    pub const ICON_CHITIN_PLATE: u16 = 54;
    pub const ICON_HIDE_JERKIN: u16 = 55;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Every flat table in this module, by name. For the gates, not the game.
pub static SPRITE_TABLES: &[(&str, crate::Table)] = &[];

/// Authoring id -> code, by name. For the gates, not the game.
pub static SPRITE_CODES: &[(&str, u16)] = &[
    ("player", 0),
    ("icon_block_cube", 1),
    ("icon_pick_traveler", 2),
    ("icon_pick_copper", 3),
    ("icon_pick_iron", 4),
    ("icon_pick_gold", 5),
    ("icon_pick_gem", 6),
    ("icon_sword_traveler", 7),
    ("icon_sword_king", 8),
    ("icon_bow", 9),
    ("icon_sling", 10),
    ("icon_arrow", 11),
    ("icon_arrow_iron", 12),
    ("icon_ore_copper", 13),
    ("icon_ore_iron", 14),
    ("icon_ore_gold", 15),
    ("icon_coal", 16),
    ("icon_bar_copper", 17),
    ("icon_bar_iron", 18),
    ("icon_bar_gold", 19),
    ("icon_gem", 20),
    ("icon_crystal_shard", 21),
    ("icon_flint", 22),
    ("icon_flask_fire", 23),
    ("icon_flask_light", 24),
    ("icon_flask_haste", 25),
    ("icon_bandage", 26),
    ("icon_stew", 27),
    ("icon_roast", 28),
    ("icon_cake", 29),
    ("icon_torch", 30),
    ("icon_lantern", 31),
    ("icon_campfire", 32),
    ("icon_ladder", 33),
    ("icon_rope", 34),
    ("icon_platform", 35),
    ("icon_chest", 36),
    ("icon_pearl", 37),
    ("icon_pearl_shard", 38),
    ("icon_bone", 39),
    ("icon_scrap", 40),
    ("icon_core_ember", 41),
    ("icon_core_frozen", 42),
    ("icon_gel", 43),
    ("icon_chitin", 44),
    ("icon_hide", 45),
    ("icon_wing", 46),
    ("icon_dust", 47),
    ("icon_sac", 48),
    ("icon_meat", 49),
    ("icon_sapling", 50),
    ("icon_anvil", 51),
    ("icon_furnace", 52),
    ("icon_workbench", 53),
    ("icon_chitin_plate", 54),
    ("icon_hide_jerkin", 55),
];
