// GENERATED by contentc — DO NOT EDIT
// 14 sounds from 3 source file(s):
//   content/sounds/mobs.toml
//   content/sounds/player.toml
//   content/sounds/world.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which oscillator. Adding one needs code.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SoundWave {
    Square,
    Saw,
    Sine,
    Triangle,
    Noise,
}

impl SoundWave {
    /// The variant a compiled code stands for, or `None` if this
    /// build has no such variant.
    #[inline]
    pub const fn from_code(code: u8) -> Option<SoundWave> {
        Some(match code {
            0 => SoundWave::Square,
            1 => SoundWave::Saw,
            2 => SoundWave::Sine,
            3 => SoundWave::Triangle,
            4 => SoundWave::Noise,
            _ => return None,
        })
    }
}

/// The compiled shape of one sound. Derived from
/// crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SoundDef {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Display name — the settings screen and the debug HUD.
    pub name: &'static str,
    /// Which oscillator. Adding one needs code.
    pub wave: u8,
    /// Starting pitch in hertz.
    pub hz: f32,
    /// Pitch at the end of the sound. Equal to `hz` means no sweep; below it
    /// falls, above it rises.
    pub hz_to: f32,
    /// Total length. Short: this is feedback, not music.
    pub seconds: f32,
    /// Fraction of the length spent rising to full volume. 0 is an instant onset,
    /// which is what an impact wants.
    pub attack: f32,
    /// Fraction of the length spent falling to silence. A sound with neither
    /// attack nor release clicks at both ends.
    pub release: f32,
    /// How much white noise is mixed over the oscillator. Grit — a footstep on
    /// gravel against one on stone.
    pub noise: f32,
    /// Per-sound volume, before the player's own setting.
    pub gain: f32,
}

/// Authoring ids, index == code.
pub static SOUND_IDS: [&str; 14] = [
    "dash",
    "dig",
    "double_jump",
    "hurt",
    "jump",
    "land",
    "mob_die",
    "mob_hurt",
    "pickup",
    "place",
    "player_hit",
    "splash",
    "step",
    "wall_jump",
];

/// Every def, index == code, tombstones included.
pub static SOUNDS: [SoundDef; 14] = [
    SoundDef {
        id: "dash",
        code: 0,
        name: "Dash",
        wave: 4,
        hz: 900.0,
        hz_to: 260.0,
        seconds: 0.14,
        attack: 0.02,
        release: 0.75,
        noise: 0.0,
        gain: 0.35,
    },
    SoundDef {
        id: "dig",
        code: 1,
        name: "Dig",
        wave: 4,
        hz: 300.0,
        hz_to: 200.0,
        seconds: 0.04,
        attack: 0.0,
        release: 0.85,
        noise: 0.0,
        gain: 0.2,
    },
    SoundDef {
        id: "double_jump",
        code: 2,
        name: "Double jump",
        wave: 0,
        hz: 480.0,
        hz_to: 760.0,
        seconds: 0.08,
        attack: 0.05,
        release: 0.6,
        noise: 0.0,
        gain: 0.28,
    },
    SoundDef {
        id: "hurt",
        code: 3,
        name: "Hurt",
        wave: 1,
        hz: 420.0,
        hz_to: 120.0,
        seconds: 0.22,
        attack: 0.0,
        release: 0.55,
        noise: 0.2,
        gain: 0.6,
    },
    SoundDef {
        id: "jump",
        code: 4,
        name: "Jump",
        wave: 0,
        hz: 320.0,
        hz_to: 520.0,
        seconds: 0.09,
        attack: 0.05,
        release: 0.6,
        noise: 0.1,
        gain: 0.3,
    },
    SoundDef {
        id: "land",
        code: 5,
        name: "Land",
        wave: 4,
        hz: 180.0,
        hz_to: 90.0,
        seconds: 0.12,
        attack: 0.0,
        release: 0.7,
        noise: 0.0,
        gain: 0.45,
    },
    SoundDef {
        id: "mob_die",
        code: 6,
        name: "Creature dies",
        wave: 1,
        hz: 480.0,
        hz_to: 90.0,
        seconds: 0.3,
        attack: 0.0,
        release: 0.7,
        noise: 0.35,
        gain: 0.5,
    },
    SoundDef {
        id: "mob_hurt",
        code: 7,
        name: "Creature hurt",
        wave: 1,
        hz: 620.0,
        hz_to: 260.0,
        seconds: 0.11,
        attack: 0.0,
        release: 0.6,
        noise: 0.25,
        gain: 0.4,
    },
    SoundDef {
        id: "pickup",
        code: 8,
        name: "Pick up",
        wave: 2,
        hz: 520.0,
        hz_to: 780.0,
        seconds: 0.07,
        attack: 0.05,
        release: 0.6,
        noise: 0.0,
        gain: 0.3,
    },
    SoundDef {
        id: "place",
        code: 9,
        name: "Place",
        wave: 3,
        hz: 340.0,
        hz_to: 300.0,
        seconds: 0.05,
        attack: 0.0,
        release: 0.7,
        noise: 0.15,
        gain: 0.22,
    },
    SoundDef {
        id: "player_hit",
        code: 10,
        name: "Creature hits you",
        wave: 0,
        hz: 200.0,
        hz_to: 140.0,
        seconds: 0.07,
        attack: 0.0,
        release: 0.5,
        noise: 0.5,
        gain: 0.45,
    },
    SoundDef {
        id: "splash",
        code: 11,
        name: "Splash",
        wave: 4,
        hz: 700.0,
        hz_to: 240.0,
        seconds: 0.18,
        attack: 0.03,
        release: 0.8,
        noise: 0.0,
        gain: 0.4,
    },
    SoundDef {
        id: "step",
        code: 12,
        name: "Footstep",
        wave: 4,
        hz: 220.0,
        hz_to: 160.0,
        seconds: 0.05,
        attack: 0.0,
        release: 0.8,
        noise: 0.0,
        gain: 0.25,
    },
    SoundDef {
        id: "wall_jump",
        code: 13,
        name: "Wall jump",
        wave: 0,
        hz: 300.0,
        hz_to: 430.0,
        seconds: 0.08,
        attack: 0.0,
        release: 0.65,
        noise: 0.35,
        gain: 0.3,
    },
];

pub const SOUND_COUNT: usize = 14;

/// id -> code. Consts, so `sound::STONE` is a compile-time constant.
pub mod sound {
    pub const DASH: u16 = 0;
    pub const DIG: u16 = 1;
    pub const DOUBLE_JUMP: u16 = 2;
    pub const HURT: u16 = 3;
    pub const JUMP: u16 = 4;
    pub const LAND: u16 = 5;
    pub const MOB_DIE: u16 = 6;
    pub const MOB_HURT: u16 = 7;
    pub const PICKUP: u16 = 8;
    pub const PLACE: u16 = 9;
    pub const PLAYER_HIT: u16 = 10;
    pub const SPLASH: u16 = 11;
    pub const STEP: u16 = 12;
    pub const WALL_JUMP: u16 = 13;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Oscillator code.
pub static SND_WAVE: [u8; 14] = [4, 4, 0, 1, 0, 4, 1, 1, 2, 3, 0, 4, 4, 0];

/// Starting pitch, Hz.
pub static SND_HZ: [f32; 14] = [
    900.0, 300.0, 480.0, 420.0, 320.0, 180.0, 480.0, 620.0, 520.0, 340.0, 200.0, 700.0, 220.0,
    300.0,
];

/// Ending pitch, Hz.
pub static SND_HZ_TO: [f32; 14] = [
    260.0, 200.0, 760.0, 120.0, 520.0, 90.0, 90.0, 260.0, 780.0, 300.0, 140.0, 240.0, 160.0, 430.0,
];

/// Length in seconds.
pub static SND_SECONDS: [f32; 14] = [
    0.14, 0.04, 0.08, 0.22, 0.09, 0.12, 0.3, 0.11, 0.07, 0.05, 0.07, 0.18, 0.05, 0.08,
];

/// Attack, as a fraction of the length.
pub static SND_ATTACK: [f32; 14] = [
    0.02, 0.0, 0.05, 0.0, 0.05, 0.0, 0.0, 0.0, 0.05, 0.0, 0.0, 0.03, 0.0, 0.0,
];

/// Release, as a fraction of the length.
pub static SND_RELEASE: [f32; 14] = [
    0.75, 0.85, 0.6, 0.55, 0.6, 0.7, 0.7, 0.6, 0.6, 0.7, 0.5, 0.8, 0.8, 0.65,
];

/// Noise mix, 0..1.
pub static SND_NOISE: [f32; 14] = [
    0.0, 0.0, 0.0, 0.2, 0.1, 0.0, 0.35, 0.25, 0.0, 0.15, 0.5, 0.0, 0.0, 0.35,
];

/// Per-sound gain, 0..1.
pub static SND_GAIN: [f32; 14] = [
    0.35, 0.2, 0.28, 0.6, 0.3, 0.45, 0.5, 0.4, 0.3, 0.22, 0.45, 0.4, 0.25, 0.3,
];

/// Every flat table in this module, by name. For the gates, not the game.
pub static SOUND_TABLES: &[(&str, crate::Table)] = &[
    ("SND_WAVE", crate::Table::U8(&SND_WAVE)),
    ("SND_HZ", crate::Table::F32(&SND_HZ)),
    ("SND_HZ_TO", crate::Table::F32(&SND_HZ_TO)),
    ("SND_SECONDS", crate::Table::F32(&SND_SECONDS)),
    ("SND_ATTACK", crate::Table::F32(&SND_ATTACK)),
    ("SND_RELEASE", crate::Table::F32(&SND_RELEASE)),
    ("SND_NOISE", crate::Table::F32(&SND_NOISE)),
    ("SND_GAIN", crate::Table::F32(&SND_GAIN)),
];

/// Authoring id -> code, by name. For the gates, not the game.
pub static SOUND_CODES: &[(&str, u16)] = &[
    ("dash", 0),
    ("dig", 1),
    ("double_jump", 2),
    ("hurt", 3),
    ("jump", 4),
    ("land", 5),
    ("mob_die", 6),
    ("mob_hurt", 7),
    ("pickup", 8),
    ("place", 9),
    ("player_hit", 10),
    ("splash", 11),
    ("step", 12),
    ("wall_jump", 13),
];
