// GENERATED by contentc — DO NOT EDIT
// 88 sprites from 2 source file(s):
//   content/sprites/icons.toml
//   content/sprites/player.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which pose this sequence supplies. Closed vocabulary — a typo is a build
/// error. The facade names this union `AnimState`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqState {
    Idle,
    Run,
    Skid,
    Jump,
    DoubleJump,
    Fall,
    Land,
    Dash,
    WallSlide,
    Swim,
    Punch,
    Hurt,
}

impl SpriteSeqState {
    /// The variant a compiled code stands for, or `None` if this
    /// build has no such variant.
    #[inline]
    pub const fn from_code(code: u8) -> Option<SpriteSeqState> {
        Some(match code {
            0 => SpriteSeqState::Idle,
            1 => SpriteSeqState::Run,
            2 => SpriteSeqState::Skid,
            3 => SpriteSeqState::Jump,
            4 => SpriteSeqState::DoubleJump,
            5 => SpriteSeqState::Fall,
            6 => SpriteSeqState::Land,
            7 => SpriteSeqState::Dash,
            8 => SpriteSeqState::WallSlide,
            9 => SpriteSeqState::Swim,
            10 => SpriteSeqState::Punch,
            11 => SpriteSeqState::Hurt,
            _ => return None,
        })
    }
}

/// How the frames are stepped. Names are the contract with the runtime's
/// picker.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum SpriteSeqMode {
    Hold,
    Loop,
    Once,
    Phase,
    Ambient,
}

impl SpriteSeqMode {
    /// The variant a compiled code stands for, or `None` if this
    /// build has no such variant.
    #[inline]
    pub const fn from_code(code: u8) -> Option<SpriteSeqMode> {
        Some(match code {
            0 => SpriteSeqMode::Hold,
            1 => SpriteSeqMode::Loop,
            2 => SpriteSeqMode::Once,
            3 => SpriteSeqMode::Phase,
            4 => SpriteSeqMode::Ambient,
            _ => return None,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteSeq {
    /// Which pose this sequence supplies. Closed vocabulary — a typo is a build
    /// error. The facade names this union `AnimState`.
    pub state: SpriteSeqState,
    /// How the frames are stepped. Names are the contract with the runtime's
    /// picker.
    pub mode: SpriteSeqMode,
    /// Playback rate for THIS sequence. 0 inherits the sprite's `fps`, which is
    /// why the default is 0 and not 8 — 0 is 'unset', and an explicit 8 here
    /// would pin the sequence if the sprite were ever retuned.
    pub fps: f32,
    /// `ambient` only: seconds between interrupts. 0 = never interrupt. The
    /// interrupt frame is the sequence's LAST frame, so the ambient cycle itself
    /// is frames[0..n-2].
    pub blink_every: f32,
    /// `ambient` only: seconds the interrupt frame is held.
    pub blink_for: f32,
    /// The frames, as a `'''` body: `cellsH` rows per frame, frames separated by
    /// a blank line. Read it as a filmstrip.
    pub frames: &'static [&'static str],
}

/// The compiled shape of one sprite. Derived from
/// crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SpriteDef {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Display name, for the art debug overlay. Defaults to the id.
    pub name: &'static str,
    /// Art grid width in world cells. One art pixel is one world cell.
    pub cells_w: i32,
    /// Art grid height in world cells. Every frame must have exactly this many
    /// rows.
    pub cells_h: i32,
    /// Art pixels per world cell, per axis. 1 — the default, and the rule
    /// everywhere — is ONE ART PIXEL IS ONE WORLD CELL. 2 doubles the art
    /// resolution inside the SAME world rectangle: the grid is still `cellsW` x
    /// `cellsH` CELLS, the drawn rect and every collision quantity are untouched,
    /// but each frame row is `cellsW * grain` characters and there are `cellsH *
    /// grain` rows. A finer-grained sprite is drawn on a finer grid than the
    /// terrain it stands on, which is exactly the mismatch the invariant exists
    /// to prevent — so this is an EXPERIMENT'S knob, not a default to drift
    /// toward. It exists so one creature can be redrawn finer and judged against
    /// its neighbours in a picture before any fleet-wide decision.
    pub grain: i32,
    /// Palette, "#rrggbb" per index. Index 0 is the transparent slot and is
    /// written "." — it is never painted, so its value is a placeholder, not a
    /// colour. Frame characters are digits indexing this list.
    pub pal: &'static [&'static str],
    /// Sprite-wide playback rate. A sequence with its own non-zero `fps`
    /// overrides it, so this is the value for everything that has no reason to be
    /// special.
    pub fps: f32,
    /// How many tinted copies of the whole sprite to bake. 1 = just the palette
    /// as authored. More than one lets a crowd of the same creature read as
    /// individuals without authoring a second palette, at the cost of one extra
    /// baked canvas set each.
    pub variants: i32,
    /// One animation sequence per entry, in file order. Attributes as keys,
    /// frames in the `frames` body.
    pub seq: Option<&'static [SpriteSeq]>,
}

/// Authoring ids, index == code.
pub static SPRITE_IDS: [&str; 88] = [
    "player",
    "icon_block_cube",
    "icon_pick_traveler",
    "icon_pick_copper",
    "icon_pick_iron",
    "icon_pick_gold",
    "icon_pick_gem",
    "icon_sword_traveler",
    "icon_sword_king",
    "icon_bow",
    "icon_sling",
    "icon_arrow",
    "icon_arrow_iron",
    "icon_ore_copper",
    "icon_ore_iron",
    "icon_ore_gold",
    "icon_coal",
    "icon_bar_copper",
    "icon_bar_iron",
    "icon_bar_gold",
    "icon_gem",
    "icon_crystal_shard",
    "icon_flint",
    "icon_flask_fire",
    "icon_flask_light",
    "icon_flask_haste",
    "icon_bandage",
    "icon_stew",
    "icon_roast",
    "icon_cake",
    "icon_torch",
    "icon_lantern",
    "icon_campfire",
    "icon_ladder",
    "icon_rope",
    "icon_platform",
    "icon_chest",
    "icon_pearl",
    "icon_pearl_shard",
    "icon_bone",
    "icon_scrap",
    "icon_core_ember",
    "icon_core_frozen",
    "icon_gel",
    "icon_chitin",
    "icon_hide",
    "icon_wing",
    "icon_dust",
    "icon_sac",
    "icon_meat",
    "icon_sapling",
    "icon_anvil",
    "icon_furnace",
    "icon_workbench",
    "icon_chitin_plate",
    "icon_hide_jerkin",
    "icon_dirt_clod",
    "icon_ice_shard",
    "icon_sand_pile",
    "icon_stone_chunk",
    "icon_wood_log",
    "icon_peat_clod",
    "icon_scoria_block",
    "icon_tar_glob",
    "icon_ash_pile",
    "icon_autumn_leaf",
    "icon_basalt_block",
    "icon_bounce_pad",
    "icon_cactus_pad",
    "icon_clay_lump",
    "icon_conveyor_left",
    "icon_conveyor_right",
    "icon_crystal_block",
    "icon_glass_pane",
    "icon_gravel_pile",
    "icon_jungle_leaf",
    "icon_moss_clump",
    "icon_mud_ball",
    "icon_mushroom_cap",
    "icon_mushroom_stem",
    "icon_obsidian_block",
    "icon_packed_ice",
    "icon_permafrost_block",
    "icon_sandstone_block",
    "icon_snow_ball",
    "icon_sticky_mud",
    "icon_vine_coil",
    "icon_wet_sand_pile",
];

/// Every def, index == code, tombstones included.
pub static SPRITES: [SpriteDef; 88] = [
    SpriteDef {
        id: "player",
        code: 0,
        name: "Player",
        cells_w: 8,
        cells_h: 10,
        grain: 1,
        pal: &[
            ".", "#1b1220", "#3ec8b4", "#21877e", "#ffcf5c", "#ff6b57", "#fff3c4", "#14564f",
            "#e8913a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[
            SpriteSeq {
                state: SpriteSeqState::Idle,
                mode: SpriteSeqMode::Ambient,
                fps: 1.6129032,
                blink_every: 4.6,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "..8.....", "..88....", "..4444..", "..8444..",
                    ".73322..", ".73322..", ".73..2..", "..1..1..", "", "........", "........",
                    ".8......", ".88.....", "..4444..", "..8444..", ".72222..", ".72222..",
                    ".73..2..", "..1..1..", "", "........", "........", "..3.....", "..33....",
                    "..3333..", "..3333..", ".73322..", ".73322..", ".73..2..", "..1..1..",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Run,
                mode: SpriteSeqMode::Phase,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "..8.....", "..88....", "..4444..", "..8444..",
                    ".73322..", "7.3322..", "..7...2.", ".77...11", "", "........", ".8......",
                    ".88.....", "..4444..", "..8444..", "..2222..", "..2222..", "...32...",
                    "...32...", "...11...", "", "........", "........", "..8.....", "..88....",
                    "..4444..", "..8444..", "..332222", "..3322..", ".1....7.", "11....77", "",
                    "........", "........", "..8.....", "..88....", "..4444..", "..8444..",
                    ".73322..", ".73322..", ".73..2..", "..1..1..",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Skid,
                mode: SpriteSeqMode::Loop,
                fps: 10.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "....88..", "...8888.", "..4444..", "..4448..",
                    ".72233..", "7.2233..", "..2...3.", "..1...11", "", "........", "........",
                    "....88..", "...8888.", "..4444..", "..4448..", ".72233..", "7.2233..",
                    "..2...3.", "..1.6611",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Jump,
                mode: SpriteSeqMode::Once,
                fps: 9.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "......2.", "......2.", "..8...2.", "..88..2.", "..44442.", "..84442.",
                    "..22222.", "..2222..", "...22...", "...1....", "", "........", "........",
                    ".8888...", "..88....", "..4444..", "..8444..", ".73322..", ".73322..",
                    "...32...", "...1....",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::DoubleJump,
                mode: SpriteSeqMode::Once,
                fps: 12.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", ".8844...", ".8844...", "...22...", "..2222..",
                    "..3333..", "...33...", "...66...", "........", "", "........", "........",
                    "........", "........", "...22.88", "..222288", "..333344", "...33.44",
                    "........", "........", "", "........", "........", "........", "........",
                    "...22...", "..2222..", "..333388", "...33.88", "...44...", "...44...", "",
                    "........", "........", "..8.....", "..88....", "..4444..", "..8444..",
                    "..332222", "..3322..", ".1....7.", "11....77",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Fall,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", ".8888...", "..88....", "..4444..", "..8444..",
                    "773333..", "..3333..", "...3..7.", "...1..7.", "", "........", "........",
                    "..88....", ".788..2.", "77444422", "..8444..", "..3333..", "..3333..",
                    "...33...", "........", "", "........", "........", ".8888...", "..88....",
                    "..4444..", "..8444..", "..333322", "..3333..", ".7...3..", ".7...1..",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Land,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "........", "........", "..8888..", ".888888.",
                    "77444422", "77333322", "66111166", ".611116.", "", "........", "........",
                    "..8.....", "..88....", "..4444..", "..8444..", ".73333..", ".73333..",
                    ".73..3..", "..1..1..", "", "........", "........", "..8.....", "..88....",
                    "..4444..", "..8444..", ".73322..", ".73322..", ".73..2..", "..1..1..",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Dash,
                mode: SpriteSeqMode::Loop,
                fps: 18.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "6.......", "66......", "884444..", "884444..",
                    "..2222..", "..2222..", "...22...", "....1...", "", "........", "........",
                    "........", "........", "884444..", "884444..", "662222..", "6.2222..",
                    "...22...", "....1...", "", "........", "........", "6.......", "66......",
                    "884444..", "884444..", "662222..", "6.2222..", "...22...", "....1...",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::WallSlide,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "...8....", "...88...", "....44..", "....84..",
                    "...722..", "...722..", "....22..", "....11..", "", "........", "........",
                    "..8.....", "..88....", "....44..", "....84..", "...722..", "...722..",
                    "....22..", "........",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Swim,
                mode: SpriteSeqMode::Loop,
                fps: 6.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "........", "....6...", "88224444", ".8338444",
                    "7777....", "........", "........", "........", "", "........", "........",
                    "........", "........", "88224444", ".8338444", "..772...", "..77....",
                    "........", "........", "", "........", "........", "........", ".......6",
                    "88224444", ".8338444", "777722..", "........", "........", "........", "",
                    "........", "........", "........", "........", "88224444", ".8338444",
                    "..772...", "..77....", "........", "........",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Punch,
                mode: SpriteSeqMode::Once,
                fps: 14.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "........", "........", "..8.....", "..88....", "..4444..", "..8444..",
                    ".23333..", "223333..", "..3..3..", "..1..1..", "", "........", "........",
                    "88......", ".88.....", "..4444.6", "..8444.6", "..332226", "..3322.6",
                    "..3..2..", "..1..1..", "", "........", "........", "..8.....", "..88....",
                    "..4444..", "..8444..", ".73322..", ".73322..", ".73..2..", "..1..1..",
                ],
            },
            SpriteSeq {
                state: SpriteSeqState::Hurt,
                mode: SpriteSeqMode::Hold,
                fps: 0.0,
                blink_every: 0.0,
                blink_for: 0.1,
                frames: &[
                    "5.......", "55......", ".55.....", "..55....", "..5555..", "..5555..",
                    ".72233..", "7.2233..", "..2..31.", "..1.....",
                ],
            },
        ]),
    },
    SpriteDef {
        id: "icon_block_cube",
        code: 1,
        name: "icon_block_cube",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#5c5c66", "#8a8a95", "#b4b4c0", "#dcdce6"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "13332221", "13332221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_traveler",
        code: 2,
        name: "icon_pick_traveler",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#4e463c", "#6e6458", "#a89a86", "#3e2c1a",
            "#c4b8a4",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_copper",
        code: 3,
        name: "icon_pick_copper",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#7a4324", "#a35f36", "#e08a52", "#3e2c1a",
            "#ffc48a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_iron",
        code: 4,
        name: "icon_pick_iron",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#5c5856", "#7e7a78", "#c8c4c0", "#3e2c1a",
            "#eceaea",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gold",
        code: 5,
        name: "icon_pick_gold",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#553a22", "#8a6238", "#7e5f18", "#b08a2e", "#f0d878", "#3e2c1a",
            "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pick_gem",
        code: 6,
        name: "icon_pick_gem",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#38202c", "#5c3a4a", "#6e2048", "#8e2f5e", "#e878b4", "#2a1620",
            "#ffd8f0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".186551.", "16554441", "15177141", ".113211.", "..1321..", "...1321.",
                "...1111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sword_traveler",
        code: 7,
        name: "icon_sword_traveler",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a2a1a", "#5a4630", "#8a8e96", "#c2c6ce", "#7d6a48", "#f2f6ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....1741", "...1541.", "..1541..", ".1541...", "166661..", ".1321...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sword_king",
        code: 8,
        name: "icon_sword_king",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a2c12", "#5c4820", "#c8a63e", "#f2dc94", "#9a7420", "#fff6cc",
            "#e0508c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....1741", "...1541.", "..1541..", ".1541...", "1686617.", ".1321777",
                ".1661.7.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bow",
        code: 9,
        name: "icon_bow",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#6b4420", "#a5713a", "#d8c898"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...1321.", "..13241.", ".132.41.", "132..41.", "132..41.", ".132.41.", "..13241.",
                "...1321.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sling",
        code: 10,
        name: "icon_sling",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#cdbb95", "#7a6c50", "#b8a884", "#9a9894"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "121..121", ".121121.", "..1221..", ".144331.", ".145531.", ".143331.", "..1331..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_arrow",
        code: 11,
        name: "icon_arrow",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#7a5a2e", "#a0783f", "#9a98a2", "#6e6c74", "#b8b096", "#d8cfae",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "......41", ".....451", "....1451", "...1321.", "..1321..", ".1321...", "17661...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_arrow_iron",
        code: 12,
        name: "icon_arrow_iron",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#7a5a2e", "#a0783f", "#dfe3eb", "#9aa0a8", "#b8b096", "#d8cfae",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "......41", ".....451", "....1451", "...1321.", "..1321..", ".1321...", "17661...",
                ".1661...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_copper",
        code: 13,
        name: "icon_ore_copper",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#7a4526", "#c2703f", "#f09a5e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14433651", "14763221", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_iron",
        code: 14,
        name: "icon_ore_iron",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#6e7682", "#aab2be", "#eaf0f6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14433651", "14763221", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ore_gold",
        code: 15,
        name: "icon_ore_gold",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a3733", "#5e5a55", "#807a72", "#8a6a20", "#c8a038", "#f0d878",
            "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...111..", "..14431.", ".1443761", "14437871", "14763721", "13365221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_coal",
        code: 16,
        name: "icon_coal",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#26232c", "#3d3848", "#565064", "#7a7290"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11111.", ".1454321", "14543321", "14433221", "13332221", "13222221", ".1222221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_copper",
        code: 17,
        name: "icon_bar_copper",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6b3c1f", "#a35f36", "#c2703f", "#e08a52", "#f7b478",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".165551.", "14444441", "14322331", "13322331", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_iron",
        code: 18,
        name: "icon_bar_iron",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4e535c", "#7c828c", "#a6acb6", "#ced4de", "#f0f4fa",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".165551.", "14444441", "14322331", "13322331", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bar_gold",
        code: 19,
        name: "icon_bar_gold",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e5218", "#b08a2e", "#d0a838", "#f0d878", "#ffeaa0", "#fff6c0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", ".155551.", "14644441", "16764331", "13633221", "13222221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_gem",
        code: 20,
        name: "icon_gem",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#52123a", "#6e1e46", "#b8407e", "#e878b4", "#f0a0d0", "#ffe6f6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".165441.", "16764331", ".164331.", "..1431..", "..1321..", "...121..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_crystal_shard",
        code: 21,
        name: "icon_crystal_shard",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#322558", "#4a3a7a", "#6e52b0", "#8e6ce0", "#cfb4ff", "#f4ecff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".....11.", "....151.", "...1651.", "..16761.", "..13641.", ".134431.", ".133221.",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flint",
        code: 22,
        name: "icon_flint",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#2e2c34", "#4e4c56", "#7a7884", "#b0aeba"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154431.", "15444331", "14443321", "14433221", "1433221.", ".13221..",
                "..111...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_fire",
        code: 23,
        name: "icon_flask_fire",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#43384a", "#877a90", "#a83a14", "#e8763a", "#ffc06a", "#ffe8b0",
            "#7a5230",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", ".132221.", "13227221", "16665551", "15444441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_light",
        code: 24,
        name: "icon_flask_light",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4a3f5c", "#8f82a8", "#7a52a8", "#b48ad8", "#f0d8ff", "#fcf2ff",
            "#7a5230", "#3a2a52",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", "91322219", "13227221", "16665551", "15444441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_flask_haste",
        code: 25,
        name: "icon_flask_haste",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3f3a52", "#7e7898", "#5e4a92", "#8a72b8", "#cfc0f0", "#efe6ff",
            "#7a5230",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".188881.", "..1321..", ".132221.", "13276661", "16655551", "15544441",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bandage",
        code: 26,
        name: "icon_bandage",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#8a7a5c", "#a89878", "#d8d2c0", "#efe9dc"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154421.", "15442331", "14423331", ".142331.", "..11431.", "...14331",
                "...11111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_stew",
        code: 27,
        name: "icon_stew",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4a3a2c", "#6a5240", "#8a6a50", "#8a4e2a", "#b06a3c", "#d8935c",
            "#e8b878",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1771..", ".176651.", "17686551", "14444431", "14333321", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_roast",
        code: 28,
        name: "icon_roast",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#5c3620", "#9a5e34", "#c88a52", "#e6a86c", "#e4dcc4", "#b0a68c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...1111.", "..154441", ".1544331", ".1443321", ".1433221", ".1672221", "1671111.",
                "1661....",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_cake",
        code: 29,
        name: "icon_cake",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#5e4478", "#8a6aa8", "#a888c0", "#d8b8f0", "#f2e2ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", ".111111.", "16555551", "15544441", "14433331", "13332221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_torch",
        code: 30,
        name: "icon_torch",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#5a3a20", "#7a5230", "#c85a1c", "#ff9a3a", "#ffd67e", "#a3521a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", "7156517.", ".14541..", ".13321..", "..1321..", "..1321..",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_lantern",
        code: 31,
        name: "icon_lantern",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e5418", "#c8a03c", "#e8a82e", "#ffdc88", "#fff8d8", "#8a6418",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".712217.", ".133221.", "12655521", "12654421", "12554421", "12544421", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_campfire",
        code: 32,
        name: "icon_campfire",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4e3018", "#7a4a2a", "#c04a12", "#ff9a3c", "#ffd070", "#8f3f0e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1661..", ".156651.", ".145541.", "71455417", ".144441.", "13211321",
                "12211221",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ladder",
        code: 33,
        name: "icon_ladder",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#8a6234", "#c8a068"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "11....11", "132..321", "13233321", "132..321", "13233321", "132..321", "13233321",
                "11....11",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_rope",
        code: 34,
        name: "icon_rope",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#7d6640", "#a08858", "#d8c098"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".144331.", "143..321", "143..321", "133..221", ".133221.", "..1111..",
                "...1321.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_platform",
        code: 35,
        name: "icon_platform",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#6a4a24", "#8a6234", "#c09050"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14444441", "13333331", "12222221", ".13..31.", ".13..31.", ".13..31.",
                ".11..11.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chest",
        code: 36,
        name: "icon_chest",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4e3316", "#7a5228", "#a06e38", "#b8901f", "#e8c85a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14455441", "13355331", "11156111", "13355331", "12255221", "12255221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pearl",
        code: 37,
        name: "icon_pearl",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e6a84", "#9a94b0", "#c8c2d8", "#eae6f4", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".165431.", "16664331", "15644321", "14443521", "14333221", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_pearl_shard",
        code: 38,
        name: "icon_pearl_shard",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e6a84", "#9a94b0", "#c8c2d8", "#eae6f4", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", "...111..", "..15441.", ".156541.", ".145431.", "..1431..", "...121..",
                "...111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bone",
        code: 39,
        name: "icon_bone",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#b0a68c", "#e4dcc4", "#f6f0dc"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111....", "14431...", "143331..", ".11331..", "...1331.", "...13321", "...13221",
                "....111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_scrap",
        code: 40,
        name: "icon_scrap",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#454c5a", "#6e7686", "#b0b8c8", "#e2e8f2"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".11.11..", "1541441.", "14444331", "14333321", ".1332221", "..132221", "...12221",
                "....1111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_core_ember",
        code: 41,
        name: "icon_core_ember",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#5c1c08", "#8a3010", "#e86a20", "#ffc060", "#fff0c0", "#4a1c0c",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", "71443317", "14554331", "14565431", "13455431", "13344321", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_core_frozen",
        code: 42,
        name: "icon_core_frozen",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#1e4058", "#3a6a90", "#6ab0e0", "#a8dcf6", "#eafaff", "#142c44",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1441..", "71455417", "14566541", "13455431", ".134431.", "..1321..",
                "...11...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_gel",
        code: 43,
        name: "icon_gel",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#2e6640", "#4e9a62", "#8ee0a0", "#c8f6d4"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1441..", ".155441.", "14544331", "14433321", "14333221", "13322221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chitin",
        code: 44,
        name: "icon_chitin",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#4a3c26", "#6e5a3c", "#a8895c", "#d0ae78"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".155441.", "15554331", "14454321", "14353221", "13353221", ".135321.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_hide",
        code: 45,
        name: "icon_hide",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#4a3626", "#6e523a", "#a07a52", "#c49a6c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".1....1.", "151..151", "15444451", "15444331", "14433321", "14332221", "131..121",
                ".1....1.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_wing",
        code: 46,
        name: "icon_wing",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#3a2e3e", "#5a4a5e", "#9a86a2", "#c2b0c8"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "1111....", "154411..", "1542431.", "14423331", "14323231", ".1323231", "..123231",
                "..11.11.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_dust",
        code: 47,
        name: "icon_dust",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#8a7a4e", "#b8a878", "#f0e2b0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...41...", ".41.....", ".....41.", "...11...", "..1431..", ".144331.", "14333221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sac",
        code: 48,
        name: "icon_sac",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#45285e", "#6a4a86", "#b088d0", "#e8d4ff"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "...11...", "..1431..", ".144331.", "14453331", "14353521", "13332521", ".133221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_meat",
        code: 49,
        name: "icon_meat",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e3a3e", "#a86868", "#d89a94", "#eec4bc", "#f2ddc8",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11111.", ".1554431", "15464331", "14463321", "14336321", "13332221", ".132221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sapling",
        code: 50,
        name: "icon_sapling",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a2a18", "#6a4a2c", "#4e8a34", "#7ac04e", "#a8e070", "#8a6a44",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".11..11.", "16511541", ".1513141", "..11311.", "...131..", "..17731.", ".1733221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_anvil",
        code: 51,
        name: "icon_anvil",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#33353a", "#4c4e54", "#72767e", "#b4b8c0"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "14444441", "13333331", "..1331..", "..1221..", ".133331.",
                "12222221",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_furnace",
        code: 52,
        name: "icon_furnace",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3e3c3a", "#5a5856", "#7a7674", "#c8601c", "#ffb04a", "#7e3a10",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1441..", "..1331..", "14444441", "13111131", "13566531", "13566531", "13555531",
                "72222227",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_workbench",
        code: 53,
        name: "icon_workbench",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#6a4a26", "#9a703e", "#c49a5c"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "14444441", "13333331", ".122221.", ".131131.", ".131131.", ".133331.",
                ".121121.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_chitin_plate",
        code: 54,
        name: "icon_chitin_plate",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#4a3c24", "#6a5838", "#8a7450", "#c0a870"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "11111111", "14411441", "14355321", "13355321", "11355311", "13355221", ".135521.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_hide_jerkin",
        code: 55,
        name: "icon_hide_jerkin",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#4e3620", "#6a4c30", "#8c6a44", "#c2a074"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".14..41.", "14411441", "13455321", "13355321", "13255221", ".132221.", ".122221.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_dirt_clod",
        code: 56,
        name: "icon_dirt_clod",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#2e1f13", "#472f1c", "#66462b", "#8a6039", "#a87c4e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..111...", ".16541..", "1655431.", "16554321", "15443221", ".1433221", "..11111.",
                "51....41",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ice_shard",
        code: 57,
        name: "icon_ice_shard",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#1e3c56", "#31607f", "#4d8db2", "#7fbcd8", "#b6e2f2", "#e8f8ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11....", ".1761...", ".16541..", ".165431.", "16554321", "15453221", "14432221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sand_pile",
        code: 58,
        name: "icon_sand_pile",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#6f5a38", "#96794c", "#c0a068", "#e2c894"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11....", ".1551...", ".15541..", "1554431.", "15544331", "14443321", "13332221",
                "11111111",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_stone_chunk",
        code: 59,
        name: "icon_stone_chunk",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a3842", "#5b5966", "#82808e", "#a6a4b2", "#cdcbd6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".165541.", "16555431", "15554321", "15543221", "14432221", ".1322221",
                "..11111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_wood_log",
        code: 60,
        name: "icon_wood_log",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3a2718", "#59402a", "#7d5c3a", "#9a7a4e", "#c2a071", "#e2c99a",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                ".111111.", "16661441", "16761431", "16761431", "16761331", "15651321", "15551221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_peat_clod",
        code: 61,
        name: "icon_peat_clod",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#241a10", "#3a2c1a", "#4e3c24", "#66502f", "#4a5c30",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "........", ".111111.", "15546541", "13233231", "11111111", "14535431", "12322321",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_scoria_block",
        code: 62,
        name: "icon_scoria_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[".", "#16121e", "#2a1e1c", "#443230", "#5c4440", "#745650"],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..11111.", ".1554431", "15514331", "14531231", "14413321", "13321321", ".131231.",
                "..1111..",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_tar_glob",
        code: 63,
        name: "icon_tar_glob",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#0d0b09", "#1c1712", "#2a231b", "#453a2e", "#948a76",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".166421.", "16654321", "15432221", "14322221", ".132221.", "..1121..",
                "...12...",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_ash_pile",
        code: 64,
        name: "icon_ash_pile",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#32302f", "#474443", "#5c5856", "#75706e", "#8e8885",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444641", "13332221", "13632221", "13332621", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_autumn_leaf",
        code: 65,
        name: "icon_autumn_leaf",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#603b18", "#895422", "#b06c2c", "#e18a38", "#7a3820",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332261", "13332621", "13366221", "13632221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_basalt_block",
        code: 66,
        name: "icon_basalt_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#1e1c21", "#2b282e", "#38343c", "#47424c", "#56505d",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15446441", "13362261", "13362261", "13362261", "13362261",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_bounce_pad",
        code: 67,
        name: "icon_bounce_pad",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#2c7942", "#3eab5d", "#50dc78", "#66ff99", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15464441", "13366221", "16636621", "13366221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_cactus_pad",
        code: 68,
        name: "icon_cactus_pad",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#29482d", "#3b663f", "#4c8452", "#61a868", "#e8f0d0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15464641", "13332221", "16232621", "13332221", "16232621",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_clay_lump",
        code: 69,
        name: "icon_clay_lump",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#553428", "#794a39", "#9c604a", "#c77a5e", "#f19472",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "16663221", "13366621", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_conveyor_left",
        code: 70,
        name: "icon_conveyor_left",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e5821", "#9c7c2e", "#c8a03c", "#ffcc4c", "#4a3410",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13326221", "13666221", "13326221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_conveyor_right",
        code: 71,
        name: "icon_conveyor_right",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e5821", "#9c7c2e", "#c8a03c", "#ffcc4c", "#4a3410",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13362221", "13366621", "13362221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_crystal_block",
        code: 72,
        name: "icon_crystal_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#533d7f", "#7657b4", "#9870e8", "#c28fff", "#f2ecff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15446441", "13362221", "13666221", "13362261", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_glass_pane",
        code: 73,
        name: "icon_glass_pane",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#63747c", "#8ca5b0", "#b4d4e2", "#e6ffff", "#ffffff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".156441.", "154..441", "13..2..1", "13.222.1", "1..2..61", "133.2661",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_gravel_pile",
        code: 74,
        name: "icon_gravel_pile",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#4b4740", "#6b655c", "#8a8276", "#b0a697", "#d5c9b6",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15464441", "13263221", "13332621", "16332221", "13362321",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_jungle_leaf",
        code: 75,
        name: "icon_jungle_leaf",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#1f5222", "#2d7530", "#3a963e", "#4ac04f", "#59e860",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332261", "13332621", "13366221", "13632221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_moss_clump",
        code: 76,
        name: "icon_moss_clump",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#27431e", "#385f2b", "#487a38", "#5c9c47", "#8ce070",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..6161..", ".165641.", "16465541", "13632221", "13332621", "13332221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_mud_ball",
        code: 77,
        name: "icon_mud_ball",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#251d16", "#352a1f", "#443628", "#574533", "#69533e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".156441.", "15444441", "13332221", "13332221", "13332221", "13362221",
                ".111611.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_mushroom_cap",
        code: 78,
        name: "icon_mushroom_cap",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#452a55", "#623c79", "#7e4e9c", "#a163c7", "#e0d4ec",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154641.", "15444441", "13362221", "16332621", "13332221", "13632221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_mushroom_stem",
        code: 79,
        name: "icon_mushroom_stem",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6c6656", "#9a917b", "#c6ba9e", "#fdeeca", "#fffff4",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13632261", "13632261", "13632261", "13632261",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_obsidian_block",
        code: 80,
        name: "icon_obsidian_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#14101c", "#1d1728", "#261e34", "#302642", "#b8a8e0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332261", "13326221", "13262221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_packed_ice",
        code: 81,
        name: "icon_packed_ice",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#526b81", "#7598b8", "#96c4ec", "#c0faff", "#f0f8ff",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154461.", "15446441", "13364221", "13632221", "16332221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_permafrost_block",
        code: 82,
        name: "icon_permafrost_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#393f44", "#515a60", "#68747c", "#85949e", "#a8d0e8",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15464441", "13332621", "13632221", "13332261", "13362221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sandstone_block",
        code: 83,
        name: "icon_sandstone_block",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#6e6042", "#9c885d", "#c8af78", "#ffe099", "#ffffba",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "16662221", "13332661", "16632221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_snow_ball",
        code: 84,
        name: "icon_snow_ball",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#818489", "#b8bbc3", "#ecf0fa", "#ffffff", "#b8c4e0",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".155441.", "15444441", "13332221", "13332261", "13632221", "13332221",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_sticky_mud",
        code: 85,
        name: "icon_sticky_mud",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#3c2c1b", "#553e27", "#6e5032", "#8c6640", "#aa7c4d",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "13332221", "13332221", "16332621",
                ".161161.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_vine_coil",
        code: 86,
        name: "icon_vine_coil",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#1f4822", "#2d6630", "#3a843e", "#4aa84f", "#59cc60",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13662221", "13326621", "13332261", "13366621",
                ".111111.",
            ],
        }]),
    },
    SpriteDef {
        id: "icon_wet_sand_pile",
        code: 87,
        name: "icon_wet_sand_pile",
        cells_w: 8,
        cells_h: 8,
        grain: 1,
        pal: &[
            ".", "#16121e", "#5c4d32", "#836d47", "#a88c5c", "#d7b375", "#ffd98e",
        ],
        fps: 8.0,
        variants: 1,
        seq: Some(&[SpriteSeq {
            state: SpriteSeqState::Idle,
            mode: SpriteSeqMode::Hold,
            fps: 0.0,
            blink_every: 0.0,
            blink_for: 0.1,
            frames: &[
                "..1111..", ".154441.", "15444441", "13332221", "13332221", "16332261", "16662661",
                ".111111.",
            ],
        }]),
    },
];

pub const SPRITE_COUNT: usize = 88;

/// id -> code. Consts, so `sprite::STONE` is a compile-time constant.
pub mod sprite {
    pub const PLAYER: u16 = 0;
    pub const ICON_BLOCK_CUBE: u16 = 1;
    pub const ICON_PICK_TRAVELER: u16 = 2;
    pub const ICON_PICK_COPPER: u16 = 3;
    pub const ICON_PICK_IRON: u16 = 4;
    pub const ICON_PICK_GOLD: u16 = 5;
    pub const ICON_PICK_GEM: u16 = 6;
    pub const ICON_SWORD_TRAVELER: u16 = 7;
    pub const ICON_SWORD_KING: u16 = 8;
    pub const ICON_BOW: u16 = 9;
    pub const ICON_SLING: u16 = 10;
    pub const ICON_ARROW: u16 = 11;
    pub const ICON_ARROW_IRON: u16 = 12;
    pub const ICON_ORE_COPPER: u16 = 13;
    pub const ICON_ORE_IRON: u16 = 14;
    pub const ICON_ORE_GOLD: u16 = 15;
    pub const ICON_COAL: u16 = 16;
    pub const ICON_BAR_COPPER: u16 = 17;
    pub const ICON_BAR_IRON: u16 = 18;
    pub const ICON_BAR_GOLD: u16 = 19;
    pub const ICON_GEM: u16 = 20;
    pub const ICON_CRYSTAL_SHARD: u16 = 21;
    pub const ICON_FLINT: u16 = 22;
    pub const ICON_FLASK_FIRE: u16 = 23;
    pub const ICON_FLASK_LIGHT: u16 = 24;
    pub const ICON_FLASK_HASTE: u16 = 25;
    pub const ICON_BANDAGE: u16 = 26;
    pub const ICON_STEW: u16 = 27;
    pub const ICON_ROAST: u16 = 28;
    pub const ICON_CAKE: u16 = 29;
    pub const ICON_TORCH: u16 = 30;
    pub const ICON_LANTERN: u16 = 31;
    pub const ICON_CAMPFIRE: u16 = 32;
    pub const ICON_LADDER: u16 = 33;
    pub const ICON_ROPE: u16 = 34;
    pub const ICON_PLATFORM: u16 = 35;
    pub const ICON_CHEST: u16 = 36;
    pub const ICON_PEARL: u16 = 37;
    pub const ICON_PEARL_SHARD: u16 = 38;
    pub const ICON_BONE: u16 = 39;
    pub const ICON_SCRAP: u16 = 40;
    pub const ICON_CORE_EMBER: u16 = 41;
    pub const ICON_CORE_FROZEN: u16 = 42;
    pub const ICON_GEL: u16 = 43;
    pub const ICON_CHITIN: u16 = 44;
    pub const ICON_HIDE: u16 = 45;
    pub const ICON_WING: u16 = 46;
    pub const ICON_DUST: u16 = 47;
    pub const ICON_SAC: u16 = 48;
    pub const ICON_MEAT: u16 = 49;
    pub const ICON_SAPLING: u16 = 50;
    pub const ICON_ANVIL: u16 = 51;
    pub const ICON_FURNACE: u16 = 52;
    pub const ICON_WORKBENCH: u16 = 53;
    pub const ICON_CHITIN_PLATE: u16 = 54;
    pub const ICON_HIDE_JERKIN: u16 = 55;
    pub const ICON_DIRT_CLOD: u16 = 56;
    pub const ICON_ICE_SHARD: u16 = 57;
    pub const ICON_SAND_PILE: u16 = 58;
    pub const ICON_STONE_CHUNK: u16 = 59;
    pub const ICON_WOOD_LOG: u16 = 60;
    pub const ICON_PEAT_CLOD: u16 = 61;
    pub const ICON_SCORIA_BLOCK: u16 = 62;
    pub const ICON_TAR_GLOB: u16 = 63;
    pub const ICON_ASH_PILE: u16 = 64;
    pub const ICON_AUTUMN_LEAF: u16 = 65;
    pub const ICON_BASALT_BLOCK: u16 = 66;
    pub const ICON_BOUNCE_PAD: u16 = 67;
    pub const ICON_CACTUS_PAD: u16 = 68;
    pub const ICON_CLAY_LUMP: u16 = 69;
    pub const ICON_CONVEYOR_LEFT: u16 = 70;
    pub const ICON_CONVEYOR_RIGHT: u16 = 71;
    pub const ICON_CRYSTAL_BLOCK: u16 = 72;
    pub const ICON_GLASS_PANE: u16 = 73;
    pub const ICON_GRAVEL_PILE: u16 = 74;
    pub const ICON_JUNGLE_LEAF: u16 = 75;
    pub const ICON_MOSS_CLUMP: u16 = 76;
    pub const ICON_MUD_BALL: u16 = 77;
    pub const ICON_MUSHROOM_CAP: u16 = 78;
    pub const ICON_MUSHROOM_STEM: u16 = 79;
    pub const ICON_OBSIDIAN_BLOCK: u16 = 80;
    pub const ICON_PACKED_ICE: u16 = 81;
    pub const ICON_PERMAFROST_BLOCK: u16 = 82;
    pub const ICON_SANDSTONE_BLOCK: u16 = 83;
    pub const ICON_SNOW_BALL: u16 = 84;
    pub const ICON_STICKY_MUD: u16 = 85;
    pub const ICON_VINE_COIL: u16 = 86;
    pub const ICON_WET_SAND_PILE: u16 = 87;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Every flat table in this module, by name. For the gates, not the game.
pub static SPRITE_TABLES: &[(&str, crate::Table)] = &[];

/// Authoring id -> code, by name. For the gates, not the game.
pub static SPRITE_CODES: &[(&str, u16)] = &[
    ("player", 0),
    ("icon_block_cube", 1),
    ("icon_pick_traveler", 2),
    ("icon_pick_copper", 3),
    ("icon_pick_iron", 4),
    ("icon_pick_gold", 5),
    ("icon_pick_gem", 6),
    ("icon_sword_traveler", 7),
    ("icon_sword_king", 8),
    ("icon_bow", 9),
    ("icon_sling", 10),
    ("icon_arrow", 11),
    ("icon_arrow_iron", 12),
    ("icon_ore_copper", 13),
    ("icon_ore_iron", 14),
    ("icon_ore_gold", 15),
    ("icon_coal", 16),
    ("icon_bar_copper", 17),
    ("icon_bar_iron", 18),
    ("icon_bar_gold", 19),
    ("icon_gem", 20),
    ("icon_crystal_shard", 21),
    ("icon_flint", 22),
    ("icon_flask_fire", 23),
    ("icon_flask_light", 24),
    ("icon_flask_haste", 25),
    ("icon_bandage", 26),
    ("icon_stew", 27),
    ("icon_roast", 28),
    ("icon_cake", 29),
    ("icon_torch", 30),
    ("icon_lantern", 31),
    ("icon_campfire", 32),
    ("icon_ladder", 33),
    ("icon_rope", 34),
    ("icon_platform", 35),
    ("icon_chest", 36),
    ("icon_pearl", 37),
    ("icon_pearl_shard", 38),
    ("icon_bone", 39),
    ("icon_scrap", 40),
    ("icon_core_ember", 41),
    ("icon_core_frozen", 42),
    ("icon_gel", 43),
    ("icon_chitin", 44),
    ("icon_hide", 45),
    ("icon_wing", 46),
    ("icon_dust", 47),
    ("icon_sac", 48),
    ("icon_meat", 49),
    ("icon_sapling", 50),
    ("icon_anvil", 51),
    ("icon_furnace", 52),
    ("icon_workbench", 53),
    ("icon_chitin_plate", 54),
    ("icon_hide_jerkin", 55),
    ("icon_dirt_clod", 56),
    ("icon_ice_shard", 57),
    ("icon_sand_pile", 58),
    ("icon_stone_chunk", 59),
    ("icon_wood_log", 60),
    ("icon_peat_clod", 61),
    ("icon_scoria_block", 62),
    ("icon_tar_glob", 63),
    ("icon_ash_pile", 64),
    ("icon_autumn_leaf", 65),
    ("icon_basalt_block", 66),
    ("icon_bounce_pad", 67),
    ("icon_cactus_pad", 68),
    ("icon_clay_lump", 69),
    ("icon_conveyor_left", 70),
    ("icon_conveyor_right", 71),
    ("icon_crystal_block", 72),
    ("icon_glass_pane", 73),
    ("icon_gravel_pile", 74),
    ("icon_jungle_leaf", 75),
    ("icon_moss_clump", 76),
    ("icon_mud_ball", 77),
    ("icon_mushroom_cap", 78),
    ("icon_mushroom_stem", 79),
    ("icon_obsidian_block", 80),
    ("icon_packed_ice", 81),
    ("icon_permafrost_block", 82),
    ("icon_sandstone_block", 83),
    ("icon_snow_ball", 84),
    ("icon_sticky_mud", 85),
    ("icon_vine_coil", 86),
    ("icon_wet_sand_pile", 87),
];
