// GENERATED by contentc — DO NOT EDIT
// 7 features from 1 source file(s):
//   content/worldgen/landmarks.toml
//
// Edit content/ and run `cargo run -p contentc`. Schemas live in
// crates/contentc/src/schemas/.

#![allow(clippy::all)]

/// Which generator in src/sim/gen/features.ts grows this. Adding one needs
/// code.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum FeatureKind {
    Island,
    Mineshaft,
    Dungeon,
    Lake,
    Geode,
    Grove,
    Oreblob,
}

impl FeatureKind {
    /// The variant a compiled code stands for, or `None` if this
    /// build has no such variant.
    #[inline]
    pub const fn from_code(code: u8) -> Option<FeatureKind> {
        Some(match code {
            0 => FeatureKind::Island,
            1 => FeatureKind::Mineshaft,
            2 => FeatureKind::Dungeon,
            3 => FeatureKind::Lake,
            4 => FeatureKind::Geode,
            5 => FeatureKind::Grove,
            6 => FeatureKind::Oreblob,
            _ => return None,
        })
    }
}

/// Which lattice offers a site: a 1D column grid for sky/surface, 2D for
/// underground.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum FeaturePlace {
    Sky,
    Surface,
    Underground,
}

impl FeaturePlace {
    /// The variant a compiled code stands for, or `None` if this
    /// build has no such variant.
    #[inline]
    pub const fn from_code(code: u8) -> Option<FeaturePlace> {
        Some(match code {
            0 => FeaturePlace::Sky,
            1 => FeaturePlace::Surface,
            2 => FeaturePlace::Underground,
            _ => return None,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FeatureMat {
    /// Outer skin: island rock, dungeon wall, geode crust, lake bed lining.
    pub shell: Option<&'static str>,
    /// Bulk interior: island soil cap, room floor, blob ore.
    pub fill: Option<&'static str>,
    /// The eye-catching bit: crystal lining, glowing cap, gilded trim.
    pub accent: Option<&'static str>,
    /// Structural timber/brick: mine supports, dungeon pillars, grove stems.
    pub frame: Option<&'static str>,
    /// What pools inside: lake water, flooded vault, geode brine.
    pub liquid: Option<&'static str>,
}

/// The compiled shape of one feature. Derived from
/// crates/contentc/src/schemas/.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FeatureDef {
    /// Stable authoring name.
    pub id: &'static str,
    /// Numeric id stored in cells and in the lock file. Never shifts.
    pub code: u16,
    /// Display name — debug HUD, map markers.
    pub name: &'static str,
    /// Which generator in src/sim/gen/features.ts grows this. Adding one needs
    /// code.
    pub kind: u8,
    /// Which lattice offers a site: a 1D column grid for sky/surface, 2D for
    /// underground.
    pub place: u8,
    /// Grid cell width in cells — the mean horizontal SPACING between
    /// instances.
    pub cell_w: i32,
    /// Grid cell height. Unread for sky/surface places, where the row is derived.
    pub cell_h: i32,
    /// Probability a grid cell actually hosts an instance. The 'is it a find?'
    /// knob.
    pub rarity: f32,
    /// Hard bound on how far the shape may extend from its origin on X. The
    /// generator clamps to it and the decorator declares it, so this is the
    /// number chunk independence rests on — see src/sim/decor/decor.ts.
    pub reach_x: i32,
    /// Hard bound on vertical extent from the origin, both directions.
    pub reach_y: i32,
    /// Primary size, drawn per instance. Half-width for a blob, length for a
    /// corridor.
    pub size: [f32; 2],
    /// Secondary size — thickness, depth, room height. Defaults to half of
    /// `size`.
    pub height: [f32; 2],
    /// For `sky` places only: cells of open air between the ground line and the
    /// feature's bottom, drawn per instance. It is a separate knob from `height`
    /// because how high something hangs and how thick it is are independent, and
    /// an island that scaled its altitude with its size would put every big one
    /// out of reach.
    pub clearance: [f32; 2],
    /// Generator-specific fill fraction: props per cell, supports per run, ore
    /// per void.
    pub density: f32,
    /// Cells below the local surface before this may appear.
    pub min_depth: i32,
    /// Last depth this may appear at. 65535 = no bound.
    pub max_depth: i32,
    /// Dominant SURFACE biome ids this may appear under (src/sim/biomes.ts).
    /// Absent = any. Plain strings for the same reason mobs use them: biomes are
    /// still hand-written and a forward ref that fails the build is worse than
    /// one that does not.
    pub biomes: Option<&'static [&'static str]>,
    /// Underground layer ids this may appear in (src/sim/biomes.ts). Absent =
    /// any.
    pub layers: Option<&'static [&'static str]>,
    pub mat: Option<FeatureMat>,
}

/// Authoring ids, index == code.
pub static FEATURE_IDS: [&str; 7] = [
    "floating_island",
    "highland_lake",
    "mineshaft",
    "vault_dungeon",
    "crystal_geode",
    "glowing_grove",
    "rich_ore_cluster",
];

/// Every def, index == code, tombstones included.
pub static FEATURES: [FeatureDef; 7] = [
    FeatureDef {
        id: "floating_island",
        code: 0,
        name: "Floating Island",
        kind: 0,
        place: 0,
        cell_w: 512,
        cell_h: 512,
        rarity: 0.5,
        reach_x: 32,
        reach_y: 26,
        size: [13.0, 30.0],
        height: [9.0, 19.0],
        clearance: [44.0, 96.0],
        density: 0.3,
        min_depth: 0,
        max_depth: 65535,
        biomes: None,
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("stone"),
            fill: Some("dirt"),
            accent: Some("crystal"),
            frame: Some("vine"),
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "highland_lake",
        code: 1,
        name: "Highland Lake",
        kind: 3,
        place: 1,
        cell_w: 420,
        cell_h: 420,
        rarity: 0.55,
        reach_x: 27,
        reach_y: 17,
        size: [11.0, 25.0],
        height: [5.0, 13.0],
        clearance: [0.0, 0.0],
        density: 0.4,
        min_depth: 0,
        max_depth: 65535,
        biomes: Some(&["plains", "savanna", "jungle", "swamp", "tundra", "glacier"]),
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("gravel"),
            fill: Some("sand"),
            accent: Some("clay"),
            frame: None,
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "mineshaft",
        code: 2,
        name: "Abandoned Mineshaft",
        kind: 1,
        place: 2,
        cell_w: 320,
        cell_h: 224,
        rarity: 0.34,
        reach_x: 88,
        reach_y: 28,
        size: [84.0, 168.0],
        height: [3.0, 4.0],
        clearance: [0.0, 0.0],
        density: 0.55,
        min_depth: 44,
        max_depth: 250,
        biomes: None,
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("stone"),
            fill: Some("gravel"),
            accent: Some("ironOre"),
            frame: Some("wood"),
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "vault_dungeon",
        code: 3,
        name: "Vault Dungeon",
        kind: 2,
        place: 2,
        cell_w: 896,
        cell_h: 416,
        rarity: 0.4,
        reach_x: 44,
        reach_y: 28,
        size: [3.0, 5.0],
        height: [2.0, 3.0],
        clearance: [0.0, 0.0],
        density: 0.45,
        min_depth: 96,
        max_depth: 360,
        biomes: None,
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("clay"),
            fill: Some("gravel"),
            accent: Some("goldOre"),
            frame: Some("stone"),
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "crystal_geode",
        code: 4,
        name: "Crystal Geode",
        kind: 4,
        place: 2,
        cell_w: 248,
        cell_h: 208,
        rarity: 0.28,
        reach_x: 19,
        reach_y: 15,
        size: [8.0, 16.0],
        height: [6.0, 12.0],
        clearance: [0.0, 0.0],
        density: 0.35,
        min_depth: 180,
        max_depth: 620,
        biomes: None,
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("obsidian"),
            fill: Some("gemOre"),
            accent: Some("crystal"),
            frame: None,
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "glowing_grove",
        code: 5,
        name: "Mushroom Grove",
        kind: 5,
        place: 2,
        cell_w: 368,
        cell_h: 288,
        rarity: 0.36,
        reach_x: 31,
        reach_y: 17,
        size: [15.0, 29.0],
        height: [7.0, 14.0],
        clearance: [0.0, 0.0],
        density: 0.5,
        min_depth: 62,
        max_depth: 300,
        biomes: None,
        layers: Some(&["fungal", "grottos", "caverns"]),
        mat: Some(FeatureMat {
            shell: Some("moss"),
            fill: Some("mud"),
            accent: Some("mushroomCap"),
            frame: Some("mushroomStem"),
            liquid: Some("water"),
        }),
    },
    FeatureDef {
        id: "rich_ore_cluster",
        code: 6,
        name: "Rich Ore Cluster",
        kind: 6,
        place: 2,
        cell_w: 152,
        cell_h: 128,
        rarity: 0.3,
        reach_x: 11,
        reach_y: 9,
        size: [4.0, 9.0],
        height: [3.0, 7.0],
        clearance: [0.0, 0.0],
        density: 0.72,
        min_depth: 56,
        max_depth: 65535,
        biomes: None,
        layers: None,
        mat: Some(FeatureMat {
            shell: Some("gravel"),
            fill: Some("ironOre"),
            accent: Some("gemOre"),
            frame: None,
            liquid: None,
        }),
    },
];

pub const FEATURE_COUNT: usize = 7;

/// id -> code. Consts, so `feature::STONE` is a compile-time constant.
pub mod feature {
    pub const FLOATING_ISLAND: u16 = 0;
    pub const HIGHLAND_LAKE: u16 = 1;
    pub const MINESHAFT: u16 = 2;
    pub const VAULT_DUNGEON: u16 = 3;
    pub const CRYSTAL_GEODE: u16 = 4;
    pub const GLOWING_GROVE: u16 = 5;
    pub const RICH_ORE_CLUSTER: u16 = 6;
}

/// Sentinel for "this threshold can never be reached".
pub const NEVER: u16 = 0xffff;

// Flat tables, index == code. Built by the compiler, not at startup:
// the sim, renderer and collision read these in per-cell loops, and an
// array read is far cheaper than a map hit plus a struct deref.

/// Generator code.
pub static FEAT_KIND: [u8; 7] = [0, 3, 1, 2, 4, 5, 6];

/// Placement class code.
pub static FEAT_PLACE: [u8; 7] = [0, 1, 2, 2, 2, 2, 2];

pub static FEAT_CELLW: [u16; 7] = [512, 420, 320, 896, 248, 368, 152];

pub static FEAT_CELLH: [u16; 7] = [512, 420, 224, 416, 208, 288, 128];

pub static FEAT_RARITY: [f32; 7] = [0.5, 0.55, 0.34, 0.4, 0.28, 0.36, 0.3];

pub static FEAT_REACHX: [u16; 7] = [32, 27, 88, 44, 19, 31, 11];

pub static FEAT_REACHY: [u16; 7] = [26, 17, 28, 28, 15, 17, 9];

/// Smallest primary size.
pub static FEAT_SIZE0: [u16; 7] = [13, 11, 84, 3, 8, 15, 4];

/// Largest primary size.
pub static FEAT_SIZE1: [u16; 7] = [30, 25, 168, 5, 16, 29, 9];

pub static FEAT_HEIGHT0: [u16; 7] = [9, 5, 3, 2, 6, 7, 3];

pub static FEAT_HEIGHT1: [u16; 7] = [19, 13, 4, 3, 12, 14, 7];

pub static FEAT_CLEAR0: [u16; 7] = [44, 0, 0, 0, 0, 0, 0];

pub static FEAT_CLEAR1: [u16; 7] = [96, 0, 0, 0, 0, 0, 0];

pub static FEAT_DENSITY: [f32; 7] = [0.3, 0.4, 0.55, 0.45, 0.35, 0.5, 0.72];

pub static FEAT_MINDEPTH: [u16; 7] = [0, 0, 44, 96, 180, 62, 56];

pub static FEAT_MAXDEPTH: [u16; 7] = [65535, 65535, 250, 360, 620, 300, 65535];

/// Every flat table in this module, by name. For the gates, not the game.
pub static FEATURE_TABLES: &[(&str, crate::Table)] = &[
    ("FEAT_KIND", crate::Table::U8(&FEAT_KIND)),
    ("FEAT_PLACE", crate::Table::U8(&FEAT_PLACE)),
    ("FEAT_CELLW", crate::Table::U16(&FEAT_CELLW)),
    ("FEAT_CELLH", crate::Table::U16(&FEAT_CELLH)),
    ("FEAT_RARITY", crate::Table::F32(&FEAT_RARITY)),
    ("FEAT_REACHX", crate::Table::U16(&FEAT_REACHX)),
    ("FEAT_REACHY", crate::Table::U16(&FEAT_REACHY)),
    ("FEAT_SIZE0", crate::Table::U16(&FEAT_SIZE0)),
    ("FEAT_SIZE1", crate::Table::U16(&FEAT_SIZE1)),
    ("FEAT_HEIGHT0", crate::Table::U16(&FEAT_HEIGHT0)),
    ("FEAT_HEIGHT1", crate::Table::U16(&FEAT_HEIGHT1)),
    ("FEAT_CLEAR0", crate::Table::U16(&FEAT_CLEAR0)),
    ("FEAT_CLEAR1", crate::Table::U16(&FEAT_CLEAR1)),
    ("FEAT_DENSITY", crate::Table::F32(&FEAT_DENSITY)),
    ("FEAT_MINDEPTH", crate::Table::U16(&FEAT_MINDEPTH)),
    ("FEAT_MAXDEPTH", crate::Table::U16(&FEAT_MAXDEPTH)),
];

/// Authoring id -> code, by name. For the gates, not the game.
pub static FEATURE_CODES: &[(&str, u16)] = &[
    ("floating_island", 0),
    ("highland_lake", 1),
    ("mineshaft", 2),
    ("vault_dungeon", 3),
    ("crystal_geode", 4),
    ("glowing_grove", 5),
    ("rich_ore_cluster", 6),
];
