//! Rendering the index to Markdown.
//!
//! Kept apart from the scan for one reason: this must be a pure function of
//! [`Index`], with no clock, no environment and no filesystem in it. `--check`
//! compares the output byte for byte against the committed page, so anything
//! non-deterministic in here — a timestamp, an absolute path, a hash map's
//! iteration order — turns the staleness gate into a coin flip that fails on
//! somebody else's machine.

use std::fmt::Write as _;

use super::Index;

pub fn page(index: &Index) -> String {
    let mut s = String::new();

    s.push_str("# Tuning index\n\n");
    s.push_str("> Generated by `cargo xtask tuning`. Do not edit — edit the source and\n");
    s.push_str("> regenerate. `cargo xtask check` fails if this page is stale.\n\n");
    s.push_str("Every tuned number in the game, by tier. `xtask/src/tuning/mod.rs` carries the\n");
    s.push_str("rule that decides which tier a number belongs to, and `rust_consts.rs` says\n");
    s.push_str("what the sweep can and cannot see.\n\n");

    table(
        &mut s,
        &["Tier", "Where", "Size", "What it describes"],
        &[
            vec![
                "1 — content".into(),
                "`content/`".into(),
                format!("{} records", index.record_count()),
                "one THING: a block, a mob, an item".into(),
            ],
            vec![
                "2 — config".into(),
                "`crates/godgame-core/src/config/`".into(),
                format!("{} constants", index.tier2_count()),
                "the WHOLE GAME: geometry, physics, worldgen".into(),
            ],
            vec![
                "3 — module".into(),
                "`crates/*/src/**`".into(),
                format!("{} constants", index.tier3_count()),
                "ONE ALGORITHM, beside the code it explains".into(),
            ],
        ],
    );

    s.push_str("\n## Tier 1 — content\n\n");
    table(
        &mut s,
        &["Directory", "Files", "Records", "Distinct fields"],
        &index
            .tier1
            .iter()
            .map(|k| {
                vec![
                    format!("`content/{}/`", k.dir),
                    k.files.to_string(),
                    k.records.to_string(),
                    k.fields.to_string(),
                ]
            })
            .collect::<Vec<_>>(),
    );
    s.push_str("\nField-by-field definitions live in `content/FORMAT.md` and the schemas under\n");
    s.push_str(
        "`crates/contentc/src/schemas/`. Numeric ids are pinned in `content/ids.lock.json`.\n",
    );

    s.push_str("\n## Tier 2 — `crates/godgame-core/src/config/`\n\n");
    s.push_str("Every `pub` item here must carry a doc comment; `cargo xtask check` fails\n");
    s.push_str("otherwise. Private constants are indexed too — they are still tuning — but\n");
    s.push_str("only the exported surface is held to the rule.\n\n");
    for domain in &index.tier2 {
        // Heading is the domain, subtitle is the path: the domain is what you
        // are looking for, the path is what you open.
        let _ = write!(s, "### `{}`\n\n`{}`\n\n", domain.module, domain.path);
        constants(&mut s, &domain.consts);
    }

    s.push_str("## Tier 3 — module constants\n\n");
    for file in &index.tier3 {
        let _ = write!(s, "### `{}`\n\n", file.path);
        constants(&mut s, &file.consts);
    }

    s
}

fn constants(s: &mut String, consts: &[super::Konst]) {
    table(
        s,
        &["Constant", "Value", "Meaning", "Line"],
        &consts
            .iter()
            .map(|k| {
                vec![
                    if k.exported {
                        format!("`{}`", k.name)
                    } else {
                        // Marked rather than dropped: it is a tuned number and
                        // belongs in the finding aid, but it is not a knob any
                        // other module can reach.
                        format!("`{}` (private)", k.name)
                    },
                    format!("`{}`", escape(&k.value)),
                    escape(&k.doc),
                    k.line.to_string(),
                ]
            })
            .collect::<Vec<_>>(),
    );
    s.push('\n');
}

fn table(s: &mut String, head: &[&str], rows: &[Vec<String>]) {
    let _ = writeln!(s, "| {} |", head.join(" | "));
    let _ = writeln!(s, "|{}|", vec!["---"; head.len()].join("|"));
    for row in rows {
        let _ = writeln!(s, "| {} |", row.join(" | "));
    }
}

/// A pipe inside a cell ends the cell. `MASK | BIT` is a real right-hand side in
/// this tree, so it has to be escaped or the row loses a column.
fn escape(s: &str) -> String {
    s.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::super::content::Kind;
    use super::super::{Domain, Konst, SourceFile};
    use super::*;

    fn sample() -> Index {
        Index {
            tier1: vec![Kind {
                dir: "blocks".into(),
                files: 8,
                records: 53,
                fields: 30,
            }],
            tier2: vec![Domain {
                module: "world".into(),
                path: "crates/godgame-core/src/config/world.rs".into(),
                consts: vec![Konst {
                    name: "CELL_SIZE".into(),
                    value: "5".into(),
                    line: 17,
                    doc: "Cellular sim geometry: px per sim cell.".into(),
                    exported: true,
                    tuned: true,
                }],
            }],
            tier3: vec![SourceFile {
                path: "crates/godgame-core/src/sim/caves.rs".into(),
                consts: vec![Konst {
                    name: "MASK".into(),
                    value: "A | B".into(),
                    line: 4,
                    doc: "Both bands at once.".into(),
                    exported: false,
                    tuned: true,
                }],
            }],
            config_names: std::collections::BTreeMap::new(),
        }
    }

    #[test]
    fn rendering_the_same_index_twice_gives_the_same_bytes() {
        // The staleness gate is byte equality, so this is the property it rests
        // on. Anything ordered by a hash map would fail here first.
        assert_eq!(page(&sample()), page(&sample()));
    }

    #[test]
    fn a_pipe_in_a_value_is_escaped_so_the_table_keeps_its_columns() {
        let out = page(&sample());
        assert!(out.contains(r"`A \| B`"), "{out}");
    }

    #[test]
    fn a_private_constant_is_indexed_and_marked_as_one() {
        assert!(page(&sample()).contains("`MASK` (private)"));
    }

    #[test]
    fn the_summary_table_reports_each_tier_count() {
        let out = page(&sample());
        assert!(out.contains("53 records"));
        assert!(out.contains("1 constants"));
    }

    #[test]
    fn every_file_and_domain_gets_its_own_heading() {
        let out = page(&sample());
        assert!(out.contains("### `world`"));
        assert!(out.contains("### `crates/godgame-core/src/sim/caves.rs`"));
    }
}
