//! Code generation: content records -> `godgame-data/src/<kind>.rs`.
//!
//! Three jobs, in order:
//!  1. assign stable numeric codes through `content/ids.lock.json` (FORMAT.md §4);
//!  2. validate every record against the schema, now that the id set is known,
//!     so `ref(block)` can be checked at compile time;
//!  3. print a deterministic Rust module (FORMAT.md §5) — sorted by code, no
//!     timestamps, no hash-map iteration order — so a rebuild that changed
//!     nothing produces a byte-identical file and `--check` means something.
//!
//! The output depends only on `bitflags`, so it can be linked by the sim, the
//! renderer, the benches and the xtask gates without dragging anything with it.
//!
//! Where the TS emitter wrote TypeScript, this writes Rust, and three things get
//! better in the translation: a string-union `enum` becomes a real `enum`, a
//! const-object bit set becomes `bitflags!`, and a base64 pair matrix becomes a
//! packed byte array with an inline accessor — no runtime inflation at all.

use crate::error::Result;
use crate::lock::{KindLock, Lock};
use crate::names;
use crate::parser::{FieldMap, RawRecord, RawValue};
use crate::schema::{ArrayKind, Field, Schema, TableCtx, TypeNode, parse_type};
use crate::value::{Def, Value};
use crate::{bail, err};
use std::collections::{HashMap, HashSet};
use std::rc::Rc;

pub struct EmitResult {
    /// The generated Rust module source.
    pub source: String,
    /// The lock as it should be on disk after this compile.
    pub lock: Lock,
    pub warnings: Vec<String>,
    pub count: usize,
    pub tombstones: Vec<String>,
}

const GEN_HEADER: &str = "// GENERATED by contentc — DO NOT EDIT";

// ---------------------------------------------------------------------------
// Code assignment
// ---------------------------------------------------------------------------

struct Assignment {
    codes: HashMap<String, u32>,
    next_lock: KindLock,
    tombstones: Vec<String>,
}

/// Give every id a code: locked ids keep theirs forever, new ids take the lowest
/// free slot, and locked ids that vanished from `content/` stay reserved as
/// tombstones. This is the invariant that lets a saved chunk survive a content
/// edit, so it is deliberately the least clever code in the compiler.
fn assign_codes(kind: &str, ids: &[String], lock: &Lock) -> Assignment {
    let prior = lock.kind(kind);
    let mut codes: HashMap<String, u32> = HashMap::new();
    let mut used: HashSet<u32> = HashSet::new();

    for id in ids {
        if let Some((_, c)) = prior.iter().find(|(k, _)| k == id) {
            codes.insert(id.clone(), *c);
            used.insert(*c);
        }
    }
    for (id, c) in prior {
        if !codes.contains_key(id) {
            used.insert(*c); // tombstone: the code stays reserved
        }
    }

    let mut next = 0u32;
    for id in ids {
        if codes.contains_key(id) {
            continue;
        }
        while used.contains(&next) {
            next += 1;
        }
        codes.insert(id.clone(), next);
        used.insert(next);
    }

    let mut tombstones: Vec<String> = prior
        .iter()
        .filter(|(id, _)| !codes.contains_key(id))
        .map(|(id, _)| id.clone())
        .collect();
    tombstones.sort();

    let mut next_lock: KindLock = codes.iter().map(|(id, c)| (id.clone(), *c)).collect();
    for t in &tombstones {
        let c = prior
            .iter()
            .find(|(k, _)| k == t)
            .map(|(_, c)| *c)
            .unwrap_or(0);
        next_lock.push((t.clone(), c));
    }
    // Sort by code, then id, so two ids can never swap places between runs.
    next_lock.sort_by(|a, b| a.1.cmp(&b.1).then_with(|| a.0.cmp(&b.0)));

    Assignment {
        codes,
        next_lock,
        tombstones,
    }
}

/// Assign one kind's codes without compiling it, so the driver can build a lock
/// covering EVERY kind before any kind emits a table. That is what makes
/// `TableCtx::foreign_code` well-defined in both directions: an item table can
/// ask for a block code and a block table for an item code, with no compile
/// order that satisfies one at the other's expense.
///
/// Idempotent, and it is the same function `compile` runs, so the codes it hands
/// out here are exactly the ones the real compile will use.
pub fn assign_kind_codes(kind: &str, ids: &[String], lock: &Lock) -> KindLock {
    let mut unique: Vec<String> = Vec::new();
    let mut seen: HashSet<&str> = HashSet::new();
    for id in ids {
        if seen.insert(id.as_str()) {
            unique.push(id.clone());
        }
    }
    assign_codes(kind, &unique, lock).next_lock
}

// ---------------------------------------------------------------------------
// Compile
// ---------------------------------------------------------------------------

/// Ids of every kind, so a `ref(item)` inside a `.block` can be checked at
/// compile time. Collected by a parse-only pre-pass in the driver, because kinds
/// reference each other in both directions (a block drops an item; an item
/// places a block) and no single compile order can satisfy that.
pub type Foreign = HashMap<String, HashSet<String>>;

pub fn compile(
    schema: &Schema,
    records: &[RawRecord],
    lock: &Lock,
    sources: &[String],
    foreign: &Foreign,
) -> Result<EmitResult> {
    let mut seen: Vec<(String, &RawRecord)> = Vec::new();
    for rec in records {
        if rec.kind != schema.kind {
            bail!(&rec.loc, "expected @{}, got @{}", schema.kind, rec.kind);
        }
        if let Some((_, dup)) = seen.iter().find(|(id, _)| *id == rec.id) {
            bail!(
                &rec.loc,
                "duplicate {} '{}' (also at {})",
                schema.kind,
                rec.id,
                dup.loc
            );
        }
        seen.push((rec.id.clone(), rec));
    }

    let ids: Vec<String> = seen.iter().map(|(id, _)| id.clone()).collect();
    let Assignment {
        mut codes,
        next_lock,
        tombstones,
    } = assign_codes(&schema.kind, &ids, lock);
    for t in &tombstones {
        let c = next_lock
            .iter()
            .find(|(k, _)| k == t)
            .map(|(_, c)| *c)
            .unwrap_or(0);
        codes.insert(t.clone(), c);
    }

    // The schema's own kind resolves against the ids it is compiling; every
    // other kind against the pre-pass registry.
    let mut registries: Foreign = foreign.clone();
    registries.insert(schema.kind.clone(), codes.keys().cloned().collect());
    let ctx = crate::schema::ResolveCtx::new(&registries);

    // A kind with no content yet is legal (the directory is added before the
    // records are), and must not take the max of an empty list.
    let count = codes.values().copied().max().map_or(0, |m| m as usize + 1);
    let mut defs: Vec<Option<Def>> = vec![None; count];

    for (id, rec) in &seen {
        let mut def = crate::schema::resolve_record(schema, rec, &ctx)?;
        let code = codes[id];
        def.insert("code", Value::Int(code as i64));
        defs[code as usize] = Some(def);
    }
    for (c, slot) in defs.iter_mut().enumerate() {
        if slot.is_some() {
            continue;
        }
        let id = tombstones
            .iter()
            .find(|t| {
                next_lock
                    .iter()
                    .any(|(k, code)| k == *t && *code as usize == c)
            })
            .cloned()
            .unwrap_or_else(|| format!("_reserved{c}"));
        let rec = tombstone_record(schema, &id);
        let mut def = crate::schema::resolve_record(schema, &rec, &ctx)?;
        def.insert("code", Value::Int(c as i64));
        *slot = Some(def);
    }
    let defs: Vec<Def> = defs.into_iter().map(Option::unwrap).collect();

    let mut bits: HashMap<String, HashMap<String, u32>> = HashMap::new();
    for set in &schema.constants {
        if set.values.len() > 32 {
            bail!("{} exceeds 32 bits", set.name);
        }
        bits.insert(
            set.name.clone(),
            set.values
                .iter()
                .enumerate()
                .map(|(i, v)| (v.clone(), i as u32))
                .collect(),
        );
    }

    // Reads the lock rather than a compiled registry, which is what makes this
    // order-free: the driver has already assigned every kind's codes into the
    // lock, so a table can reach any kind regardless of which compiles first.
    let mut foreign_codes: HashMap<String, HashMap<String, u32>> = HashMap::new();
    for kind in foreign.keys() {
        foreign_codes.insert(
            kind.clone(),
            lock.kind(kind).iter().cloned().collect::<HashMap<_, _>>(),
        );
    }
    let tctx = TableCtx::new(&codes, &foreign_codes, &bits);

    let source = print(schema, &defs, count, &tctx, sources, &tombstones)?;
    if let Some(e) = tctx.take_error() {
        return Err(e);
    }

    let mut out_lock = lock.clone();
    out_lock.set_kind(&schema.kind, next_lock);

    Ok(EmitResult {
        source,
        lock: out_lock,
        warnings: ctx.into_warnings(),
        count,
        tombstones,
    })
}

fn tombstone_record(schema: &Schema, id: &str) -> RawRecord {
    let loc = crate::error::Loc {
        file: Rc::from("<tombstone>"),
        line: 0,
    };
    let mut fields = FieldMap::default();
    for (k, v) in &schema.tombstone {
        let text = if v.starts_with('"') && v.ends_with('"') && v.len() >= 2 {
            v[1..v.len() - 1].to_string()
        } else {
            v.clone()
        };
        fields.push(
            k,
            RawValue {
                text: Some(text),
                lines: None,
                loc: loc.clone(),
            },
        );
    }
    RawRecord {
        kind: schema.kind.clone(),
        id: id.to_string(),
        loc,
        fields,
    }
}

// ---------------------------------------------------------------------------
// Rust type rendering (the emitted struct is derived, never written)
// ---------------------------------------------------------------------------

/// Field name paired with its descriptor, borrowed from the schema.
type FieldRef<'a> = (&'a str, &'a Field);
/// A dotted group: its name and its leaf fields, in declaration order.
type GroupRef<'a> = (&'a str, Vec<FieldRef<'a>>);

/// Split a schema's dotted fields into top-level fields and named groups.
fn partition(schema: &Schema) -> (Vec<FieldRef<'_>>, Vec<GroupRef<'_>>) {
    let mut flat: Vec<(&str, &Field)> = Vec::new();
    let mut groups: Vec<(&str, Vec<(&str, &Field)>)> = Vec::new();
    for (key, field) in &schema.fields {
        match key.find('.') {
            None => flat.push((key.as_str(), field)),
            Some(i) => {
                let g = &key[..i];
                let leaf = &key[i + 1..];
                match groups.iter_mut().find(|(name, _)| *name == g) {
                    Some((_, v)) => v.push((leaf, field)),
                    None => groups.push((g, vec![(leaf, field)])),
                }
            }
        }
    }
    (flat, groups)
}

/// The name of the Rust enum a non-mapped `enum(...)` field becomes.
///
/// `scope` is the struct the field belongs to — the schema's `iface_prefix` for
/// a top-level or group field, the element name for a `record[]` sub-field — so
/// two unrelated `mode` fields cannot collide.
fn enum_name(scope: &str, key: &str, field: &Field) -> String {
    match &field.alias {
        Some(a) => a.clone(),
        None => format!("{scope}{}", names::pascal(key)),
    }
}

/// The integer type a `map`ped enum resolves to.
fn mapped_int_type(field: &Field) -> &'static str {
    let fits = field
        .map
        .as_ref()
        .is_some_and(|m| m.iter().all(|(_, v)| (0..=255).contains(v)));
    if fits { "u8" } else { "i32" }
}

fn rust_type(scope: &str, key: &str, field: &Field) -> Result<String> {
    if field.map.is_some() {
        return Ok(mapped_int_type(field).to_string());
    }
    rust_type_of(&parse_type(&field.ty)?, scope, key, field)
}

fn rust_type_of(node: &TypeNode, scope: &str, key: &str, field: &Field) -> Result<String> {
    Ok(match node {
        TypeNode::Int => "i32".into(),
        TypeNode::Float | TypeNode::Chance => "f32".into(),
        TypeNode::Bool => "bool".into(),
        TypeNode::Str | TypeNode::Ref { .. } => "&'static str".into(),
        TypeNode::Enum(_) => enum_name(scope, key, field),
        TypeNode::Color => "[u8; 3]".into(),
        TypeNode::Range => "[f32; 2]".into(),
        TypeNode::Text => "&'static [&'static str]".into(),
        TypeNode::List(of) => {
            format!("&'static [{}]", rust_type_of(of, scope, key, field)?)
        }
        TypeNode::Record => {
            let elem = field
                .element
                .clone()
                .ok_or_else(|| err!("'{key}' is record[] but names no element struct"))?;
            format!("&'static [{elem}]")
        }
    })
}

/// A field is `Option<T>` when nothing guarantees it a value.
fn is_optional(field: &Field) -> bool {
    !(field.required || field.default.is_some())
}

// ---------------------------------------------------------------------------
// Literals
// ---------------------------------------------------------------------------

fn str_lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn f32_lit(v: f64) -> String {
    let f = v as f32;
    if f.is_infinite() {
        return if f > 0.0 {
            "f32::INFINITY".into()
        } else {
            "f32::NEG_INFINITY".into()
        };
    }
    if f.is_nan() {
        return "f32::NAN".into();
    }
    // Debug for floats is the shortest round-tripping form and always carries a
    // `.` or an exponent, so it is a valid float literal on its own.
    format!("{f:?}")
}

/// One table slot. Integer arrays reject a value that would not survive the
/// store, rather than wrapping the way a JS typed array silently would.
fn table_lit(kind: ArrayKind, v: f64, table: &str, code: usize) -> Result<String> {
    if kind == ArrayKind::F32 {
        return Ok(f32_lit(v));
    }
    let max = match kind {
        ArrayKind::U8 => 255.0,
        ArrayKind::U16 => 65535.0,
        ArrayKind::U32 => 4294967295.0,
        ArrayKind::F32 => unreachable!(),
    };
    if !v.is_finite() || v.fract() != 0.0 || v < 0.0 || v > max {
        bail!(
            "{table}[{code}] = {v} does not fit a {} — a table's array kind and its \
             callback disagree",
            kind.rust_elem()
        );
    }
    Ok(format!("{}", v as u64))
}

fn value_lit(node: &TypeNode, field: &Field, scope: &str, key: &str, v: &Value) -> Result<String> {
    Ok(match (node, v) {
        (TypeNode::Enum(_), Value::Int(n)) => format!("{n}"),
        (TypeNode::Enum(_), Value::Str(s)) => {
            format!("{}::{}", enum_name(scope, key, field), names::pascal(s))
        }
        (TypeNode::Int, Value::Int(n)) => format!("{n}"),
        (TypeNode::Int, Value::Float(f)) => format!("{}", *f as i64),
        (TypeNode::Float | TypeNode::Chance, v) => {
            f32_lit(v.as_num().ok_or_else(|| err!("'{key}' is not numeric"))?)
        }
        (TypeNode::Bool, Value::Bool(b)) => format!("{b}"),
        (TypeNode::Str | TypeNode::Ref { .. }, Value::Str(s)) => str_lit(s),
        (TypeNode::Color, Value::Color(c)) => format!("[{}, {}, {}]", c[0], c[1], c[2]),
        (TypeNode::Range, Value::Range(a, b)) => format!("[{}, {}]", f32_lit(*a), f32_lit(*b)),
        (TypeNode::Text, Value::Text(lines)) => {
            let parts: Vec<String> = lines.iter().map(|l| str_lit(l)).collect();
            format!("&[{}]", parts.join(", "))
        }
        (TypeNode::List(of), Value::List(items)) => {
            let mut parts = Vec::with_capacity(items.len());
            for it in items {
                parts.push(value_lit(of, field, scope, key, it)?);
            }
            format!("&[{}]", parts.join(", "))
        }
        (TypeNode::Record, Value::Records(rows)) => {
            let elem = field
                .element
                .clone()
                .ok_or_else(|| err!("'{key}' is record[] but names no element struct"))?;
            let subs = field
                .fields
                .as_ref()
                .ok_or_else(|| err!("'{key}' is record[] but declares no fields"))?;
            let mut parts = Vec::with_capacity(rows.len());
            for row in rows {
                let mut inner = Vec::with_capacity(subs.len());
                for (sk, sf) in subs {
                    let snode = parse_type(&sf.ty)?;
                    let lit = match row.get(sk) {
                        Some(val) => {
                            let l = value_lit(&snode, sf, &elem, sk, val)?;
                            if is_optional(sf) {
                                format!("Some({l})")
                            } else {
                                l
                            }
                        }
                        None if is_optional(sf) => "None".to_string(),
                        None => bail!("'{key}.{sk}' has no value and is not optional"),
                    };
                    inner.push(format!("{}: {lit}", names::snake(sk)));
                }
                parts.push(format!("{elem} {{ {} }}", inner.join(", ")));
            }
            format!("&[{}]", parts.join(", "))
        }
        (n, v) => {
            bail!("'{key}': cannot render a {} as {n:?}", v.type_name())
        }
    })
}

// ---------------------------------------------------------------------------
// Printing
// ---------------------------------------------------------------------------

/// Wrap prose to a `///` doc comment at the given indent.
fn doc(text: Option<&String>, indent: &str) -> Vec<String> {
    let Some(text) = text else { return Vec::new() };
    if text.is_empty() {
        return Vec::new();
    }
    let mut lines: Vec<String> = Vec::new();
    let mut line = String::new();
    for w in text.split_whitespace() {
        if !line.is_empty() && line.len() + w.len() + 1 > 74 {
            lines.push(std::mem::take(&mut line));
            line.push_str(w);
        } else {
            if !line.is_empty() {
                line.push(' ');
            }
            line.push_str(w);
        }
    }
    if !line.is_empty() {
        lines.push(line);
    }
    lines
        .into_iter()
        .map(|l| format!("{indent}/// {l}"))
        .collect()
}

/// Wrap a comma-separated list so diffs stay narrow.
fn wrap(items: &[String], indent: &str) -> String {
    let mut lines: Vec<String> = Vec::new();
    let mut line = indent.to_string();
    for (i, item) in items.iter().enumerate() {
        let piece = format!("{item}{}", if i == items.len() - 1 { "" } else { "," });
        if line.len() + piece.len() + 1 > 92 && line != indent {
            lines.push(std::mem::take(&mut line));
            line.push_str(indent);
        }
        if line != indent {
            line.push(' ');
        }
        line.push_str(&piece);
    }
    if line != indent {
        lines.push(line);
    }
    lines.join("\n")
}

/// One generated enum: its Rust name, its variants in order, and its doc.
type EnumDecl = (String, Vec<String>, Option<String>);

/// Every enum a schema needs declared, in declaration order, deduplicated.
fn collect_enums(schema: &Schema) -> Result<Vec<EnumDecl>> {
    let (flat, groups) = partition(schema);
    let mut out: Vec<EnumDecl> = Vec::new();
    let mut push = |name: String, values: Vec<String>, d: Option<String>| -> Result<()> {
        if let Some((_, existing, _)) = out.iter().find(|(n, _, _)| *n == name) {
            if *existing != values {
                bail!("two different enums are both named '{name}'");
            }
            return Ok(());
        }
        out.push((name, values, d));
        Ok(())
    };

    let walk = |scope: &str, key: &str, field: &Field| -> Result<Vec<EnumDecl>> {
        let mut found = Vec::new();
        let mut node = parse_type(&field.ty)?;
        while let TypeNode::List(of) = node {
            node = *of;
        }
        if let TypeNode::Enum(values) = node
            && field.map.is_none()
        {
            found.push((enum_name(scope, key, field), values, field.doc.clone()));
        }
        Ok(found)
    };

    let mut all: Vec<(&str, &str, &Field)> = Vec::new();
    for (k, f) in &flat {
        all.push((schema.iface_prefix.as_str(), k, f));
    }
    for (_, fields) in &groups {
        for (k, f) in fields {
            all.push((schema.iface_prefix.as_str(), k, f));
        }
    }

    for (scope, key, field) in &all {
        for e in walk(scope, key, field)? {
            push(e.0, e.1, e.2)?;
        }
        // `record[]` sub-fields carry enums too — `mode` and `state` on a sprite
        // sequence — and they are scoped to the element struct.
        if let (Some(elem), Some(subs)) = (&field.element, &field.fields) {
            for (sk, sf) in subs {
                for e in walk(elem, sk, sf)? {
                    push(e.0, e.1, e.2)?;
                }
            }
        }
    }
    Ok(out)
}

fn print(
    schema: &Schema,
    defs: &[Def],
    count: usize,
    tctx: &TableCtx,
    sources: &[String],
    tombstones: &[String],
) -> Result<String> {
    let (flat, groups) = partition(schema);
    let mut out: Vec<String> = Vec::new();
    let p = &schema.prefix;

    out.push(GEN_HEADER.to_string());
    out.push(format!(
        "// {count} {}s from {} source file(s):",
        schema.kind,
        sources.len()
    ));
    for s in sources {
        out.push(format!("//   {s}"));
    }
    if !tombstones.is_empty() {
        out.push(format!("// tombstoned: {}", tombstones.join(", ")));
    }
    out.push("//".to_string());
    out.push("// Edit content/ and run `cargo run -p contentc`. Schemas live in".to_string());
    out.push("// crates/contentc/src/schemas/.".to_string());
    out.push(String::new());
    out.push("#![allow(clippy::all)]".to_string());
    out.push(String::new());

    // --- named enums ---------------------------------------------------------
    let enums = collect_enums(schema)?;
    for (name, values, d) in &enums {
        out.extend(doc(d.as_ref(), ""));
        out.push("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]".to_string());
        out.push("#[repr(u8)]".to_string());
        out.push(format!("pub enum {name} {{"));
        for v in values {
            out.push(format!("    {},", names::pascal(v)));
        }
        out.push("}".to_string());
        out.push(String::new());
    }

    // --- element structs -----------------------------------------------------
    //
    // Grouped fields are walked too, not just flat ones: `art.seq` is a
    // `record[]` living under the `art` group, and the group struct below
    // renders it as `&[MobSpecSeq]`, so skipping groups here emits a module that
    // references a type it never declares. The dedupe is not theoretical — two
    // fields may legitimately share one element shape by naming the same
    // element, and a repeated `pub struct` is a hard error.
    let mut elements: Vec<&str> = Vec::new();
    let mut all_fields: Vec<(&str, &Field)> = flat.clone();
    for (_, fields) in &groups {
        all_fields.extend(fields.iter().copied());
    }
    for (_, field) in &all_fields {
        let (Some(elem), Some(subs)) = (&field.element, &field.fields) else {
            continue;
        };
        if elements.contains(&elem.as_str()) {
            continue;
        }
        elements.push(elem.as_str());
        out.push("#[derive(Clone, Copy, Debug, PartialEq)]".to_string());
        out.push(format!("pub struct {elem} {{"));
        for (sk, sf) in subs {
            out.extend(doc(sf.doc.as_ref(), "    "));
            let t = rust_type(elem, sk, sf)?;
            let t = if is_optional(sf) {
                format!("Option<{t}>")
            } else {
                t
            };
            out.push(format!("    pub {}: {t},", names::snake(sk)));
        }
        out.push("}".to_string());
        out.push(String::new());
    }

    // --- group structs -------------------------------------------------------
    for (name, fields) in &groups {
        out.push("#[derive(Clone, Copy, Debug, PartialEq)]".to_string());
        out.push(format!(
            "pub struct {}{} {{",
            schema.iface_prefix,
            names::pascal(name)
        ));
        for (k, sf) in fields {
            out.extend(doc(sf.doc.as_ref(), "    "));
            let t = rust_type(&schema.iface_prefix, k, sf)?;
            // A group's sub-field defaults are NOT injected when the group is
            // absent, so only `required` makes one non-optional.
            let t = if sf.required {
                t
            } else {
                format!("Option<{t}>")
            };
            out.push(format!("    pub {}: {t},", names::snake(k)));
        }
        out.push("}".to_string());
        out.push(String::new());
    }

    // --- the def struct ------------------------------------------------------
    out.extend(doc(
        Some(&format!(
            "The compiled shape of one {}. Derived from crates/contentc/src/schemas/.",
            schema.kind
        )),
        "",
    ));
    out.push("#[derive(Clone, Copy, Debug, PartialEq)]".to_string());
    out.push(format!("pub struct {} {{", schema.iface));
    out.push("    /// Stable authoring name.".to_string());
    out.push("    pub id: &'static str,".to_string());
    out.push("    /// Numeric id stored in cells and in the lock file. Never shifts.".to_string());
    out.push("    pub code: u16,".to_string());
    let mut emitted: Vec<&str> = Vec::new();
    for (key, field) in &schema.fields {
        match key.find('.') {
            None => {
                out.extend(doc(field.doc.as_ref(), "    "));
                let t = rust_type(&schema.iface_prefix, key, field)?;
                let t = if is_optional(field) {
                    format!("Option<{t}>")
                } else {
                    t
                };
                out.push(format!("    pub {}: {t},", names::snake(key)));
            }
            Some(i) => {
                let g = &key[..i];
                if emitted.contains(&g) {
                    continue;
                }
                emitted.push(g);
                out.push(format!(
                    "    pub {}: Option<{}{}>,",
                    names::snake(g),
                    schema.iface_prefix,
                    names::pascal(g)
                ));
            }
        }
    }
    out.push("}".to_string());
    out.push(String::new());

    // --- registry ------------------------------------------------------------
    out.push("/// Authoring ids, index == code.".to_string());
    out.push(format!("pub static {p}_IDS: [&str; {count}] = ["));
    out.push(wrap(
        &defs
            .iter()
            .map(|d| str_lit(d.str_of("id")))
            .collect::<Vec<_>>(),
        "    ",
    ));
    out.push("];".to_string());
    out.push(String::new());

    out.push("/// Every def, index == code, tombstones included.".to_string());
    out.push(format!(
        "pub static {}S: [{}; {count}] = [",
        p, schema.iface
    ));
    for d in defs {
        out.push(format!("    {},", def_literal(d, schema)?));
    }
    out.push("];".to_string());
    out.push(String::new());

    out.push(format!("pub const {p}_COUNT: usize = {count};"));
    out.push(String::new());

    let idmod = names::snake(&schema.prefix.to_ascii_lowercase());
    out.push(format!(
        "/// id -> code. Consts, so `{idmod}::STONE` is a compile-time constant."
    ));
    out.push(format!("pub mod {idmod} {{"));
    let mut const_names: Vec<String> = Vec::new();
    for d in defs {
        let id = d.str_of("id");
        let n = names::screaming_snake(id);
        if const_names.contains(&n) {
            bail!(
                "two {} ids collapse to the Rust constant '{n}'",
                schema.kind
            );
        }
        const_names.push(n.clone());
        out.push(format!(
            "    pub const {n}: u16 = {};",
            d.num("code") as u64
        ));
    }
    out.push("}".to_string());
    out.push(String::new());

    out.push("/// Sentinel for \"this threshold can never be reached\".".to_string());
    out.push("pub const NEVER: u16 = 0xffff;".to_string());
    out.push(String::new());

    // --- bit constants -------------------------------------------------------
    for set in &schema.constants {
        out.push("bitflags::bitflags! {".to_string());
        out.extend(doc(set.doc.as_ref(), "    "));
        out.push("    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]".to_string());
        out.push(format!(
            "    pub struct {}: u32 {{",
            names::pascal(&set.name)
        ));
        for (i, v) in set.values.iter().enumerate() {
            out.push(format!(
                "        const {} = 1 << {i};",
                names::screaming_snake(v)
            ));
        }
        out.push("    }".to_string());
        out.push("}".to_string());
        out.push(String::new());
    }

    // --- flat tables ---------------------------------------------------------
    out.push("// Flat tables, index == code. Built by the compiler, not at startup:".to_string());
    out.push("// the sim, renderer and collision read these in per-cell loops, and an".to_string());
    out.push("// array read is far cheaper than a map hit plus a struct deref.".to_string());
    out.push(String::new());
    for t in schema.hot_arrays() {
        let mut values = Vec::with_capacity(count);
        for (code, d) in defs.iter().enumerate() {
            let v = (t.value)(d, tctx).unwrap_or(t.fill);
            values.push(table_lit(t.array, v, &t.name, code)?);
        }
        // A callback cannot return an error through `Option<f64>`, so a bad
        // `bit()` lookup is stashed and surfaces here, naming the table.
        if let Some(e) = tctx.take_error() {
            return Err(err!("{}: {}", t.name, e.message));
        }
        out.extend(doc(t.doc.as_ref(), ""));
        out.push(format!(
            "pub static {}: [{}; {count}] = [",
            t.name,
            t.array.rust_elem()
        ));
        out.push(wrap(&values, "    "));
        out.push("];".to_string());
        out.push(String::new());
    }

    // --- pair matrices -------------------------------------------------------
    //
    // One bit per pair, packed. The TS build base64'd this and inflated it at
    // module init to keep the bundle small; a Rust static array costs nothing at
    // runtime, so the accessor reads the packed bytes directly.
    for m in &schema.matrices {
        let n = count * count;
        let mut packed = vec![0u8; n.div_ceil(8)];
        for d in defs {
            let Some(row) = (m.row)(d, tctx) else {
                continue;
            };
            for target in row {
                let i = d.num("code") as usize * count + tctx.code(&target) as usize;
                packed[i >> 3] |= 1 << (i & 7);
            }
        }
        let fname = names::snake(&m.name);
        out.extend(doc(m.doc.as_ref(), ""));
        out.push(format!(
            "pub static {}_BITS: [u8; {}] = [",
            m.name,
            packed.len()
        ));
        out.push(wrap(
            &packed.iter().map(|b| b.to_string()).collect::<Vec<_>>(),
            "    ",
        ));
        out.push("];".to_string());
        out.push(String::new());
        out.push(format!(
            "/// `true` when the `{}` pair matrix has the (a, b) bit set.",
            m.name
        ));
        out.push("#[inline]".to_string());
        out.push(format!("pub fn {fname}(a: u16, b: u16) -> bool {{"));
        out.push(format!("    let i = a as usize * {count} + b as usize;"));
        out.push(format!(
            "    i < {n} && ({}_BITS[i >> 3] >> (i & 7)) & 1 != 0",
            m.name
        ));
        out.push("}".to_string());
        out.push(String::new());
    }

    // --- reflection registries -----------------------------------------------
    //
    // Rust cannot look a static up by name, and two consumers need to: the
    // parity test that diffs these tables against the TypeScript build, and the
    // tuning index. Emitting the registry is cheaper than either of them
    // restating 79 table names by hand and drifting.
    out.push(
        "/// Every flat table in this module, by name. For the gates, not the game.".to_string(),
    );
    out.push(format!(
        "pub static {p}_TABLES: &[(&str, crate::Table)] = &["
    ));
    for t in schema.hot_arrays() {
        let variant = match t.array {
            ArrayKind::U8 => "U8",
            ArrayKind::U16 => "U16",
            ArrayKind::U32 => "U32",
            ArrayKind::F32 => "F32",
        };
        out.push(format!(
            "    (\"{}\", crate::Table::{variant}(&{})),",
            t.name, t.name
        ));
    }
    out.push("];".to_string());
    out.push(String::new());

    out.push("/// Authoring id -> code, by name. For the gates, not the game.".to_string());
    out.push(format!("pub static {p}_CODES: &[(&str, u16)] = &["));
    for d in defs {
        out.push(format!(
            "    (\"{}\", {}),",
            d.str_of("id"),
            d.num("code") as u64
        ));
    }
    out.push("];".to_string());
    out.push(String::new());

    if !schema.matrices.is_empty() {
        out.push(
            "/// Every pair matrix in this module: name, side length, packed bits.".to_string(),
        );
        out.push(format!(
            "pub static {p}_MATRICES: &[(&str, usize, &[u8])] = &["
        ));
        for m in &schema.matrices {
            out.push(format!("    (\"{}\", {count}, &{}_BITS),", m.name, m.name));
        }
        out.push("];".to_string());
        out.push(String::new());
    }

    let joined = out.join("\n");
    let mut text = collapse_blank_runs(&joined);
    while text.ends_with('\n') {
        text.pop();
    }
    text.push('\n');
    Ok(text)
}

/// `/\n{3,}/g -> "\n\n"` — three or more newlines collapse to one blank line.
fn collapse_blank_runs(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut run = 0usize;
    for c in s.chars() {
        if c == '\n' {
            run += 1;
            if run <= 2 {
                out.push(c);
            }
            continue;
        }
        run = 0;
        out.push(c);
    }
    out
}

/// One def as a struct literal, fields in schema order, defaults included.
fn def_literal(d: &Def, schema: &Schema) -> Result<String> {
    let mut parts: Vec<String> = vec![
        format!("id: {}", str_lit(d.str_of("id"))),
        format!("code: {}", d.num("code") as u64),
    ];
    let mut emitted: Vec<String> = vec!["id".into(), "code".into()];

    for (key, field) in &schema.fields {
        let name = match key.find('.') {
            None => key.clone(),
            Some(i) => key[..i].to_string(),
        };
        if emitted.contains(&name) {
            continue;
        }
        emitted.push(name.clone());

        if name != *key {
            // A group: emit the whole nested struct, or None.
            let group_fields: Vec<(&str, &Field)> = schema
                .fields
                .iter()
                .filter(|(k, _)| k.starts_with(&format!("{name}.")))
                .map(|(k, f)| (&k[name.len() + 1..], f))
                .collect();
            let lit = match d.get(&name) {
                Some(Value::Group(g)) => {
                    let mut inner = Vec::with_capacity(group_fields.len());
                    for (leaf, sf) in &group_fields {
                        let snode = parse_type(&sf.ty)?;
                        let l = match g.get(leaf) {
                            Some(v) => {
                                let raw = value_lit(&snode, sf, &schema.iface_prefix, leaf, v)?;
                                if sf.required {
                                    raw
                                } else {
                                    format!("Some({raw})")
                                }
                            }
                            None if !sf.required => "None".to_string(),
                            None => bail!(
                                "{} '{}' group '{name}' is missing required '{leaf}'",
                                schema.kind,
                                d.str_of("id")
                            ),
                        };
                        inner.push(format!("{}: {l}", names::snake(leaf)));
                    }
                    format!(
                        "Some({}{} {{ {} }})",
                        schema.iface_prefix,
                        names::pascal(&name),
                        inner.join(", ")
                    )
                }
                _ => "None".to_string(),
            };
            parts.push(format!("{}: {lit}", names::snake(&name)));
            continue;
        }

        let node = parse_type(&field.ty)?;
        let lit = match d.get(&name) {
            Some(v) => {
                let raw = value_lit(&node, field, &schema.iface_prefix, &name, v)?;
                if is_optional(field) {
                    format!("Some({raw})")
                } else {
                    raw
                }
            }
            None if is_optional(field) => "None".to_string(),
            None => bail!(
                "{} '{}' is missing '{name}', which is neither optional nor defaulted",
                schema.kind,
                d.str_of("id")
            ),
        };
        parts.push(format!("{}: {lit}", names::snake(&name)));
    }

    Ok(format!("{} {{ {} }}", schema.iface, parts.join(", ")))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lock_with(kind: &str, entries: &[(&str, u32)]) -> Lock {
        let mut l = Lock::default();
        l.set_kind(
            kind,
            entries.iter().map(|(a, b)| (a.to_string(), *b)).collect(),
        );
        l
    }

    fn ids(v: &[&str]) -> Vec<String> {
        v.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn a_locked_id_keeps_its_code_forever() {
        let lock = lock_with("block", &[("air", 0), ("stone", 1), ("dirt", 2)]);
        let a = assign_codes("block", &ids(&["dirt", "stone", "air"]), &lock);
        assert_eq!(a.codes["air"], 0);
        assert_eq!(a.codes["stone"], 1);
        assert_eq!(a.codes["dirt"], 2);
        assert!(a.tombstones.is_empty());
    }

    #[test]
    fn a_removed_id_leaves_its_code_reserved() {
        let lock = lock_with("block", &[("air", 0), ("mud", 1), ("dirt", 2)]);
        // `mud` is gone from content; `sand` is new and must NOT take code 1.
        let a = assign_codes("block", &ids(&["air", "dirt", "sand"]), &lock);
        assert_eq!(a.tombstones, vec!["mud".to_string()]);
        assert_eq!(a.codes["sand"], 3);
        // The tombstone still occupies its slot in the next lock.
        assert!(a.next_lock.contains(&("mud".to_string(), 1)));
    }

    #[test]
    fn new_ids_take_the_lowest_free_slot_in_source_order() {
        let lock = Lock::default();
        let a = assign_codes("block", &ids(&["air", "stone", "dirt"]), &lock);
        assert_eq!(a.codes["air"], 0);
        assert_eq!(a.codes["stone"], 1);
        assert_eq!(a.codes["dirt"], 2);
    }

    #[test]
    fn assignment_is_idempotent() {
        let lock = Lock::default();
        let first = assign_kind_codes("block", &ids(&["air", "stone"]), &lock);
        let mut l2 = Lock::default();
        l2.set_kind("block", first.clone());
        let second = assign_kind_codes("block", &ids(&["air", "stone"]), &l2);
        assert_eq!(first, second);
    }

    #[test]
    fn integer_tables_reject_a_value_that_would_not_survive_the_store() {
        assert!(table_lit(ArrayKind::U8, 300.0, "MAT_X", 3).is_err());
        assert!(table_lit(ArrayKind::U8, -1.0, "MAT_X", 3).is_err());
        assert!(table_lit(ArrayKind::U8, 1.5, "MAT_X", 3).is_err());
        assert_eq!(
            table_lit(ArrayKind::U16, 65535.0, "MAT_X", 0).unwrap(),
            "65535"
        );
        assert_eq!(
            table_lit(ArrayKind::F32, f64::INFINITY, "MAT_X", 0).unwrap(),
            "f32::INFINITY"
        );
    }
}
