#!/usr/bin/env python3
"""Diff two `--dump-state` JSONs by ABSOLUTE cell coordinate.

The `cells` block is a 21x21 window centred on the body, and the body moves
between runs. Comparing the two `front` arrays row by row therefore compares
two different places in the world, and the answer it gives is not a small error
— it is nonsense. Doing exactly that on the dig-a-shaft pair reported 242
changed cells for a dig that changed 53. Every cell in the shifted band reads
as changed because it is being held up against whatever happened to be nine
rows above it.

So the window is reconstructed to world coordinates —
`(centre[0] - radius + i, centre[1] - radius + j)` for column i, row j — and
only cells present in BOTH windows are compared. The overlap is the answer;
the rest is not comparable and is not counted. When the two windows share no
cells at all this says so, loudly, rather than reporting zero differences.

Standard library only. No numpy, no PIL, none of which is on this box, and
none of which this needs: the payload is one small JSON object and one 21x21
grid of integers.

Material names are parsed out of `crates/godgame-data/src/blocks.rs` at run
time rather than copied into a table here. That file is generated by contentc,
so a table copied here would go stale silently the first time a block is added
and would not fail any gate.

Exit status: 0 if the two dumps are equivalent, 1 if they differ, 2 if a file
could not be read.
"""
import argparse
import json
import os
import re
import sys

# Floats in a dump are float32 positions and a wall-clock day fraction. Across
# four same-tree runs of two scenarios everything was bit-identical except
# `clock.t`, which drifted by up to 5.6e-5 because the world clock advances on
# wall time. 1e-3 sits ~18x above that measured noise floor and far below
# anything the sim can mean: cells are 5px, so a real positional change is at
# least 1.0, and health and counts are whole numbers.
TOL = 1e-3

# These carry their own sections; everything else top-level is a scalar.
STRUCTURED = ("inventory", "mobs", "cells")

BLOCKS_RS = "crates/godgame-data/src/blocks.rs"
BLOCK_RECORD = re.compile(r'id:\s*"([A-Za-z0-9_]+)"\s*,\s*code:\s*(\d+)\s*,')


class Fail(Exception):
    """A bad input file, reported as a line rather than a traceback."""


def material_names():
    """code -> id, parsed from the generated block table. Empty if not found."""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, BLOCKS_RS)
    try:
        with open(path, "r") as fh:
            text = fh.read()
    except OSError:
        print(f"warning: no {BLOCKS_RS}; showing raw codes", file=sys.stderr)
        return {}
    return {int(code): ident for ident, code in BLOCK_RECORD.findall(text)}


def load(path):
    try:
        with open(path, "r") as fh:
            doc = json.load(fh)
    except FileNotFoundError:
        raise Fail(f"{path}: no such file")
    except OSError as exc:
        raise Fail(f"{path}: {exc.strerror}")
    except json.JSONDecodeError as exc:
        raise Fail(f"{path}: not valid JSON (line {exc.lineno}: {exc.msg})")
    if not isinstance(doc, dict):
        raise Fail(f"{path}: top level is {type(doc).__name__}, expected an object")
    return doc


def grid_of(doc, path, layer):
    """Validate one cell layer and return it, or None if the dump has no cells."""
    cells = doc.get("cells")
    if cells is None:
        return None
    if not isinstance(cells, dict):
        raise Fail(f"{path}: `cells` is not an object")
    for key in ("centre", "radius", layer):
        if key not in cells:
            raise Fail(f"{path}: `cells` has no `{key}`")
    centre, radius = cells["centre"], cells["radius"]
    if not (isinstance(centre, list) and len(centre) == 2):
        raise Fail(f"{path}: `cells.centre` is not a [x, y] pair")
    if not isinstance(radius, int) or radius < 0:
        raise Fail(f"{path}: `cells.radius` is not a non-negative integer")
    size = 2 * radius + 1
    rows = cells[layer]
    if not isinstance(rows, list) or len(rows) != size:
        got = len(rows) if isinstance(rows, list) else type(rows).__name__
        raise Fail(f"{path}: `cells.{layer}` has {got} rows, expected {size}")
    for j, row in enumerate(rows):
        if not isinstance(row, list) or len(row) != size:
            got = len(row) if isinstance(row, list) else type(row).__name__
            raise Fail(f"{path}: `cells.{layer}` row {j} has {got} cells, expected {size}")
    return rows


def same(x, y):
    if isinstance(x, bool) or isinstance(y, bool):
        return x is y
    if isinstance(x, (int, float)) and isinstance(y, (int, float)):
        return abs(x - y) <= TOL
    return x == y


def show(v):
    if isinstance(v, bool) or not isinstance(v, float):
        return str(v)
    return f"{v:.6g}"


def flatten(value, prefix, out):
    """Scalar leaves of a nested object, keyed by dotted path. Lists are skipped;
    every list in a dump is a structured section with its own comparison."""
    if isinstance(value, dict):
        for k, v in value.items():
            flatten(v, f"{prefix}.{k}" if prefix else k, out)
    elif not isinstance(value, list):
        out[prefix] = value


def scalars(a, b):
    """Every differing top-level scalar. Walked generically rather than from a
    fixed field list, so a field added to the dump is diffed without a change
    here."""
    flat_a, flat_b = {}, {}
    keys = [k for k in dict.fromkeys(list(a) + list(b)) if k not in STRUCTURED]
    lines = []
    for key in keys:
        va, vb = a.get(key, "<absent>"), b.get(key, "<absent>")
        # A whole section going null (`player` on a dead body) is one fact, not
        # seven; do not explode it into a field-by-field diff against nothing.
        if va is None or vb is None:
            if va is not vb:
                lines.append((key, "null" if va is None else "present",
                              "null" if vb is None else "present"))
            continue
        flatten(va, key, flat_a)
        flatten(vb, key, flat_b)
    for key in dict.fromkeys(list(flat_a) + list(flat_b)):
        va = flat_a.get(key, "<absent>")
        vb = flat_b.get(key, "<absent>")
        if not same(va, vb):
            lines.append((key, show(va), show(vb)))

    print("== scalars ==")
    if not lines:
        print(f"  no differences beyond a tolerance of {TOL:g}")
        return False
    width = max(len(k) for k, _, _ in lines)
    for key, was, now in lines:
        print(f"  {key:<{width}}  {was} -> {now}")
    return True


def totals(inv):
    """Item id -> count, summed over slots. The slot a thing sits in is not the
    fact under test; how much of it there is, is."""
    out = {}
    if not isinstance(inv, dict):
        return out
    for slot in inv.get("slots") or []:
        item = slot.get("item")
        if item is None:
            continue
        out[item] = out.get(item, 0) + (slot.get("count") or 0)
    return out


def inventory(a, b):
    ta, tb = totals(a.get("inventory")), totals(b.get("inventory"))
    gained, lost, changed = [], [], []
    for item in sorted(set(ta) | set(tb)):
        was, now = ta.get(item, 0), tb.get(item, 0)
        if was == now:
            continue
        (gained if was == 0 else lost if now == 0 else changed).append((item, was, now))

    print("\n== inventory ==")
    if not (gained or lost or changed):
        print("  unchanged")
    for label, rows in (("gained", gained), ("lost", lost), ("changed", changed)):
        for item, was, now in rows:
            if label == "gained":
                print(f"  gained   {item} x{now}")
            elif label == "lost":
                print(f"  lost     {item} x{was}")
            else:
                print(f"  changed  {item}  {was} -> {now}")
    return bool(gained or lost or changed)


def census(mobs):
    out = {}
    for mob in mobs or []:
        key = mob.get("id", "<unnamed>")
        out[key] = out.get(key, 0) + 1
    return out


def mobs(a, b):
    """A census, not a matching. Mobs carry no stable identity between runs —
    `id` is the species — so claiming a particular grubling moved would be an
    invention."""
    ma, mb = a.get("mobs") or [], b.get("mobs") or []
    ca, cb = census(ma), census(mb)
    print("\n== mobs ==")
    print(f"  count  {len(ma)} -> {len(mb)}")
    rows = [(k, ca.get(k, 0), cb.get(k, 0)) for k in sorted(set(ca) | set(cb))]
    width = max((len(k) for k, _, _ in rows), default=0)
    for key, was, now in rows:
        mark = "" if was == now else f"   ({now - was:+d})"
        print(f"    {key:<{width}}  {was} -> {now}{mark}")
    return len(ma) != len(mb) or ca != cb


def window_of(doc):
    cells = doc["cells"]
    cx, cy = cells["centre"]
    r = cells["radius"]
    return cx - r, cy - r, cx + r, cy + r


def compare_layer(rows_a, rows_b, box_a, box_b, overlap, names):
    """Differences in one layer, keyed by absolute cell coordinate."""
    x0, y0, x1, y1 = overlap
    ax0, ay0 = box_a[0], box_a[1]
    bx0, by0 = box_b[0], box_b[1]
    transitions = {}
    changed = set()
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            va = rows_a[y - ay0][x - ax0]
            vb = rows_b[y - by0][x - bx0]
            if va != vb:
                changed.add((x, y))
                key = (va, vb)
                transitions[key] = transitions.get(key, 0) + 1
    return changed, transitions


def name_of(code, names):
    return names.get(code, str(code))


def report_layer(label, changed, transitions, area, names):
    print(f"  {label}: {len(changed)} of {area} overlapping cells differ")
    if not transitions:
        return
    rows = sorted(transitions.items(), key=lambda kv: (-kv[1], kv[0]))
    pairs = [(f"{name_of(a, names)} -> {name_of(b, names)}", n) for (a, b), n in rows]
    width = max(len(p) for p, _ in pairs)
    for text, count in pairs:
        print(f"    {text:<{width}} : {count}")


def draw(overlap, front_changed, wall_changed):
    """An ASCII map of the overlap. The count says how much moved; only the map
    says what shape it was, which is how you tell a dug shaft from a landslide."""
    x0, y0, x1, y1 = overlap
    cols = x1 - x0 + 1
    print("\n  map of the overlap  (. same, F front, W wall, B both)")
    ruler = [" "] * cols
    for i in range(0, cols, 5):
        label = str(x0 + i)
        if i + len(label) <= cols:
            ruler[i : i + len(label)] = label
    pad = len(str(max(abs(y0), abs(y1)))) + (1 if y0 < 0 or y1 < 0 else 0)
    print(f"    {' ' * pad}  {''.join(ruler)}")
    for y in range(y0, y1 + 1):
        band = ""
        for x in range(x0, x1 + 1):
            f = (x, y) in front_changed
            w = (x, y) in wall_changed
            band += "B" if f and w else "F" if f else "W" if w else "."
        print(f"    {y:>{pad}}  {band}")


def layers(doc, path):
    """Both cell layers, validated. Done before anything is printed so a short
    or malformed dump fails as one line rather than half a report."""
    front = grid_of(doc, path, "front")
    if front is None:
        return None
    return front, grid_of(doc, path, "wall")


def cells(a, b, grids_a, grids_b, path_a, path_b, names, want_map, lead):
    print(f"{lead}== cells ==")
    if grids_a is None or grids_b is None:
        which = path_a if grids_a is None else path_b
        print(f"  {which} has no `cells` block; nothing to compare")
        return grids_a is not grids_b
    front_a, wall_a = grids_a
    front_b, wall_b = grids_b

    box_a, box_b = window_of(a), window_of(b)
    ca, cb = a["cells"]["centre"], b["cells"]["centre"]
    print(f"  window centre  {ca} -> {cb}")
    if ca != cb:
        print(f"  the body moved by ({cb[0] - ca[0]:+d}, {cb[1] - ca[1]:+d}) cells; "
              "comparing by absolute coordinate over the overlap only")

    x0 = max(box_a[0], box_b[0])
    y0 = max(box_a[1], box_b[1])
    x1 = min(box_a[2], box_b[2])
    y1 = min(box_a[3], box_b[3])
    if x0 > x1 or y0 > y1:
        print("  NO OVERLAP: the two windows share no cells.")
        print(f"    a covers x {box_a[0]}..{box_a[2]}, y {box_a[1]}..{box_a[3]}")
        print(f"    b covers x {box_b[0]}..{box_b[2]}, y {box_b[1]}..{box_b[3]}")
        print("  The cell layers cannot be compared. This is not zero differences.")
        return True

    overlap = (x0, y0, x1, y1)
    cols, rows = x1 - x0 + 1, y1 - y0 + 1
    area = cols * rows
    full = (2 * a["cells"]["radius"] + 1) ** 2
    print(f"  overlap        x {x0}..{x1}, y {y0}..{y1}  "
          f"= {cols} x {rows} = {area} cells of {full}")

    fc, ft = compare_layer(front_a, front_b, box_a, box_b, overlap, names)
    wc, wt = compare_layer(wall_a, wall_b, box_a, box_b, overlap, names)
    report_layer("front", fc, ft, area, names)
    report_layer("wall ", wc, wt, area, names)
    if want_map and (fc or wc):
        draw(overlap, fc, wc)
    return bool(fc or wc)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Diff two godgame --dump-state JSONs by absolute cell coordinate.")
    ap.add_argument("a", help="the baseline dump")
    ap.add_argument("b", help="the dump to compare against it")
    ap.add_argument("--cells-only", action="store_true",
                    help="only the cell layers; skip scalars, inventory and mobs")
    ap.add_argument("--no-map", action="store_true", help="skip the ASCII map")
    args = ap.parse_args(argv)

    try:
        a, b = load(args.a), load(args.b)
        grids_a = layers(a, args.a)
        grids_b = layers(b, args.b)
    except Fail as exc:
        print(f"statediff: {exc}", file=sys.stderr)
        return 2

    names = material_names()
    print(f"{args.a}  ->  {args.b}\n")
    differs = False
    if not args.cells_only:
        differs |= scalars(a, b)
        differs |= inventory(a, b)
        differs |= mobs(a, b)
    differs |= cells(a, b, grids_a, grids_b, args.a, args.b, names,
                     not args.no_map, "\n" if not args.cells_only else "")

    print("\n" + ("dumps differ" if differs else "dumps are equivalent"))
    return 1 if differs else 0


if __name__ == "__main__":
    sys.exit(main())
